### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by CvH** [anxdpanic/plugin.video.twitch#1]
Hi, try to open WhiteRa Stream at Twitch (runs at second pc well, also at opera addon). At the Twitch Addon it trys to load -> loop no exit possible.

http://paste.org/52236
...
ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
...

Openelc XBMC

**Comment by kokarn** [comment]
Have you tried to update to the latest version of librtmp?

http://wiki.xbmc.org/index.php?title=HOW-TO:Update_librtmp

Fixes a lot of issues and this does sound like a librtmp related one.

**Comment by CvH** [comment]
works now :)
