### ISSUE TITLE
Past Broadcasts starting at part 2

### ISSUE THREAD

**Issue by defoeyido** [anxdpanic/plugin.video.twitch#103]
Any time I try and play a past broadcast, it starts off at part 2 instead of 1, can anyone take a look at that? Thanks

**Comment by ingwinlu** [comment]
Would be helpful if you could point us to the broadcast that is not working
Am 20.12.2014 19:29 schrieb "defoeyido" notifications@github.com:

**Comment by defoeyido** [comment]
Hey, it happens on every single broadcast I've tried the last few days. For example, if I try and load: http://www.twitch.tv/sandyravage/b/601120169 in xbmc, it starts at part 2 via the past broadcasts section in xbmc

**Comment by MrSprigster** [comment]
Fixed! (https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/archive/master.zip)

Sprig

**Comment by defoeyido** [comment]
This issue has come back again, can anyone take a look please

**Comment by MrSprigster** [comment]
Hi, 

I've just tested the current version (1.2.0) and I'm not able to reproduce your issue. 

Please try a fresh install of 1.2.0 and if the problem persists post again here with details of the steps you took which lead to the unexpected behavior.

https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/archive/master.zip

Thanks,

Sprig
