### ISSUE TITLE
Error with quality setting when unavailable for stream.

### ISSUE THREAD

**Issue by Adminjojo** [anxdpanic/plugin.video.twitch#104]
Hello,

If i set 720p in the addon settings, and if the stream is only avalaible in source, the addon will fail to launch the stream, i will need to select "best quality possible" in the addon settings.

I's actigin like this since a few days now.
XBMC Gotham / Windows7
error log :

13:38:49 T:1292  NOTICE: -->Python Interpreter Initialized<--
13:38:49 T:1292  NOTICE: [xbmcswift2] Request for "/playLive/streamer/" matches rule for function "playLive"
13:38:50 T:1292   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 2: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\plugin.video.twitch\default.py", line 251, in <module>
                                                PLUGIN.run()
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(*_items)
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\plugin.video.twitch\default.py", line 20, in wrapper
                                                return func(_args, **kwargs)
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\plugin.video.twitch\default.py", line 200, in playLive
                                                resolver.saveHLSToPlaylist(name,videoQuality,plpath)
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\plugin.video.twitch\twitch.py", line 236, in saveHLSToPlaylist
                                                playlist = self._saveHLSToPlaylist(data,maxQuality)
                                              File "C:\Users\Admin\AppData\Roaming\XBMC\addons\plugin.video.twitch\twitch.py", line 289, in _saveHLSToPlaylist
                                                playlist = '\n'.join(playlist) + '\n'
                                            TypeError: sequence item 2: expected string, NoneType found
                                            -->End of Python script error report<--
13:38:50 T:4276   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/streamer/]
13:38:50 T:4880  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by Giacom** [comment]
I receive this error too when watching streams with very low viewer count, which do not get the quality settings. A solution would be to make it so that if the plugin detects the stream does not support the requested quality then it defaults to "Source", like it does on the flash player.

**Comment by ingwinlu** [comment]
^ this is already how it should work, and how it did work.

i have not had time to check what they did change exactly so our parsing fails, and i won't have till next month. if someone else wants to step up i would gladly review changes.

**Comment by Giacom** [comment]
I had a look and I found the check here.

https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/blob/master/twitch.py#L248
```Python
    #split off from main function so we can feed custom data for test cases + speedtest
    def _saveHLSToPlaylist(self, data, maxQuality):
        if(maxQuality>=len(Keys.QUALITY_LIST_STREAM)): #check if maxQuality is supported
            raise TwitchException()
```

There is a function called _bestMatchForChosenQuality() which has the code to sort the quality but that is used in a function which is unused itself.

**Comment by Giacom** [comment]
Sorry, yeah you're right now that I look at it. I am unable to debug this too and looking at the code alone does not give me any hints; having the quality values represent indexes of lists is confusing.

**Comment by MrSprigster** [comment]
Fixed in https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/commit/5ed6b8c760bdffb1d3825255dc331061ac48bdec

**Comment by Giacom** [comment]
Awesome thanks.
