### ISSUE TITLE
VODs no longer working on some videos

### ISSUE THREAD

**Issue by defoeyido** [anxdpanic/plugin.video.twitch#106]
Hey, seem to be having a problem viewing certain VODs on new streams like this one: http://www.twitch.tv/hutch/v/3709509

If you try it in XBMC, it gives an error

**Comment by MrSprigster** [comment]
Looks as though these VODs (id beginning with v) aren't chunked hence the error when trying to load them.

https://api.twitch.tv/api/videos/v3709509

Returns:
chunks":{"audio_only":[],"medium":[],"mobile":[],"high":[],"low":[],"chunked":[]}

No chunks to play :(... 

Working Past Broadcast (CobaltStreak):
https://api.twitch.tv/api/videos/c5928479

Unfortunately I don't have much time to look into this at the moment but the following URL may be of use to someone who wants to take a look at making this work:

https://gist.github.com/EhsanKia/0330132521ee3c6caf7e

Thanks,

Sprig

**Comment by ingwinlu** [comment]
good news everybody, i am currently working on redoing python-twitch, and including unit tests for video playback.

i already reversed the new vod system, my changes to twitch.py will be huge though, will take a while.
