### ISSUE TITLE
Network underrun with 1920x1080@60

### ISSUE THREAD

**Issue by Tele42** [anxdpanic/plugin.video.twitch#107]
First of all, great job on making and maintaining this plugin.

I am a raspberry pi user with RaspBMC running at 850 Mhz (twitch plugin 1.1.8).

When I select a stream with 1920x1080 and more than 30fps, the stream will play smoothly for about 10-15 seconds, then have constant mini-stutters and start falling behind wall clock time. the overlay indicates the current playback position is right up against the total length, indicating the buffer is running out constantly. ~~The Kodi System info section reports the arm cpu is between 90-95% usage.~~ top via ssh reports no more than 30% total cpu usage. 1920@1080@30 works with no problem.

As of the writing of this issue report, the main twitch account covering PAX South 2015 is an example of 1920x1080 above 30 fps.

Please let me know if I can provide any other information.

**Comment by ingwinlu** [comment]
works fine for me (without xbmc)
omxplayer does not go above 50% cpu

edit: more competent answer:
this plugin does only resolve the url for xbmc/omxplayer/whatever to play back, we don't do anything else so your performance issues are not related to the plugin

**Comment by Tele42** [comment]
Closing as misfiled.
