### ISSUE TITLE
Trying to list channels which are being followed by the username creates a script failure.

### ISSUE THREAD

**Issue by Giacom** [anxdpanic/plugin.video.twitch#11]
When I tried to view channels which I followed, via choosing the "Following" option, and after entering a valid username, the script failed. This means I cannot view a list of channels which I am following.

**Comment by StateOfTheArt89** [comment]
Hey,
i just tested version 0.2.2 and 0.2.5 on xbmc frodo rc2 with windows 7. Both were working fine.

Could you name the xmbc version, the version of the twitch plugin and maybe your twitchtv account name? (I'm just interested if your twitch account name contains any special characters).

**Comment by Giacom** [comment]
Thanks for the reply.

Well I was using a custom xmbc version for the raspberry pi. The version number for it says: XBMC 12.0-RC2 Git:20121226 - 7d8c737 (Compiled Dec 27 2012)

The plugin itself says version 0.2.2. My username is "giacomand".

**Comment by Zialus** [comment]
I'm having the same issue.

Version - Latest Nightly
OS - Mountain Lion
Username - "Zialus"

**Comment by StateOfTheArt89** [comment]
Ok, i was able to reproduce this error on my raspberry pi with raspbmc (twitch plugin 0.2.2).

```
07:53:34 T:3035681504   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?mode=following&siteIndex=0&url
07:53:34 T:3035681504   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?mode=following&siteIndex=0&url) failed
07:53:34 T:2917135376  NOTICE: Thread Background Loader start, auto delete: false
07:53:40 T:2831225872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: object of type 'NoneType' has no len()
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 344, in <module>
                                                createFollowingList()
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 71, in createFollowingList
                                                if len(name) <= 0:
                                            TypeError: object of type 'NoneType' has no len()
                                            -->End of Python script error report<--
```

This kind of error seems to occur if the stream doesn't contain a status message.

I think in the current version 0.2.5 this error is fixed. But I'm going to try it out by myself...

**Comment by Giacom** [comment]
Yeah it works perfectly in 0.2.5. Thanks.

**Comment by Zialus** [comment]
It's still not working for me

**Comment by Giacom** [comment]
What I did was downloaded the plugin from github ( https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/archive/master.zip ) and put it onto a USB stick (don't unzip it). You can then find an option in XBMC to install a plugin from a zip file.
