### ISSUE TITLE
Playback suddenly stopped

### ISSUE THREAD

**Issue by Klueze** [anxdpanic/plugin.video.twitch#112]
Hello there,

since today i got a problem with the playback from this plugin. i can select the stream and press play, then it will do the standard "start playback" thing and then it says working on the bottom right side for about 2 minuts. then i get an error saying i should look into the login file, witch can be found here: 

http://pastebin.com/ch4JZwVU

As you can see its spamming something like ERROR: CCurlFile::GetCookies - invalid cookie:

I tryed: Update Windows, Update Graphicsdriver, Update to the newest Kodi Version, reinstall the twitch plugin (settings werent removed i guess)

Can you help me? thx

**Comment by ingwinlu** [comment]
`05:56:26 T:2820  NOTICE: DVDPlayer: Opening: http://video3.fra01.hls.twitch.tv/hls8/beyondthesummit_13024770224_201163074/chunked/py-index-live.m3u8?token=id=899220839492984079,bid=13024770224,exp=1423371218,node=video3-1.fra01.hls.justin.tv,nname=video3.fra01,fmt=chunked&sig=e722e4ff4e8dad63ccc590b70da98799de3d1528` shows the plugin did its work correctly, everything after that is not related to this plugin

**Comment by Klueze** [comment]
So where can i get an answer to this bug?

**Comment by ingwinlu** [comment]
http://bit.ly/1umuX3D

**Comment by Klueze** [comment]
couldnt it be possible that the link the plugin passes is wrong? if i activate debug mode it says:

04:00:38 T:1504   DEBUG: CFileCache::Open - opening <hls113/cobaltstreak_13042483152_201696670/chunked/py-index-live.m3u8> using cache
04:00:38 T:1504   DEBUG: CurlFile::Open(0867EC20) http://video54.fra01.hls.twitch.tv/hls113/cobaltstreak_13042483152_201696670/chunked/py-index-live.m3u8?token=id=7061167187744215870,bid=13042483152,exp=1423450668,node=video54-1.fra01.hls.justin.tv,nname=video54.fra01,fmt=chunked&sig=481f788d7adad2cc00f747f0b067071d1a1f1bb7

the CurlFile seems to be the problem and the file it trys to open is exactly the string that was passed to the dvdplayer

anyways, i fixed it with a complete reinstall of kodi and i had to delete the usersettings

**Comment by ingwinlu** [comment]
if you insist its the plugins fault do the following:
- generate a fresh link
- open it up in vlc
