### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by SirJonthe** [anxdpanic/plugin.video.twitch#113]
Playback fails for some streams, usually the less popular ones. Log below:

http://pastebin.com/ik5LFt9a

Note that this log was created using the 1.1.8 version on XBMC 12 on Ubuntu 14.04, although it is present on all other platforms I tested it on (RPi Openelec 3.2, XBMC 12 on OSX 10.6), and is still present in version 1.3.0.

It has been speculated that the issue relates to setting the video quality to anything but "Best possible" and watching streams without transcoding options, and indeed it is resolved when setting the quality to "Best possible".

**Comment by ingwinlu** [comment]
Update the plugin then. Old bug is old.

i hardly believe that the bug is still in 1.3.0 since the code that was generating the error in the log is no longer around

**Comment by MrSprigster** [comment]
Although it is an unlikely coincidence, unfortunately, it seems this bug has reared its head again in 1.3.0. 

When testing on all qualities but Best Possible and attempting to view a stream which does not have transcoding options, the stream fails to play.

Fixed in 1.3.1
