### ISSUE TITLE
Advertisements not working

### ISSUE THREAD

**Issue by gersilex** [anxdpanic/plugin.video.twitch#116]
Hey there,

I want to support twitch broadcasters by watching the advertisements.
The ads are not inside the video stream and usually are overlayed over the normal player window.

Is there a way to implement this and optionally disable it?

**Comment by ingwinlu** [comment]
Hey,

last time i checked the ads are swfs loaded above the actual stream, would be tricky to do something like this

**Comment by MrSprigster** [comment]
Hey,

As far as I'm aware, the Twitch API doesn't provide us with triggers to let us know when to play the ads even if we managed to implement the ability to play them which as @ingwinlu said; it wouldn't be easy to do as they are in a completely different format to the stream itself.

If you'd like to support the broadcasters via advertising there's a strong likelihood that you'll have to stick to a browser I'm afraid.

Sprig
