### ISSUE TITLE
doesn't show media info if a stream is opened from outside the plugin

### ISSUE THREAD

**Issue by disrupted** [anxdpanic/plugin.video.twitch#117]
this addon works really well in my opinion, however I have one issue that really bothers me. I typically only watch one channel on twitch (rbtv but doesn't matter). If I open the twitch addon, search for a stream and open it from within the addon everything looks good (info labels and stream thumbnail on fullscreen playback): ![screenshot with thumb](http://i.imgur.com/4oEhBLD.png)

but as I said I only watch one particular channel so I created a favourite and placed it on my homescreen so I can directly launch this stream. If I do so the media info is completely missing (neither info labels nor thumbnail): ![screenshot without thumb](http://i.imgur.com/I6j4KkY.png)

nevertheless great job! cheers, freem@n

**Comment by BadBone2k** [comment]
Same problem here. Same channel, same favourite, same py-index-live.m38u :-)

**Comment by disrupted** [comment]
@MrSprigster why was this issue closed? is it fixed?

**Comment by anxdpanic** [comment]
@freeman212 this should have been resolved around: https://github.com/MrSprigster/Twitch-on-Kodi/commit/c4d5652657699afe15d4387208637f8362470983 I believe

**Comment by MrSprigster** [comment]
Yup

**Comment by disrupted** [comment]
@anxdpanic @MrSprigster ah, good to know :)
