### ISSUE TITLE
Resume past broadcasts

### ISSUE THREAD

**Issue by lawrencecurtis** [anxdpanic/plugin.video.twitch#119]
Is it possible to add a resume functionality too past broadcast, as most that i was are several hours long so i tend to watch them in chunks, it would be good if i could start off from where i left off like i can with a Movie or TV show

Sadly my python is not very good but I just wanted to ask how possible this was?

Many thanks
-Lawrence

**Comment by thaweed** [comment]
I would love to see this

**Comment by nDmitry** [comment]
Shouldn't this be handled by Kodi?

**Comment by spiffomatic64** [comment]
according to http://forum.kodi.tv/showthread.php?tid=229951 it looks like its up to "us" to implement this... Shouldn't be too hard to keep a small cache of streams and watched/resume. xbmc.player().getTime()  onPlayBackEnded() etc

**Comment by thaweed** [comment]
This is already working fine since  [this commit](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/commit/c4d5652657699afe15d4387208637f8362470983)
Thank you anxdpanic!
