### ISSUE TITLE
Some streams cause codec error

### ISSUE THREAD

**Issue by StateOfTheArt89** [anxdpanic/plugin.video.twitch#12]
Some streams do not work while others work flawlessly. I guess it's a codec problem?

From the log:

```
17:28:34 T:4376 WARNING: could not find codec parameters for rtmp://199.9.255.175/app/jtv_FMN_mCJgkQwpNuC3 jtv=329437f408d8c15f5308dd54bdea56a4a334e09c:{\22swfDomains\22:\20[\22justin.tv\22,\20\22jtvx.com\22,\20\22xarth.com\22,\20\22twitchtv.com\22,\20\22twitch.tv\22,\20\22newjtv.com\22,\20\22jtvnw.net\22,\20\22wdtinc.com\22,\20\22imapweather.com\22,\20\22facebook.com\22,\20\22starcrafting.com\22],\20\22streamName\22:\20\22jtv_FMN_mCJgkQwpNuC3\22,\20\22expiration\22:\201356629262.1224761,\20\22geo_ip\22:\20\222.248.124.229\22,\20\22server\22:\20\22video3-2.ams01\22} swfUrl=http://www-cdn.jtvnw.net/widgets/live_embed_player.r95f2431b85bbe338f413de2e48e8e2aea94814a8.swf?channel=tackblossom&referer=http://www.justin.tv/tackblossom&userAgent=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64;%20rv:6.0)%20Gecko/20100101%20Firefox/6.0&channel=tackblossom swfVfy=1 live=1 Pageurl=http://www.justin.tv/tackblossom
```

Full log:
http://pastebin.com/qzgMLs8j

Running xbmc 11.0 on Windows 7. 
~ kattapa

**Comment by Nyber** [comment]
Seeing this as well.  I believe it is codec 11.0; Speex.  

XBMC claims Speex support (http://wiki.xbmc.org/index.php?title=Features_and_supported_formats): 

Audio formats: MIDI, AIFF, WAV/WAVE, AIFF, MP2, MP3, AAC, AACplus (AAC+), Vorbis, AC3, DTS, ALAC, AMR, FLAC, Monkey's Audio (APE), RealAudio, SHN, WavPack, MPC/Musepack/Mpeg+, Shorten, Speex, WMA, IT, S3M, MOD (Amiga Module), XM, NSF (NES Sound Format), SPC (SNES), GYM (Genesis), SID (Commodore 64), Adlib, YM (Atari ST), ADPCM (Nintendo GameCube), and CDDA.

Dump here:
http://openelec.tv/forum/68-audio/63255-codec-86052-fusion-build

I also checked my machine, it has both Speex and Opus (newer version of Speex) installed. 

openelec:~ # ffmpeg -codecs
ffmpeg version 1.2 Copyright (c) 2000-2013 the FFmpeg developers
built on Apr 4 2013 23:06:09 with gcc 4.7.2 (GCC)
configuration: --prefix=/usr --cpu=btver1 --arch=x86_64 --enable-cross-compile --cross-prefix=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu- --sysroot=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/x86_64-openelec-linux-gnu/sysroot --sysinclude=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/include --target-os=linux --nm=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-nm --ar=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-ar --as=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc --cc=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc --ld=/home/openelec/OpenELEC.tv/build.OpenELEC-Fusion.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc --host libavutil 52. 18.100 / 52. 18.100
libavcodec 54. 92.100 / 54. 92.100
libavformat 54. 63.104 / 54. 63.104
libavdevice 54. 3.103 / 54. 3.103
libavfilter 3. 42.103 / 3. 42.103
libswscale 2. 2.100 / 2. 2.100
libswresample 0. 17.102 / 0. 17.102
libpostproc 52. 2.100 / 52. 2.100
..A.L. speex Speex
..A.L. opus Opus (Opus Interactive Audio Codec)

**Comment by ccaspers** [comment]
old and probably not related to the plugin itself
