### ISSUE TITLE
OpenElec 5.0.5 and Raspberry Pi 2 support

### ISSUE THREAD

**Issue by hfb11** [anxdpanic/plugin.video.twitch#122]
Sorry for writting an issue but yesterday i tried to install your plugin in OpenElec 5.0.5 on my new Raspberry Pi 2. But i get an error message, that i can't install it. I'm a noob in the XBMC universe (installed my first XBMC on last saturday) but i'm software developer to. I think it doesn't run because of the changed processor structur (from ARM11 single core to ARMv7 quad core) or something else. I would by very happy if your plugin also run on the "new" Raspberry/Openelec system.

**Comment by Tele42** [comment]
I did not encounter this issue on my Raspberry Pi 2 with OpenElec (5.0.2 -> 5.0.5) (Raspberry Pi 2 build) noobs install or with OSMC's Raspberry Pi 2 build.
