### ISSUE TITLE
Games stream list not updating when added to Favourites

### ISSUE THREAD

**Issue by zulunia** [anxdpanic/plugin.video.twitch#127]
After browsing to a specific game via the Games Menu, the list of live games is presented as normal.

However, when a game is added to Favourites, the next time the list is brought up via the Favourites menu the list of live games hasn't refreshed, as in, still showing the original list. This is an issue if it's a few days/hours old.

The only way to get a fresh list of live streams is browsing through the Games menu of the addon, and for uncommon games (in my case) this can be over 15 pages deep. 

Is there a method to refresh (whether it's simply deleting a cache or something) the Games list if it's accessed from Favourites in Kodi ?

Alternatively, is there a way to simply bookmark a particular game in the addon itself so when you look for it a day later the stream list is current?

**Comment by LordPanzar** [comment]
I too have this exact problem, I would really love a solution for this.

**Comment by Smultie** [comment]
Seconded!

**Comment by Poperze** [comment]
Just the question I was looking for. My current workaround is to reboot the device, would be awesome to get some kind of refresh-option or a non-cached list when I pick a favorite.
