### ISSUE TITLE
[Raspberry Pi] freezes after closing stream on TwitchTV plugin

### ISSUE THREAD

**Issue by logock** [anxdpanic/plugin.video.twitch#13]
I'm using Xbian on my Raspberry Pi currently (also tested this on Raspbmc).
I can perfectly open any stream but I'm not able to close it afterwards!
As soon as I hit the "Stop Button" my whole Raspberry Pi freezes and I'm not able to do anything anymore.

I hope you can look into this issue and I would be really glad if you could fix it somehow.

Thanks in advance!

Here's my log file: http://pastebin.com/Ez1w5Yij

**Comment by StateOfTheArt89** [comment]
Hey,
which version of the twitch plugin are you using?
I tested version 0.2.2 a while ago on my raspberry pi (with raspbmc) and it seemed to work fine, but i'm going to check that again.

**Comment by logock** [comment]
I'm not entirely sure but it should've been the latest version since I installed it yesterday for the first time. I will check on that. Thanks for the reply.

**Comment by StateOfTheArt89** [comment]
Where did you get the add-on? If it is from GitHub, it should be 0.2.5 - in the official XBMC repository you will find version 0.2.2

**Comment by logock** [comment]
It was from the XBMC repository. I'm currently reinstalling my RPi on a second SD-card but I highly doubt it could be the SD card's fault..

EDIT: Yes it was the 0.2.2 version! I just checked it
EDIT2: Yep, tested a stream (League of Legends) and it froze again. :(

**Comment by StateOfTheArt89** [comment]
Ok, thanks...
I will take a closer look on it

**Comment by logock** [comment]
I have no god damn idea how but it does work now finally. What I did was watching one stream pretty long (until it went offline and TwitchTV automatically brought me to my menu) and afterwards (which I believe fixed the issue, don't ask me why) I downloaded the WIMP plugin to watch a video (and I believe it downloaded some other plugin for playback probably?) and I went back to TwitchTV to watch a stream and suddenly I could normally stop the stream just like it should be. I have no idea how it got fixed suddenly. Thanks for your help though...Sorry for causing such an uproar...

**Comment by StateOfTheArt89** [comment]
Oh, no problem.
Actually I did encounter similar errors when using fast forward/backward or stop, but only at 1080+ streams and not even on every try.
But i think (and hope) this is a problem due to the limited resources of the raspberry pi and maybe some problems with handling such amounts of data.

**Comment by logock** [comment]
A little update on my issue here...
Seems like the issue isn't with the plugin itself. It's as I noticed because of the video player. When I boot my Raspberry Pi and choose a livestream right away it won't work like I stated. BUT. When I open a WIMP video first (I believe any plugin which doesn't use livestreams) and after that a livestream then it will work perfectly and fine...
