### ISSUE TITLE
Audio offsync on raspberry pi 2 and other devices

### ISSUE THREAD

**Issue by neyoneit** [anxdpanic/plugin.video.twitch#132]
Hi,

many ppl have same problem, but they choose to not watch those streams on TV.. But I have already two that I cannot watch on TV and its kinda irritating.

Twitch streams that are off sync with audio, not possible to watch on kodi raspberry pi 2
http://www.twitch.tv/smitegame
http://www.twitch.tv/cryaotic

Here is full issue:
forum.kodi.tv/showthread.php?tid=134538&pid=2039888#pid2039888

Thanks for solving this issue.

Best regards,
neyoneit

**Comment by ingwinlu** [comment]
read the faq in the readme;

**Comment by MrSprigster** [comment]
Closing (issue outside scope of the addon)
