### ISSUE TITLE
Stuttering with lates version of OSMC

### ISSUE THREAD

**Issue by ad-ab** [anxdpanic/plugin.video.twitch#133]
Hi,
I am sorry to bother you all here. I am desperate and have got no help anywhere else and my problem is related to the Twitch.tv kodi addon. I have used osmc alpha4 and this addon worked flawlessly. Since upgrade to the release version, the twitch.tv playback is horrible and lagy, i have reinstalled, double checked everything, connection, lowering resoultion, setting advanced settings to buffer more data, nothing help. Anyone here having similar problems, any idea why is Kodi when playing twitch streams when everything else works without a problem?
Thank you anyone for help. 

X.

**Comment by MrSprigster** [comment]
See the FAQ. this add-on does not handle playback.

**Comment by ad-ab** [comment]
Like i said, im desperate, and just wanted to try. Thank you anyway for your answer.

**Comment by MrSprigster** [comment]
No problem at all. I had issues with buffering in the past due to my ISP’s routing and using a VPN solved the issue for me so it may be worth a try in such desperate times (I used www.privateinternetaccess.com).

Cheers,

Sprig

**Comment by ad-ab** [comment]
I have tried vpn to a different network, no change at all, i have tried all quality settings, all advanced.xml settings for kodi, complete reinstall, i have it connected over 1gb (tested) ethernet on a 240/24 Mb internet line. Other computers, even on wifi don't lag at all. I have some degree of computer skill, unfortunately i am not very skilled with linux so debugging kodi is a big unknown for me. The kodi forums had 0 help so far :-(

**Comment by Queuecumber** [comment]
@Xenik007 This could be related to #139

**Comment by ad-ab** [comment]
@Queuecumber I actually solved this issue by switching the (im not sure of the exact setting) video player...or decoder in the video playback settings. I can't access my OSMC atm but i will come back later and update both threads with the exact description of what i did.

**Comment by Queuecumber** [comment]
@Xenik007 Thats fantastic, it would be great to get a possible solution documented on here. Although I'm not sure what decoder settings there are outside of disabling VA-API/VDPAU.

**Comment by ad-ab** [comment]
@Queuecumber Settings - Video - Acceleration  and im not sure which exact option Allow hardware acceleration - OMXPayer (turned on), Allow hardware acceleration - MMAL (turned on). Please let me know if it helped, i will post on the other link.

**Comment by Queuecumber** [comment]
@Xenik007 Unfortunately I don't have either of those options

**Comment by ad-ab** [comment]
@Queuecumber :-( I have in my OSMC rPi2

**Comment by Queuecumber** [comment]
@Xenik007 those options may be specific to OSMC
