### ISSUE TITLE
"Best possible quality" is actually just "high", not "source"

### ISSUE THREAD

**Issue by Hubro** [anxdpanic/plugin.video.twitch#135]
Here is a comparison:

![2015-08-02 selection 01](https://cloud.githubusercontent.com/assets/597206/9024818/3482c78a-38e6-11e5-8c53-43fda2937a0a.png)

The top window is "Best possible quality" in Kodi, the middle VLC window is playing the stream in "high" and the bottom VLC window is playing it in "source". Even just by comparison you can clearly see that the bottom stream is much sharper than the top two. Please click the image to open it in full size if you are not convinced.

"Best possible quality" should absolutely pick the "source" quality and not "high". Especially in this case, where "source" means 1920x1080 and "high" means 1280x720.

**Comment by Hubro** [comment]
Wait, this is weird, I re-opened the stream and this time it's playing in 1080p. I guess this bug is a bit more complicated than I hoped.

**Comment by MrSprigster** [comment]
Hello Tomas,

When best possible quality is selected in the settings the add-on will
always play the highest quality stream offered to it by the Twitch API.

It's a possibility that Twitch only offered a 'high' option on your first
attempt, either erroneously or for a programmatically correct reason for
example; source only being available to subscribers of the channel.

Feel free to test further and if you find a repeatable scenario where you
receive the incorrect stream quality please do report it and ill look into
it.

Regards,

Sprig
