### ISSUE TITLE
Start showing channel from API

### ISSUE THREAD

**Issue by blddk** [anxdpanic/plugin.video.twitch#137]
This is either a question or a feature request... :)

Is it possible to start the addon, and have it start showing a channel, directly from the kodi api?

What I am hoping to do, is just calling something like this

```
http://kodi/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Addons.ExecuteAddon","params":{"addonid":"plugin.video.twitch","params":{"channel":"cohhcarnage"}}}
```

and then have it start showing the channel set in the params.

**Comment by blddk** [comment]
Okay, this is driving me cray... I don't know much of this programming language, so I learn as I go, and right now I am getting absolutely no where. Anyone know where to get some examples on how to do this? Maybe I can use that to get a step closer to what I try to do.

**Comment by disrupted** [comment]
Can't you just call it via favourites?

**Comment by blddk** [comment]
favourites? like at the bottom of the main window? What I would like to do, is to remotely control what it show, have another system check the twitch api, and decide which broadcaster to put on.. so it might even be some I dont even know it decide to pick and show
