### ISSUE TITLE
Lag and Buffering

### ISSUE THREAD

**Issue by Queuecumber** [anxdpanic/plugin.video.twitch#139]
So I've read the FAQ, I understand that your addon does not handle playback. 

However, a few weeks ago, twitch streams started lagging horribly for me. Before this, I was able to stream at "best possible" quality setting with no buffering. Now, even a 240p stream buffers every couple of mins. 

I've checked my download speed and nothing has changed there: a stable 54Mbps.

Also the twitch web player works flawlessly at source quality, no buffering issues at all.

Do you know of anything that might have changed in the Kodi video playback that could cause this? I am on Kodi 15.2-RC1

**Comment by kokarn** [comment]
Shouldn't the first two sentences make you not post this here? :P

"So I've read the FAQ, I understand that your addon does not handle
playback.

However, a few weeks ago, twitch streams started lagging horribly for me."

**Comment by pipinije** [comment]
I have exactly the same problem. It was working from the first time i installed it till few weeks ago without any problem at best quality. Now it's working as usual for few minutes then just start freezing and continuing until disconnecting from stream. If i start stream again same thing, working for few minutes like normal then starts freezing. I tried tinkering with buffer settings in kodi with no avail and tested my internet and home networking which are working normally without hiccups. So i dont think it's to do with faq. 
I dont even see so much buffering that's why i use term freezing, stream just freezes and maybe continues after a while or disconnect altogether.

**Comment by ingwinlu** [comment]
> This Addon does not handle any aspect of the playback of Twitch streams (that would be the XBMC Video Player), it simply tells XBMC what to play.

It does not matter that you have the same problem.

This plugin just provides an URL that is passed to the video player. It is the same url that the web player produces. Accept that the fault can not be in this plugin and move on.

**Comment by Queuecumber** [comment]
Really guys this is a rather off-putting reaction. I'm not sure if you didn't read my entire post or something. 

I'm asking if the author knows of any change to Kodi that would have caused such an issue. If this is a known bug, I can move on to the proper channels for resolving it. As this -only- effects the twitch plugin and no other streaming plugins I use, it makes sense to ask the question here to be redirected to better information.

This is -not- a request for the author of the twitch plugin to fix the bug, it is a request for any relevant information.

**Comment by ingwinlu** [comment]
Really you guy this is a rather off-putting reaction. I'm not sure if you didn't read my entire post or something.
- get the plugin
- resolve a playable url
- throw it into vlc

if it does work better than in kodi you have your culprit.

Also keep in mind that Twitch has phases where it barely works (mostly when the league of legends stuff is around) and kodi can not handle the automatic reconnect to the stream that the webplayer has.

**Comment by kokarn** [comment]
I'm sorry about the off-putting reaction.
But you are in the wrong place asking questions.

Nothing has changed in the twitch plugin so why not go directly to KODI and
ask there?
It's 100% not related to the plugin :)

**Comment by Queuecumber** [comment]
@ingwinlu Thanks this is a fantastic direction to continue debugging. I'll try this later on today and post my findings. 

@pipinije Can you confirm that we are on the same version of Kodi?

**Comment by pipinije** [comment]
I'm on last stable openelec based on 14.2 helix kodi (installed on intel nuc). On other "stations" (pc through browser, android) i have no problem playing twitch, also just installed raspbian on raspbery pi i had lying around and it's working without a glitch with livestreamer+omxplayer so probably culprit is on twitch side in combination with kodi.

**Comment by Queuecumber** [comment]
@pipinije The thing is that the twitch web player is flawless, and preliminary testing with VLC seems like it is also working fine, all at highest possible quality. 

So the machine that is causing you problems is using Kodi 14.2 correct? (you can verify this in the settings menu under system information)

**Comment by pipinije** [comment]
@Queuecumber Yes, kodi 14.2 (openelec 5.0.8).

**Comment by Queuecumber** [comment]
@pipinije Then we may not be able to narrow this down to a specific kodi release, strange. Would you mind installing 15.2-RC1 on another computer, preferably one that you have verified the streaming works fine in, to see if you can reproduce with the same version I have?

**Comment by Queuecumber** [comment]
So I spent some time testing the streams in different players. My procedure was the make twitch API calls from my browser to get at the stream playlist and copy the stream URLs for the "source" quality stream into different players. I tested with mplayer, totem, vlc, kodi, and the twitch web player. All I can say is that the results are very inconsistent. 

Totem and the twitch web player seemed to perform the best, I had no buffering with either. vlc buffered rarely. Kodi had similar buffering issues to what I described when I opened the issue. Mplayer was a huge failure, it buffered after only a few seconds and never recovered.

While these tests were running I watched my network received usage in the system monitor. I can see that for each group of players I mentioned above, the received bps was lower each time. The more time I spend with this issue the weirder it gets.

**Comment by pipinije** [comment]
I installed kodi 15.1 on my windows 8.1 machine, and it's a bit better as it's not freezing for a longer time or disconnecting but it's stuttery/freezy.

**Comment by Queuecumber** [comment]
I also tried upgrading to kodi 16 alpha with no success. I'll keep thinking about different ways to get to the bottom of this but I'm running out of ideas.

**Comment by Queuecumber** [comment]
OK guys I'm out of ideas, I've posted to the Kodi forums, hopefully someone there can help

http://forum.kodi.tv/showthread.php?tid=239693

**Comment by pipinije** [comment]
I think problem is on twitch side, because i see quite a few of "buffering problems" topics on reddit (https://www.reddit.com/r/twitch) and as kodi is probably most unreliable player for it the problem is more pronounced because i also see stream problems even on web player. Most reliable for me was livestreamer with vlc. So until twitch fixes things...

**Comment by Queuecumber** [comment]
I'm starting to think the same thing

**Comment by henriklb** [comment]
I've had issues with openelec + this addon for about two weeks now, am I alone?

**Comment by blddk** [comment]
I just tested this on my Raspberry Pi 3, and even over the build-in wifi it runs fine. However, I see a lot of the comments was from late last year, I had a lot of trouble with twitch back then, both through Kodi and watching it in a browser from their site, so that was a server problem at their end for me.
