### ISSUE TITLE
Error to open a stream on Android Frodo 12.0 

### ISSUE THREAD

**Issue by spavezv** [anxdpanic/plugin.video.twitch#14]
I have installed the version Frodo 12.0 stable for android and installed the latest version of the plugin for twitch 0.2.2 and I get this error on log files:

12:34:35 T:1762128128  NOTICE: Creating InputStream
12:34:35 T:1762128128   DEBUG: SECTION:LoadDLL(librtmp.so)
12:34:35 T:1762128128   DEBUG: Loading: /data/app-lib/org.xbmc.xbmc-2/librtmp.so
12:34:35 T:1762128128   ERROR: Unable to load /data/app-lib/org.xbmc.xbmc-2/librtmp.so, reason: (null)
12:34:35 T:1827366248    INFO: Python script stopped

**Comment by StateOfTheArt89** [comment]
It seems the library for rtmp is missing. Rtmp is the protocol which is used to stream the video data from twitch. This library is usually shipped with xbmc and is not a part of my addon.

Edit: I'm going to take a look on this anyway. Maybe there is an easy fix for this issue.

**Comment by spavezv** [comment]
Hey, I have reinstalled xbmc, since I have first updated it from a rc version. Now it shows me a differenet error. I tried to change the librtmp, in the page that you link says that in android its located on:
/data/data/org.xbmc.xbmc/lib/librtmp.so 
but in the log file says that it will open one in the this folder:
19:00:29 T:1743899976   DEBUG: Loading: /data/app-lib/org.xbmc.xbmc-1/librtmp.so
19:00:29 T:1743899976    INFO: : Using external libRTMP
19:00:29 T:1743899976    INFO: Parsing...
19:00:29 T:1743899976    INFO: Parsed protocol: 0
19:00:29 T:1743899976    INFO: Parsed host    : justintvlivefs.fplive.net
19:00:29 T:1743899976    INFO: Parsed app     : justintv4live-live
19:00:29 T:1743899976   ERROR: Unknown option jtv

Even updating this one,  the other or both, it still show that error.

**Comment by StateOfTheArt89** [comment]
"Unknown option jtv" is a strong indicator, that your librtmp is too old / doesn't support the current rtmp. The jtv option was added to librmtp to support justin.tv (and now twitch.tv).

"jtv=JSON
JSON token used by legacy Justin.tv servers. Invokes NetStream.Authenticate.UsherToken" (source: http://rtmpdump.mplayerhq.hu/librtmp.3.html)

**Comment by spavezv** [comment]
How can I get an updated version of it. I have downloaded this one:
https://dl.dropbox.com/u/477050/librtmp.so.0
From:
http://wiki.xbmc.org/index.php?title=HOW-TO:Update_librtmp

but it says that its for xbmc 11.0 eden

I don't know how to compile a new version to android device because I just have windows. My tablet its rooted and tried to do it on the terminal, but I need to install gcc compiler, there is some on the play store, but I don't a medium to pay for one.
