### ISSUE TITLE
vods & subscribtions

### ISSUE THREAD

**Issue by vidje** [anxdpanic/plugin.video.twitch#144]
Is there any way to watch/browse vods (past broadcasts) via this plugin?

also, when user auth gets done it'd be nice if we could follow the channels on twitch instead of sending them to kodi favorites :)

**Comment by Giacom** [comment]
You can watch past broadcasts by..
1. Go to the following listings.
2. Scroll down until you reach a channel with a past broadcast you want to watch.
3. It should give you an option for past broadcasts or highlights.
4. Choose a VOD to watch.

Some channels are able to disable watching VODs unless you are subscriber, which would not allow you to watch with this plugin as there is no authentication.

**Comment by vidje** [comment]
@Giacom thanks a lot, btw can I somehow watch past broadcasts of channels I am not following?

**Comment by Giacom** [comment]
I don't think there's a way to do that, I only know the following method.

**Comment by vidje** [comment]
still, thanks a lot, this helped as well!
