### ISSUE TITLE
Lag only with certain streams - any suggestions

### ISSUE THREAD

**Issue by domvo** [anxdpanic/plugin.video.twitch#145]
So, first of all: I know, this plugin does not handle the playback. But I have a very interesting issue with my playback, maybe you can shed some light here anyways.

I am using Kodi 16 RC on an Amazon Fire TV Stick. I use your Addon with it a lot! Most of the streams play back very very well. No buffering, no stuttering, just smooth 1080p playback, audio and video always perfectly synchronized.

But there are a few Streams (maybe 1 out of 8) that have great issues being played back in highest quality. They stutter a lot (feels like 5-10 fps), audio and video sometimes not synced. They can only be played back in 720p, which is not looking too great on my big TV.

So do you guys know anything about issues with different codecs? Or maybe they use other software to stream their content? I've also tried watching the streams on my PC with the livestreamer command line tool and VLC. No issues here. ANY help would be appreciated. A workaround from your side might be to implement a sort of blacklist, where we can define 720p as maximum quality for some streams or so.

**Comment by Blayr** [comment]
I have encountered this as well. Can confirm on the following streams:
- AnnieBot
- GoodGuyGarry

I have discovered that changing the add-on setting stream quality to 720p  (as opposed to best possible quality) fixes these issues.

**Comment by domvo** [comment]
I'm pretty sure as of now that this is the case with Full HD 60fps streams! 30fps is no problem. Easiest way to find out some meta data on the stream is this website: https://r-1.ch/analyzer/ . My guess is that the Fire TV Stick is not fast enough for 60fps. A friend of mine says he has no problem with Kodi 16 RC on an RPi2 and that plugin!

**Comment by h0us3cat** [comment]
This has nothing to do with fps.
I have this issue on any random stream, does not matter what bitrate they/me use or how much fps it is both 30/60 have this issue.
One time the stream works perfect the other time the buffer drops to 0% and then it keeps at 0%.
Tried kodi 15.x up to 17.x
My specs are i3 4160, asus z97 motherboard with 4GB DDR3 ram and windows 10 x64.
My connection is wired up to 200Mbit download.
I hope this can be solved.

**Comment by domvo** [comment]
I know for a fact that my problem only occurs with 1080p60 streams (60fps). I haven't encountered this problem with any 30fps stream ever.

**Comment by h0us3cat** [comment]
I found out sometimes i view from a us server with lag/buffering and sometimes i watch from a eu server with no lag/buffering. I gues this is twitch fault?

**Comment by h0us3cat** [comment]
So any idea why the us/san fransisco server has buffering issues in kodi? While the same stream/url works fine outside of kodi?
