### ISSUE TITLE
Suggestion: Followed Games?

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#146]
Hi,

First off - thank you VERY much for your work on this. I've loved my migration to Kodi and now that I can watch with there, there is very little I need to do outside of Kodi for entertainment.

There was a new feature introduced to twitch a while ago now, followed games. Much like followed users, followed games allows you to, well, follow a game and quickly access whoever is playing it. Would it be possible (or is there interest) in implementing this in addition to the followed user functionality?

I've not looked at the API so I don't know if the followed game functionality requires authentication or not (I presume not as you're table to pull my following list without authentication).

**Comment by MrSprigster** [comment]
This feature already exists :)... Just below Following on the main menu.

**Comment by MrSprigster** [comment]
Actually, this feature may not yet be included in the latest release on the
Kodi repo but it's definitely present in the current development release
which is available to download right here.

**Comment by cmsimike** [comment]
Excellent! Thank you very much for the continued additions to the plugin.

I will close this
