### ISSUE TITLE
Stream thumbnails do not update (Fix Here)

### ISSUE THREAD

**Issue by Blayr** [anxdpanic/plugin.video.twitch#147]
As mentioned in my title, stream thumbnails once loaded do not change. This is because Kodi is caching the image, and when it sees the URL again it just references the cache as opposed to the updated thumbnail.

Apparently directly accessing the cache is against add-on rules, so I added a random queryString value to the end of the image URL. 

Within `converter.py` : 

Add uuid import:

`import xbmcgui, xbmc, uuid`

Within the `convertStreamToListItem` function change the following lines: 

`if preview:
            preview = preview.get(Keys.MEDIUM, '')`

to

`if preview:
            preview = preview.get(Keys.MEDIUM, '') + "?uuid=" + str(uuid.uuid4());`

**Comment by disrupted** [comment]
@Blayr Can you open a pull request for this?

**Comment by Blayr** [comment]
@freeman212 This is my first (ever) pull request, but done.

**Comment by disrupted** [comment]
@Blayr there's always a first time. good job ! :+1: 
edit: umm actually I can't find your PR. are you sure about sending it?
