### ISSUE TITLE
Can't use or install the plugin

### ISSUE THREAD

**Issue by peterlandry** [anxdpanic/plugin.video.twitch#15]
Using OpenELEC 3.0.0, the plugin shows a blank entry in the add-ons list, and if I try to install, triggers a reboot.

This is on a RasPi. It previously worked fine -- not sure what caused it to break.

**Comment by miksven** [comment]
It complains about the plugins structure

**Comment by ccaspers** [comment]
Any updates on the situation? If the problem still exists, can you provide a log?

**Comment by ccaspers** [comment]
closed due to lack of information

**Comment by peterlandry** [comment]
Sorry to drop off the radar -- It's indeed fixed. Thanks!

**Comment by ccaspers** [comment]
great :)
