### ISSUE TITLE
Plugin failed working on Kodi Krypton with HTTP Error

### ISSUE THREAD

**Issue by elchupete** [anxdpanic/plugin.video.twitch#154]
Twitch throws http Error on Krypton

20:59:04 T:140735177162752   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:59:04 T:140735177162752   DEBUG: Window DialogBusy.xml was already loaded
20:59:04 T:140735177162752   DEBUG: Alloc resources: 0.00ms
20:59:04 T:123145303990272   DEBUG: [plugin.video.twitch] Error URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),) during HTTP Request, retrying
20:59:04 T:140735177162752   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/players/VideoPlayer/libdvdnav-x86-osx.so)
20:59:04 T:123145303990272   DEBUG: [plugin.video.twitch] Error URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),) during HTTP Request, retrying
20:59:05 T:123145325506560   DEBUG: Previous line repeats 2 times.
20:59:05 T:123145325506560   DEBUG: WaitOnScriptResult- plugin returned failure
20:59:05 T:123145303990272    INFO: CPythonInvoker(20, /Users/stefan/Library/Application Support/Kodi/addons/Twitch.tv-on-XBMC-master/resources/lib/__run__.py): script aborted
20:59:05 T:140735177162752   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/createListOfTeams/0/
20:59:05 T:140735177162752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/createListOfTeams/0/) failed
20:59:05 T:140735177162752   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.twitch/)
20:59:05 T:140735177162752   DEBUG:   ParentPath = [plugin://]
20:59:05 T:140735177162752   DEBUG: Loading items: 8, directory: plugin://plugin.video.twitch/ sort method: 0, ascending: false
20:59:05 T:123145316945920   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.twitch] took 1 ms
20:59:05 T:123145304526848   DEBUG: Thread BackgroundLoader start, auto delete: false
20:59:05 T:123145303990272    INFO: Python script stopped
20:59:05 T:123145303990272   DEBUG: Thread LanguageInvoker 123145303990272 terminating
20:59:05 T:140735177162752   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
20:59:05 T:123145304526848   DEBUG: Thread BackgroundLoader 123145304526848 terminating

**Comment by anxdpanic** [comment]
@elchupete If you're able, please give this a test and post if it resolves the issue for you

https://github.com/anxdpanic/Twitch.tv-on-XBMC/archive/patch-1.zip

**Comment by elchupete** [comment]
Thanks @anxdpanic , your version works for me

Stefan

**Comment by MrSprigster** [comment]
Feel free to issue a pull request for this fix.

**Comment by anxdpanic** [comment]
:+1:

**Comment by elchupete** [comment]
Has been merged 25 Minutes ago.

-> closed
