### ISSUE TITLE
Http Error

### ISSUE THREAD

**Issue by pdefreitas** [anxdpanic/plugin.video.twitch#166]
At this morning this was working. At this moment it is giving me a http error message.

Version: 1.4.0

**Comment by derTobsch** [comment]
Sane for me with latest osmc and twitch addon version 1.4.0

Log says

<pre>
16:35:28 366.564850 T:1515189232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /playLive/rocketbeanstv/
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/__run__.py", line 7, in <module>
                                                sys.exit(PLUGIN.run())
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /playLive/rocketbeanstv/
                                            -->End of Python script error report<--
16:35:28 366.733337 T:1956729776   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/playLive/rocketbeanstv/
</pre>

It does work with version 1.3.1

**Comment by anxdpanic** [comment]
@derTobsch this looks like you may be loading through an old favorite created with 1.3.1, the plugin:// url has had a change in 1.4.0+

New: plugin://plugin.video.twitch/playLive/rocketbeanstv/-2/
Old: plugin://plugin.video.twitch/playLive/rocketbeanstv/ (seen in the log clip)

If it's a favorite, try just deleting and re-adding that favorite

**Comment by derTobsch** [comment]
@anxdpanic Thanks! that worked for me. Just re-added the favourite.

**Comment by foss-** [comment]
seeing http error for every action using Twitch Add-on 1.4.0 from Kodi repo in Kodi 17a2. Is there a fix coming to the kodi repo?

**Comment by MrSprigster** [comment]
Yes.

**Comment by foss-** [comment]
working with 1.4.1 installed via zip. close this issue?
