### ISSUE TITLE
Using JSON endpoint, adding Twitch videos (not live streams) to playlist and playing it fails. Opening a video directly works though.

### ISSUE THREAD

**Issue by khloke** [anxdpanic/plugin.video.twitch#167]
Basically if I did this:

`[{"jsonrpc": "2.0", "method": "Playlist.Clear", "params":{"playlistid":1}, "id": 1},
{"jsonrpc": "2.0", "method": "Playlist.Add", "params":{"playlistid":1, "item" :{ "file" : "plugin://plugin.video.twitch/playVideo/v67845766/-2/" }}, "id" :1},
{"jsonrpc": "2.0", "method": "Player.Open", "params":{"item":{"playlistid":1, "position" : 0}}, "id": 1}]`

It fails to play.

But this works:

`[{"jsonrpc": "2.0", "method": "Player.Open", "params":{"item" :{ "file" : "plugin://plugin.video.twitch/playVideo/v67845766/-2/" }}, "id": 1}]`

Attached here is the log file: [kodi.txt](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/files/288138/kodi.txt)

Line 537-539 and 619 are just additional info from my attempt to debug it.

Live streams are fine.

**Comment by anxdpanic** [comment]
@khloke if possible can you test hxxps://github.com/anxdpanic/Twitch.tv-on-XBMC/releases/download/json-playback-fix-test/plugin.video.twitch.json.playback.fix.test.zip

see commit 9a2c4e4

I believe that should resolve it. I've tested against other playback without issues

Edit: remove live link, zip removed.

**Comment by khloke** [comment]
@anxdpanic the fix works great. Great job!

**Comment by anxdpanic** [comment]
Good to hear!

PR #168
