### ISSUE TITLE
Plugin throws UnicodeEncodeError when trying to load channel with non-ASCII name

### ISSUE THREAD

**Issue by spidloun** [anxdpanic/plugin.video.twitch#171]
When I am trying to load favourite channels list from the main plugin menu, plugin crashes with UnicodeEncodeError. This happens only if one of the expected channels has non-ASCII characters in name (Czech characters in my case). Channels list loads OK if there are only ASCII chars.

Problem is at line 221 in file /resources/lib/converter.py

I made a patch as a workaround for my OSMC (Kodi) installation.

[converter.patch.txt](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/files/326596/converter.patch.txt)

**Comment by torstehu** [comment]
@spidloun can you test if this commit fixed the issue for you?
