### ISSUE TITLE
Past broadcasts / highlights broken

### ISSUE THREAD

**Issue by tofof** [anxdpanic/plugin.video.twitch#174]
Upon installing 1.4.1 from the Kodi Repo, attempting to play a past broadcast or highlight only produces "Http error" on multiple independent installs.  Reverting to version 1.4.0 corrects this problem.

Log:
00:37:27 T:8064   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/v75261763/-2/]
00:38:32 T:8064   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/v14292806/-2/]

Attempting to play the same broadcasts via the 'select video by id or url' option produces the same error. Used a URL from web browser, pasted in: https://www.twitch.tv/brownman/v/76419262

Log: 
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/v76419262/-2/]

**Comment by nDmitry** [comment]
Had that problem too. I created new application in Twitch settings/connection and entered my client ID and secret (oauth token) in add-on settings. It worked.

**Comment by WallyCZ** [comment]
+1

**Comment by MrSprigster** [comment]
fixed in 1.4.2
