### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by slideup-benni** [anxdpanic/plugin.video.twitch#175]
Hello,

Version 1.4.1 is broken on OpenElec with Kodi Jarvis on the Raspberry Pi B.
When i want to play a video from past broadcast, i will get a HTTP Error.

I don't know if version 1.4.2 fixed the problem. It is not availible in the kodi repo.
After the downgrade to 1.4.0 it works.

Benni

**Comment by MrSprigster** [comment]
To manually fix 1.4.1, goto settings and then the API tab (last tab). Make
a note of the oauth client I'd  in there and type it in the oauth token
field in the general tab.

Ill submit the fix to the official Repo asap.

**Comment by slideup-benni** [comment]
Thank you for your very fast answer.

Yes, this fixed the problem :) Thank you very much

**Comment by toffelwurst** [comment]
Thank you for the Hotfix it totally solved the problem for me too.
Any idea when 1.4.2 is available in the Kodi repo?

**Comment by MrSprigster** [comment]
https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/releases/tag/1.4.3
