### ISSUE TITLE
"Dependencies not met" /AppleTV 2 / Kodi 14.2 HELIX

### ISSUE THREAD

**Issue by richiegigabit** [anxdpanic/plugin.video.twitch#178]
[log.txt](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/files/391676/log.txt)

Every time I try to install the addon I get a "Dependencies not met. Please contact author." error. Running Kodi 14.2 Helix. I previously had this addon installed but I ran a Fresh Start to reconfigure my ATV2. When I went to install the addon it was no longer listed in the Kodi repo where I originally found it. Found you and ccaspers were the main authors and would love to get this working again.

**Comment by MrSprigster** [comment]
Update your Kodi

**Comment by richiegigabit** [comment]
I am running Kodi on an ATV2 and there isn't a build that goes past Helix.

**Comment by richiegigabit** [comment]
**FIX FOUND:**
After much investigation, I got the addon to install using version 1.3.1 of the Twitch plugin. To anyone using an AppleTV 2 that receives the "Dependencies not met" message, the previous version installs flawlessly. The zip file can be downloaded here. >>> http://bit.ly/2a7NT1D

Thank you Mr. Sprigster and anyone else involved in the development of this plugin.

Regards,

\RXM
