### ISSUE TITLE
Valve's The International 2016 streams (1080p60) not working

### ISSUE THREAD

**Issue by deebo** [anxdpanic/plugin.video.twitch#179]
Twitch is allowing Valve to do 1080p60 broadcasting on at least the english channels dota2ti, dota2ti_2 etc, but these do not work in kodi using "best possible" quality.

Any other channel works fine.

see https://blog.twitch.tv/the-international-on-twitch-705404e95cc2#.dc7xmzjm2

**Comment by Line40** [comment]
Just a a quick fix: In file 

"plugin.video.twitch/resources/lib/twitch/constants.py"

 replace the line 
    QUALITY_LIST_STREAM = ['Source', 'High', 'Medium', 'Low', 'Mobile']
with
    QUALITY_LIST_STREAM = ['Source', '720p60', '720p30', '540p30', '480p30', '360p30', '240p30', '144p30', 'High', 'Medium', 'Low', 'Mobile']

After that, make sure to select "Best quality" in the plugin settings, that worked for me. Other qualities may not work, or have a different resolution than the one selected in settings. Sorry for that, but I could not make heads or tails from the code that does the quality mapping, just made it work somehow :smile:

**Comment by Imnotgoodathis** [comment]
Explains why I couldn't get it to work.

Wonder if I can edit that file on my raspberry PI.

Well rpi1 aint strong enough for 1080p60fps, but 720p is working fine with this fix. 
Thank you (Line40) very much, saved my dota2 party this weekend =D

**Comment by YellowOnion** [comment]
Thanks for the fix, was easy enough for me.

**Comment by MrSprigster** [comment]
ThIs fix is included in the current release.

**Comment by ghost** [comment]
I'm running into this issue aswell, i already changed the QUALITY_LIST_STREAM line but it didnt change anything for me. 
I double checked the file and folder but is it normal that it still shows the standard quality settings and not the fps ones?
I'm running Kodi 16.1 and Twitch 14.1.

Edit: I found a reddit thread where someone added 1080p to the options: 

> QUALITY_LIST_STREAM = ['Source', '1080p60', '1080p30', '720p60','720p30','540p30','480p30','360p30','240p30','144p30']
> QUALITY_LIST_VIDEO = ['live', '1080p60', '1080p30', '720p60','720p30','540p30','480p30','360p30','240p30','144p30']

That works now!
