### ISSUE TITLE
Playback failed ubuntu 

### ISSUE THREAD

**Issue by Riftcore** [anxdpanic/plugin.video.twitch#18]
Howdy I used this epic app all the time when I was back on xbmcbuntu but am on ubuntu server and I can't seem to get this to play the streams.

Here is part of the log file
http://pastebin.com/MZEcuhw5
(Hope it's the right part)

Hope you can shine some light on this for me I am so lost without it :)

Cheers

**Comment by ccaspers** [comment]
Did you try manually update librtmp? I was on Ubuntu 12.04 and had to replace it. 

See http://wiki.xbmc.org/index.php?title=HOW-TO:Update_librtmp to get instructions.

**Comment by Riftcore** [comment]
Yes but there is only the xbmc v11 on there. I am on frodo.

**Comment by Riftcore** [comment]
Now xbmc won't even boot >.>

http://pastebin.com/JVsjvLvx

**Comment by Riftcore** [comment]
All fxied it was indeed needing the update cheers
