### ISSUE TITLE
Release 1.43 in a timely fashion

### ISSUE THREAD

**Issue by lucabric** [anxdpanic/plugin.video.twitch#182]
As Ti6 is currently underway, is there any way to push adba68bd2dcdfba88f78d164e5b14c34d5e2c008 to the official Kodi repository any time soon?
It is quite easy to apply manually for Linux/Windows users, but not for Android/iOS users.
Might need a version bump to 1.43.

**Comment by MrSprigster** [comment]
Will do ASAP

**Comment by lucabric** [comment]
Wonderful, thanks!

**Comment by nogweii** [comment]
Unfortunately, TI6 is over and the add-on wasn't updated in the repo (assuming http://addons.kodi.tv/show/plugin.video.twitch/ is correct). However the changes included since 1.4.1 are still important. More streams have 60fps streams which breaks the current version in the repo.

**Comment by pepotr** [comment]
New version needed, as old versions no longer work, returning errors.

**Comment by MrSprigster** [comment]
https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/releases/tag/1.4.3
