### ISSUE TITLE
Not working after introducing 60fps streams

### ISSUE THREAD

**Issue by Flixi555** [anxdpanic/plugin.video.twitch#183]
After the recent change to constants.py to accommodate for the new 60fps streams, I was unable to load 'normal' streams. 

Reversing to

```
QUALITY_LIST_STREAM = ['Source', '720p60', '720p30', '540p30', '480p30', '360p30', '240p30', '144p30', 'High', 'Medium', 'Low', 'Mobile']
QUALITY_LIST_VIDEO = ['live', '720p', '480p', '360p', '226p']
```

fixed it for me.

**Comment by nogweii** [comment]
I think this is fixed now with https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/commit/6e44a0e9cbb384805496c4ab3cd8000fdecf75ce

**Comment by MrSprigster** [comment]
Fixed in https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/190
