### ISSUE TITLE
Stream is not starting

### ISSUE THREAD

**Issue by postpapa** [anxdpanic/plugin.video.twitch#188]
i everytime get "twitch error" if i hit "abbonements" or choose a stream.
here is the log file:

http://pastebin.com/AtVNMMjz

and here the hole kodi.log:

http://pastebin.com/BNwXcBUi

**Comment by anxdpanic** [comment]
Twitch just added closed captioning to their playlists, which has caused all streams to not play. I believe I have it fixed, just testing a few things now as well as this.

https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/blob/master/resources/lib/twitch/utils.py#L100
to
`if line.startswith('#EXT-X-MEDIA:TYPE=VIDEO'):`

**Comment by postpapa** [comment]
Ty for your fast Response, gonna try it tomorrow :)

**Comment by prometheanfire** [comment]
I can confirm that this fix works (tried on master)

**Comment by DJClean** [comment]
Just hacked it into mine after messing with it (cause I thought it was the oauth thing) and streams are working again

**Comment by Morgyn** [comment]
Hacked it into mine as well, confirmed here.

TY!

**Comment by henriklb** [comment]
line change in code works! ty

**Comment by finuh** [comment]
Hi guys.. i'm a newbie on twitch and XBMC. Could you gently teach me how to change this code? (like path or file to be changed?)
Thank you!

**Comment by nrk666** [comment]
anxdpanic fix above works, thanks mate

**Comment by anxdpanic** [comment]
👍 Thanks for confirming

**Comment by rd1** [comment]
nope, doesn't work

i edited "C:\Users<username>\AppData\Roaming\kodi\addons\plugin.video.twitch\resources\lib\twitch\utils.py"

now kodi won't even start the twitch addon. says twitch error. what fresh hell is this.

**Comment by andrewell** [comment]
Hey guys, is there a way to do this on the Fire TV stick or do I need to wait for the Twitch addon to be updated? Currently running on TwitchTV 1.4.1.

**Comment by postpapa** [comment]
doesnt work for me, too.

http://pastebin.com/aneAA98e

looks like same urllib3 error 

EDIT: NVM works now, dont know why

**Comment by SonOfSunTzu** [comment]
I'm seeing the same problem with 1.4.3. Error log is at:

http://pastebin.com/nqD3MrTn

Version 2.9.1 ( latest available ) of "requests" is installed... I'm a little stuck on this, suggestions welcome, happy to carry out diagnostics.

**Comment by rd1** [comment]
kodi finaly updated addon to 1.4.3 and it works!

thank you !
