### ISSUE TITLE
update releases and kodi repository with v1.4.2 please

### ISSUE THREAD

**Issue by rd1** [anxdpanic/plugin.video.twitch#189]
title says it all

we're stuck at 1.4.1 and it doesn't work on twitch anymore. kodi doesn't find an update and there is nothing in releases here on git past 1.4.0

update everywhere please

**Comment by pepotr** [comment]
Yes, please update twitch app on Kodi repository. It no longer works.

**Comment by nrk666** [comment]
I'll third this I guess, please update releases to 1.4.2 so it propagates out to repos.

**Comment by MrSprigster** [comment]
Updated to 1.4.3 on Official Repository (awaiting pull accept by the Kodi Addons Team)

**Comment by nrk666** [comment]
Thanks!

**Comment by rd1** [comment]
thank you !
