### ISSUE TITLE
Error when opening a stream that does not support the desired resolution

### ISSUE THREAD

**Issue by Wooza** [anxdpanic/plugin.video.twitch#19]
Here is the stacktrace from the xbmc log.
I've never worked with python, therefore i can't try to fix it on my own :(

21:09:14 T:2862441536  NOTICE: -->Python Interpreter Initialized<--
21:09:27 T:2862441536  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
21:09:27 T:2887607360  NOTICE: Thread Background Loader start, auto delete: false
21:09:29 T:2887607360  NOTICE: Thread XBPyThread start, auto delete: false
21:09:30 T:2887607360  NOTICE: -->Python Interpreter Initialized<--
21:09:33 T:2887607360  NOTICE: [xbmcswift2] Request for "/createListOfGames/0/" matches rule for function "createListOfGames"
21:09:36 T:2862441536  NOTICE: Thread Background Loader start, auto delete: false
21:09:52 T:2862441536  NOTICE: Thread XBPyThread start, auto delete: false
21:09:52 T:2862441536  NOTICE: -->Python Interpreter Initialized<--
21:09:54 T:2862441536  NOTICE: [xbmcswift2] Request for "/createListForGame/StarCraft+II%3A+Heart+of+the+Swarm/0/" matches rule for function "createListForGame"
21:09:57 T:2887607360  NOTICE: Thread Background Loader start, auto delete: false
21:10:20 T:2887607360  NOTICE: Thread XBPyThread start, auto delete: false
21:10:20 T:2887607360  NOTICE: -->Python Interpreter Initialized<--
21:10:22 T:2887607360  NOTICE: [xbmcswift2] Request for "/playLive/totalbiscuit/" matches rule for function "playLive"
21:10:27 T:2887607360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('video_height',)
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 324, in <module>
                                                plugin.run()
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 309, in playLive
                                                jtvtoken = getBestJtvTokenPossible(name)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 272, in getBestJtvTokenPossible
                                                videoHeight = int(x['video_height'])
                                            KeyError: ('video_height',)
                                            -->End of Python script error report<--
21:10:28 T:3037560832   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/totalbiscuit/]

Hope you can find a solution

**Comment by Wooza** [comment]
Seems to be fixed with version 1.0.0

**Comment by ccaspers** [comment]
Thanks :)
