### ISSUE TITLE
No streams opening

### ISSUE THREAD

**Issue by NoclueMac** [anxdpanic/plugin.video.twitch#191]
Hi,

Latest master files, no streams are viewable with demuxer errors in the log. Pastebin logs below:

http://pastebin.com/CKCBvuGJ

Many thanks

**Comment by anxdpanic** [comment]
I just tested dreamhackcs and pgl_hs here and they are working fine as do all other I tested. Not sure what the cause may be

**Comment by anxdpanic** [comment]
A couple others have reported this on the forum as well now. I've tested 15.2-17alpha&beta and cannot replicate the issue still. 

http://forum.kodi.tv/showthread.php?tid=134538&pid=2416970#pid2416970 to see more info. 

So far the only hint or suspect I can see is ffmpeg version related, but not able to confirm anything yet

**Comment by MrSprigster** [comment]
Worth monitoring.

**Comment by Winjet** [comment]
I installed version 1.4.3 but I still get the same error messages :
http://pastebin.com/L6Wwc1LE

In addition, I have the following error (Unverified HTTPS request) :
http://pastebin.com/0AAsW4Sd

RaspberryPI 3 Model B with Recalbox OS (version : 4.0.0-beta5) and Kodi 15.2

Thanks

**Comment by lwis** [comment]
Could this have been broken by 8317cbd145c6c72cef0666dd38e603dc9f9909be?

**Comment by SonOfSunTzu** [comment]
I'm seeing the same problem with 1.4.3. Error log is at:

http://pastebin.com/nqD3MrTn

Version 2.9.1 ( latest available ) of "requests" is installed... I'm a little stuck on this, suggestions welcome, happy to carry out diagnostics.

I'm on a RaspberryPI 2 B using Xbian.

**Comment by Tele42** [comment]
Hi folks, I was experiencing this issue on Gentoo. I have restored functionality by rebuilding ffmpeg 2.8.6 with openssl support (previously disabled and unneeded).

**Comment by NoclueMac** [comment]
Hi,

Unfortunately I'm using an Asustor NAS with a fairly locked down Linux OS on it so the suggestions made both here and in the forum are outside of my access levels.

I have raised a ticket with them asking about the possibility of enabling OpenSSL support for their own version of the FFMPEG library.

I'll report back if I hear anything from them.

Thanks to everyone for their input so far.

**Comment by MrSprigster** [comment]
Please feel free to test 1.4.4 and provide feedback 👍  https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/releases/tag/1.4.4

**Comment by NoclueMac** [comment]
Evening,

I tested 1.4.4 and while the first stream opened successfully all subsequent streams failed, including retrying the first stream once more.

Pastebin below:

http://pastebin.com/aikuh034

**Comment by MrSprigster** [comment]
That log entry suggests an FFMPEG error. I'm not sure why it would work only once and not subsequently :/. Does it work after a reboot? Only once?

Are you able to update your Kodi to a newer version?

**Comment by Tele42** [comment]
For what it's worth, a single random working stream here and there is consistent with my testing pre-rebuild of ffmpeg. I did not profile this.

**Comment by nymphie** [comment]
Enabling openssl for ffmpeg fixed it for me on gentoo.

**Comment by NoclueMac** [comment]
The makers of my NAS (Asustor) have confirmed they can reproduce the issue and are looking into it.

I'll update when I hear more from them.

**Comment by MrSprigster** [comment]
Nice! please do update us.

**Comment by vhda** [comment]
Are there any workarounds available, in the meanwhile? 
Twitch streams started requiring some form of SSL, or is this something that this addon started to enable by default?

**Comment by MrSprigster** [comment]
Twitch streams are now transported through SSL. 

Unfortunately guys this is a playback issue and falls outside the scope of the add-on. 

The add-on is doing its job perfectly as you are successfully requesting a stream and being presented with the correct data, and then Kodi takes over and fails to play it (likely due to your platforms having FFMPEG which has been built without ssl).

Your best bet is rebuilding FFMPEG with ssl support. The following may or may not work for your platform but google should help you find the correct method on your specific Linux distro.

./configure --enable-gnutls

sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update

cd
apt-get source ffmpeg
sudo apt-get build-dep ffmpeg

cd ffmpeg-2.8.6
./configure --enable-gnutls
dpkg-buildpackage -rfakeroot -uc -b

**Comment by lwis** [comment]
@MrSprigster crap, so does this mean that Android is dead in the water?

**Comment by MrSprigster** [comment]
I haven't seen reports of this problem with android..  are you having issues on android?

**Comment by MrSprigster** [comment]
I just installed Kodi 16 Jarvis on my phone running Android M with add-on ver 1.4.4 and all seems well. 

This issue appears to be a Linux specific problem affecting only a few specific distributions.

**Comment by lwis** [comment]
@MrSprigster ignore me, looks like my config was borked. Sorry!

**Comment by MrSprigster** [comment]
Ha. Good news! No worries.

**Comment by MrSprigster** [comment]
Based on results of testing ([here](http://forum.kodi.tv/showthread.php?tid=134538&pid=2423084#pid2423084)), the only way to fix this problem is to update to Kodi 15+ or use FFMPEG built with SSL (along with all dependencies) with Kodi 14 or lower.

This is not an issue within the scope of this add-on.

**Comment by vhda** [comment]
I just noticed that there is a `libffmpeg-full` package in entware. Do you know of a way of using these libs for this addon? Maybe through some kind of `LD_LIBRARY_PATH` setting?
