### ISSUE TITLE
VoDs are giving http errors

### ISSUE THREAD

**Issue by oczr** [anxdpanic/plugin.video.twitch#192]
Good evening!

I was about to watch an older VoD nut as soon as I start it I get an http error. I am using Kodi 16.1 on a Fire TV Stick with Version 1.41 from the Kodi repo.

It seems like that every VoD does not start. Is it somehow related to last night when pretty much everything stopped working?

Does anyone else have problems playing old VoDs (e.g. 38287043) and or newer ones?

If any data is needed please let me know.

Hugs and kisses,
oczr

**Comment by anxdpanic** [comment]
Version 1.4.1 no longer working. For vods you'll also need to visit http://www.twitchapps.com/tmi/ and enter the oauth token in the add-on settings

**Comment by oczr** [comment]
That's strange. Everything was working just fine till the problems came up two days ago.

Anyways ...
Thank for your answer.

Guess I'll have to wait for an update being released in the Kodi Repo.

**Comment by MrSprigster** [comment]
1.4.3 is now live on the Official Repo. Let us know how you get on.
