### ISSUE TITLE
Changes requested by Kodi Addons Team

### ISSUE THREAD

**Issue by MrSprigster** [anxdpanic/plugin.video.twitch#193]
In our previous Kodi Addons Repository update, the Kodi team requested some changes be made to this addon which I unfortunately do not have time to sit and correct due to RL commitments, details of which can be found in the comments of the previous pull request here: https://github.com/xbmc/repo-plugins/pull/581 and are also listed at the bottom of this post.

I have submitted 1.4.3 without these requested changes as the 1.4.1 version on the repository now seems to be broken and is causing users who reside on systems which are difficult to manually update (from the git) to lose functionality .

If anyone has the time to go through and make the requested changes, it would be greatly appreciated.

**Requested changes:**

```
plugin.video.twitch/addon.xml
  "would be good if you could add forum tag entry in your next update"

plugin.video.twitch/resources/language/%language%/strings.xml
  "Please change to strings.po for your next update, strings.xml is now deprecated."

plugin.video.twitch/resources/lib/converter.py
  "the thumbnailImage init field is now deprecated. Please change to listItem.setArt() in your next update."

plugin.video.twitch/resources/lib/converter.py
  "Next update, please set the videolabel 'mediatype' to the correct value - newer skins need it to display the item correctly."

plugin.video.twitch/resources/lib/swiftwrap.py
  "This should also be fixed to use listItem.setArt() instead of the inits."
```

Thanks to everyone who has put their efforts into this project, there are many people out there who really appreciate it (myself included!).

Sprig

**Comment by anxdpanic** [comment]
Happy to help where I can 👍 and thank you for yours as well! 

point 1 closed by #194 
point 3-5 should be covered by #195

will look into the i18n change in the next bit unless someone beats me to it

**Comment by MrSprigster** [comment]
Thanks for the super quick commits to address these.

**Comment by anxdpanic** [comment]
point 2 closed by #196

**Comment by MrSprigster** [comment]
Nice work!  We are now Kodi compliant :D.

**Comment by anxdpanic** [comment]
👍
