### ISSUE TITLE
HTTP Error on 1.3.1

### ISSUE THREAD

**Issue by Joasis** [anxdpanic/plugin.video.twitch#197]
I got HTTP error on version 1.3.1. I now the issue has been fixed in 1.4.1, but i can't update my twitch due to dependencies. I know it's caused by Twitch introducing OAuth. Does anyone have a work around? It's not possible to upgrade my XBMC version.

Thanks.

**Comment by MrSprigster** [comment]
Unfortunately not. Why are you unable to update Kodi?

**Comment by Joasis** [comment]
I have a media center (TLBB), which comes with preinstalled XBMC. So unless they release a new version (which they don't) im stuck on Gotham build. 

I've tried altering the 1.3.1 code, to add Client-ID to header, but it seems like every code i input results in "Script failed".

**Comment by MrSprigster** [comment]
Kodi Gotham is unsupported for several reasons and it is unlikely that you will be able to make it work.
