### ISSUE TITLE
Can't list games, can't open favorites. Log shows exception in osrandom

### ISSUE THREAD

**Issue by andersea** [anxdpanic/plugin.video.twitch#198]
Hi. Yesterday twitch.tv plugin stopped working for me. I can't list any games. I can't open my favorites window.

My log shows an exception is thrown:

http://pastebin.com/sYZ32WC5

I am using version 1.4.3 on XBMCBuntu on a Intel NUC.

**Comment by anxdpanic** [comment]
There's no threading being used in the add-on that would cause this, seems like it may be a local issue.

First thing I would try is re-installing python-cryptography if you can

**Comment by MrSprigster** [comment]
The fix for this issue is installing cryptography 1.1 from pip. To do this you may need to uninstall python-cryptography from apt though.

https://pypi.python.org/pypi/crypto/1.1.0

**Comment by MrSprigster** [comment]
sudo pip install --upgrade cryptography

**Comment by BtbN** [comment]
I have a related issue. Since the update, my entire Kodi crashes with a spectacular segfault the moment this module tries to issue a https request. Or rather, after it's done doing so:

https://paste.pound-python.org/show/eik2ith9ww15CXgJNKaU/

Downgrading the system cryptography from 1.5 is not an option, as it would break large parts of the system.
What is the underlying cause of this? Some other package that needs updating?

**Comment by MrSprigster** [comment]
This may be worth a try in your situation:

"Hi folks, I was experiencing this issue on Gentoo. I have restored
functionality by rebuilding ffmpeg 2.8.6 with openssl support (previously
disabled and unneeded)."

**Comment by BtbN** [comment]
I'm using the static ffmpeg coming with kodi. Looked into its flags, and it's using gnutls instead of openssl.
Going to try using the system ffmpeg again, with openssl enabled. But last time this ended in disaster.

**Comment by andersea** [comment]
I upgraded my Ubuntu version to Ubuntu 16.04.1 LTS using do-release-upgrade from the command line.

https://help.ubuntu.com/lts/serverguide/installing-upgrading.html

Twitch.tv plugin is working again for me now.

Thanks for the advice!

**Comment by BtbN** [comment]
Reverting 8317cbd145c6c72cef0666 makes it work fine for me again.

**Comment by MrSprigster** [comment]
I'm wondering if its worth us reverting that too. Does anyone know if
Twitch plan to move everything to HTTPS or was it an isolated test that
provoked the contribution that changed us over to requests from urllib2 for
https support?

**Comment by BtbN** [comment]
Twitch did move everything to https.
But at least for me, https works great with the old method?

I added a Debug-Log into the downloadWebData function, and it successfully downloads a lot of(in fact, all of the requests are https) stuff via HTTPS.

**Comment by MrSprigster** [comment]
Please feel free to test 1.4.4 and provide feedback 👍  https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/releases/tag/1.4.4

**Comment by BtbN** [comment]
Works fine without any mysterious crashes.

**Comment by MrSprigster** [comment]
Woo! 🎱

**Comment by BtbN** [comment]
I wonder what the original commit/PR tried to fix though? To my knowledge, everything, including https, was working fine?

**Comment by anxdpanic** [comment]
The original monkey patch PR #156 was for issue #154

**Comment by MrSprigster** [comment]
Not sure, it felt a little (tiny tiny bit) quicker to load menus and didn't cause me any issues in my testing (on Windows) and appeared to fix an issue for the contributor so I merged the PR but in hindsight it appears to have caused more issues than it was worth.

**Comment by MrSprigster** [comment]
@anxdpanic  You are indeed correct (my memory is very broken it seems) ha.

**Comment by BtbN** [comment]
@anxdpanic  I'm referring to #185 

SSL certificate validation is enabled in the requests version as well.

The requests version in itself looks fine to me. But for some obscure reason results in weird crashes which involve openssl/cryptography/cffi/kodi, and apparently also other issues, depending on what libraries are installed in which versions.

So I agree, it's not worth the trouble. I'm still curious about what's going on and will keep investigating how it behaves with the patch back applied and switching various libraries around.

**Comment by MrSprigster** [comment]
@BtbN there seems to be various discussion regarding similar issues with the requests module here: https://github.com/pyca/cryptography/issues/2287 

Worth a look if you're intending to investigate more...

Sprig
