### ISSUE TITLE
Message for StateOfTheArt89 (everyone else, please disregard).

### ISSUE THREAD

**Issue by MrSprigster** [anxdpanic/plugin.video.twitch#200]
@StateOfTheArt89: I have sent you an email to the email address in your profile 👍 

Thanks,

Sprig

**Comment by StateOfTheArt89** [comment]
Hey @MrSprigster 
Could resend the mail? I screwed up the DNS entry for darcula.de so that mail went nowhere.
Thank you!

**Comment by MrSprigster** [comment]
Done :)

**Comment by StateOfTheArt89** [comment]
And received :)
