### ISSUE TITLE
Can't open"followers" "games" or anything else in the app

### ISSUE THREAD

**Issue by henriklb** [anxdpanic/plugin.video.twitch#201]
[log.txt](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/files/486201/follow_error_twitch.txt)

1.4.4 crashes. 1.4.3 works fine
Rpi2 running LibreELEC 7.0.3

**Comment by anxdpanic** [comment]
Only thing I can think of that may have caused that is something going wrong during install. Could you try uninstalling and installing the add-on again to confirm? If it still fails provide a full debug log if you can please,

**Comment by henriklb** [comment]
A reinstall of 1.4.4 worked, thanks!
