### ISSUE TITLE
Can't watch Past Broadcasts or Video Highlights from specific channel I'm subscribed to

### ISSUE THREAD

**Issue by SonOfSunTzu** [anxdpanic/plugin.video.twitch#207]
Hi,

Thank you - as always - I'm able to watch the vast majority of what I want to on Twitch, both live and recorded streams.

However for one channel, GeekAndSundry, which I'm subscribed to, any attempt to watch "Past Broadcasts" or "Video Highlights" just gives me an "http error" warning on screen. I'm able to watch these items if I access Twitch via a browser.

The specific error I receive is:

DEBUG: WaitOnScriptResult- plugin returned failure
INFO: CPythonInvoker(15, /home/xbian/.kodi/addons/plugin.video.twitch/resources/lib/**run**.py): script aborted
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/v93200152/-2/]
DEBUG: Playlist Player: one or more items failed to play... aborting playback

I'm getting the same error for version 1.4.4 of the AddOn on both Xbian and OpenELEC.

Let me know what kind of information you need to debug this - I can probably install useful software like strace or similar, pushing the HTTPS traffic through a useful proxy might be harder ;)

**Comment by anxdpanic** [comment]
Should work now with the latest github copy :)

**Comment by SonOfSunTzu** [comment]
What did you change?  I was about to embarrassingly explain that once I followed the oauth process "properly" ( as random as that process seems sometimes ) I can now access the subscription only content using my existing 1.4.4 version. I'm hoping I haven't made your battle with the Twitch API even harder...

**Comment by anxdpanic** [comment]
wasn't working for playback, only listing for me. so i appended oauth to the m3u8 url and it's working.

I can try on my end with it reverted to see if it was something else on my end. didn't notice anything else out of the norm. though only just subscribed to anyone pre tests. so may have been a delay somewhere.

**Comment by anxdpanic** [comment]
Yea, works reverted now as well.

**Comment by anxdpanic** [comment]
And no worries @OakTwo was no trouble and the sub was planned :) Odd timing for me having that issue testing led to the changes.
