### ISSUE TITLE
Error Contents: u'1080p60 - source' is not in list

### ISSUE THREAD

**Issue by eusi** [anxdpanic/plugin.video.twitch#210]
Hey,

I am not able to watch some streams (like the one from TwitchCon or RiotGames Worlds) because of the missing item in the quality list.

**Solution:**
You need to add (at least) '1080p60 - source' and '720p30 - source' to QUALITY_LIST_STREAM and/or QUALITY_LIST_VIDEO (i did both just to be sure) in ./resources/lib/twitch/constants.py

```
QUALITY_LIST_STREAM = ['Source', '1080p60 - source', '1080p60', '1080p30', '720p60', '720p30 - source', '720p30', '540p30', '480p30', '360p30', '240p30','144p30']
QUALITY_LIST_VIDEO = ['live', '1080p60 - source', '1080p60', '1080p30', '720p30 - source', '720p60', '720p30', '540p30', '480p30', '360p30', '240p30','144p30']
```

Thx to cspack for help.

**Just for completeness, my log snippet:**
00:29:44 T:14324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: u'1080p60 - source' is not in list
                                            Traceback (most recent call last):
                                              File "...\Kodi\addons\plugin.video.twitch\resources\lib__run__.py", line 7, in <module>
                                                sys.exit(PLUGIN.run())
...

**Comment by MrSprigster** [comment]
This is fixed in the current Github version in a more elegant way. Please download and test and let us know how you get on. :)

**Comment by eusi** [comment]
Nice, and thanks for your answer!

I tested the current "Twitch on Kodi" version on Kodi 17 Beta 3 (Krypton) via LibreElec (RPI) and Win32. It works fine! 
I would recommend to release the current version as 1.4.5 to the Kodi Addons Repository, because I bet I am not the  only one with this issue ^^

**Comment by MrSprigster** [comment]
Thanks for the feedback, I intend to release the latest version (with a
version bump) to the official Kodi repository as soon as its been
thoroughly tested but things are looking good so far so it should be on
there fairly soon.

Sprig
