### ISSUE TITLE
Suggestion: Auto quality

### ISSUE THREAD

**Issue by Jadty** [anxdpanic/plugin.video.twitch#216]
Hello. I don't know if it's ever been suggested, discussed or even possible, but is there any hope for Auto quality be a feature someday?

**Comment by WilliamStam** [comment]
keen for this aswell. im suffering from the stuttering issue at the moment (pretty much every quality), i know the auto wont change that, but while trouble shooting ive been jumping through the quality menu a lot and every time i wonder why there isnt an auto option

**Comment by anxdpanic** [comment]
Just double checked and adaptive hls is not very well supported in Kodi yet. It should work but not adaptive, and likely not best 'auto' results either.

**Comment by anxdpanic** [comment]
added Bandwidth for version 2(#235) in #256

**Comment by anxdpanic** [comment]
Closed by #282, opened #283
