### ISSUE TITLE
Amlogic S905 support

### ISSUE THREAD

**Issue by oliver989** [anxdpanic/plugin.video.twitch#217]
Hello,
Please make this work on Amlogic S905. Currently it installs fine, but streams will not play.

**Comment by hephooey** [comment]
I think the addon just extract the url for the stream and pass it to Kodi, it has nothing to do with hardware. On the otherside, I have a odroid-c2 (based on S905) and Jarvis plays most of the twitch streams. For Krypton, the stream stuck from time to time but still I do not think it is the fault of the twitch addon.

**Comment by crepton** [comment]
nice
