### ISSUE TITLE
Opening certain streams moves Kodi to primary monitor

### ISSUE THREAD

**Issue by fragande** [anxdpanic/plugin.video.twitch#218]
I'm using Kodi on a multi-screen setup running on the secondary monitor. For some reason, when certain streams are opened, the Twitch plugin moves Kodi to the primary monitor. When stopped it moves back to the designated monitor. This behavior is very inconsistent and only happens with certain streams. No other video plugin behaves like this. Is this a known issue and if so is there a fix for it?

**Comment by anxdpanic** [comment]
I would check if you have 'Adjust display refresh rate to match video' on in Kodi's playback settings. If so, disable it and try the same streams. Otherwise a debug log may help.
