### ISSUE TITLE
HTTP error 

### ISSUE THREAD

**Issue by richiegigabit** [anxdpanic/plugin.video.twitch#221]
Using Twitch addon version 1.3.1 

I keep getting an HTTP error for any of the functions I try to perform (Search, Featured Streams, etc.). I would like instruction on how I can potentially fix this myself. I only follow a few channels so If I can program the addon to just view the one channel I mostly watch that would be okay.

https://www.twitch.tv/maximilian_dood

**Comment by evan-sm** [comment]
Same problem, tried everything. Client ID, Token, general tab, api tab. Nothing works.

**Comment by anxdpanic** [comment]
version 1.3.1 is very far behind at this point, not sure what it would take to make it work. May try asking if anyone has a working copy of the add-on for whichever version of Kodi you are limited to in the forum. http://forum.kodi.tv/showthread.php?tid=134538&page=36&highlight=twitch
