### ISSUE TITLE
IRC Indefinitely Connecting

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#222]
While connecting using the IRC addon directly works, using the feature within the Twitch addon does not.

The overlay stays "Connecting please wait..." and the user can no longer use the rest of Kodi.

This is on RC 3 of 17 and the current version  of both the Twitch (1.4.5) and IRC (1.0.1) addons.

**Comment by ghost** [comment]
Here is a log file. It seems like the server is refusing the connection which may mean something is getting called wrong from within the Twitch addon.

http://pastebin.com/jmHfARxF

Do you see anything that I can fix or is it the addon?

**Comment by ghost** [comment]
I believe a port can (needs?) added to the call.

**Comment by nv043** [comment]
Are you sure you're using the write authentication token, and in the right format?  I had the same error until i changed to "oauth:" followed by the token.

**Comment by ghost** [comment]
I used the same authentication token as I used to log in, and I used both with and without the "oauth:" being included.

I hadn't tried since I posted this. It does work now. I don't think I can reproduce the behavior anymore.

**Comment by anxdpanic** [comment]
Likely just twitch irc servers being flaky, the add-on should append the "oauth:" for irc if not included.
