### ISSUE TITLE
Support timestamps in URLs.

### ISSUE THREAD

**Issue by xevz** [anxdpanic/plugin.video.twitch#223]
So, AGDQ 2017 is over and I'd love to watch some runs I missed.
Unfortunately this plugin doesn't support specific timestamps, so I have to jump forward manually, instead of just converting and sending the URLs in the [VOD thread on Reddit](https://www.reddit.com/r/speedrun/comments/5mq821/agdq_vod_thread_2017/) to Kodi.

**Comment by anxdpanic** [comment]
added in #261 for V2 (#235)

**Comment by anxdpanic** [comment]
Closed by #282

**Comment by xevz** [comment]
@anxdpanic 
So, basically #261 only helps me add the URL to create a list of URLs using the search_results method? I won't be able to just play the URL (after parsing) and jump to the specific timestamp using the "play" method?

**Comment by anxdpanic** [comment]
Yes. I just added seek_time parameter to the PLAY route, seek_time=[seconds]
