### ISSUE TITLE
Past Broadcast doenst work anymore

### ISSUE THREAD

**Issue by Chris0706** [anxdpanic/plugin.video.twitch#226]
Hey there,

since a few days (~4) I can't watch past broadcasts anymore. At the beginning everything works, but after some time video stops and only audio plays on.
Normally a quick +00:10 forward or backward does a resync and everything works again.. but now the progress bar gets completly broken and it doenst help anymore.
Tested with Odroid-C2 with Libreelec Alpha and also tested with RaPi 3 with OSMC. Maybe Twitch changed something?

Kind regards
Chris

**Comment by anxdpanic** [comment]
Once playback has started it is no longer add-on related. May want to take a look in Kodi/Libreelec/OSMC forums if it's not resolved.
