### ISSUE TITLE
Past Broadcast issue when stream is live

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#229]
Hi,

I noticed this weekend that current live broadcasts from streamers show up in the 'past broadcasts' view - which is correct and how Twitch currently works. The issue is that if I pick a past broadcasts vod that is actually in progress, selecting that broadcast will show you the current live stream. This is different than how twitch.com acts - while I'm able to go to a live streamer and view their past broadcasts (which includes the current live offering), I can click the current live steam in past broadcasts and it will start at the beginning.

**Comment by tofof** [comment]
~~Can you elaborate on why this is cantfix? The prior version of the plugin had this capability.~~
I misread the final line of the OP; disregard. 
(The prior version had the same behavior on a 'live' vod even in past broadcasts.)

**Comment by cmsimike** [comment]
You know, I tested this out recently and it seems it works. I don't know what causes it to not work vs work.
