### ISSUE TITLE
New transcode system and new stream names

### ISSUE THREAD

**Issue by pmarzi** [anxdpanic/plugin.video.twitch#231]
So, Twitch seems to be rolling out a new transcode system, that again, uses slightly different stream quality names.
The '_getLiveStream_' method can not determine if a stream using this new system is live or not, because there is no stream named '_NAME="360p30"_' in the playlist file. Since there is no such named stream, it chooses to use the '_OLD_QUALITY_LIST_STREAM_' list which then fails completely, because the new system uses the correct quality names...well except for the one named '_1080p60 (source)_'.

I don't think that twitch is using the old system anywhere anymore, so it might be fine to just remove that check to fix this. (api.py line 202 & 203)

As an idea to make this whole process independent of a fixed lookup table, maybe just grab all of the available stream names from the playlist, sort them by resolution and frame rate and choose the best (depending on sort: first or last entry) of these.
In terms of the config UI, the above idea would be the 'auto highest quality' option, to allow specific options split the resolution and frame rate into two different selection options (yes, a fixed LUT) and use the selected values for choosing a value from the gathered available stream qualities.

Btw. you might also want to change to use TLS for the playlist URLs under the new url 'https://usher.ttvnw.net...' which seems to be the new url for the playlist because the SSL cert is only valid for that domain.
In case you want to use the TLS stuff, you might also need / want to add the 'need_https=true' parameter to the channel token URL.

**Comment by anxdpanic** [comment]
Should be _resolved_ in #234, with changes to quality selection coming in v2 (#235)
