### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by anxdpanic** [anxdpanic/plugin.video.twitch#235]
Version 2 is finalized

Available @ https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.0.0

**Comment by MrSprigster** [comment]
I've been actively testing v2 (alpha4) for the past 5 days and all seems good. 
I particularly like the new features (in add-on Follow is a God send).

Thanks @anxdpanic , keep up the amazing work.

**Comment by grocal** [comment]
Same for me with _alpha4_. Looks promising. So far no serious problem if any.  The only one I've encountered was lack of `userdata\addon_data\plugin.video.twitch` creation upon installing, which threw exceptions and did not allow to use the addon. After manually creating folder - no problems.

`File "C:\Users\x360\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon\common\json_store.py", line 33, in save`
`with open(self.filename, 'wb') as jsonfile:`
`IOError: (2, 'No such file or directory', u'C:\\Users\\x360\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.twitch\\storage.json')`

**Comment by anxdpanic** [comment]
Thanks :) Directory creation should be fixed in dev branch now along with minor fix to search

**Comment by cmsimike** [comment]
Awesome! I am looking forward to this release.
Is there any ETA? Will the 1.x line upgrade to the 2.x, or will it be a new addon?

**Comment by cesarDevOp** [comment]
Hello @anxdpanic,
i am testing your releases (plugin.video.twitch-1.4.6-alpha1 and plugin.video.twitch-2.0.0~alpha4)
In 1.4.6 i test the high, medium, low quality, but it always runs on 1080.
In contrast, i try to install 2.0.0 but its drops me dependency error on installation.

Thanks for your work

**Comment by anxdpanic** [comment]
@cmsimike no ETA as of yet still working on a few things between the add-on and module. It will update to the new version and will install the required module during the update as well.

@cesarDevOp 1.4.6 was working when I tested, should be more than 1080 for sure. I re-labeled the qualities to show where 'high', 'medium', etc.. are triggered.  As for dependency error, [script.module.python.twitch](/MrSprigster/script.module.python.twitch) needs to be installed first. The easiest way to do that would be to just install [repository zip](https://raw.githubusercontent.com/anxdpanic/__testing_repository/master/zips/repository.anxdpanic.testing/repository.anxdpanic.testing-0.0.1.zip) and update the Twitch add-on.

**Comment by cesarDevOp** [comment]
@anxdpanic I continue testing and I surprised myself when you released 2.0.0-alpha5. It promises a lot.
I have some bad experiences, because I have a rpi 1, they crash kodi and restart my rpi. This is the reason because I am focusing on the possibility of changing the video quality.

Now, I am going to put my efforts on 1.4.6-alpha, and I reproduced the quality problem. It works fine on a live channel, but when I try a "past broadcast", it omits the quality i set.

Tell me if I can help you in some approach.

**Comment by cmsimike** [comment]
@anxdpanic thank you! I look forward to the release.

**Comment by Giacom** [comment]
Been having no issues with version 2 so far. Only complaint is that it's very slow on the Raspberry Pi, with it having to go through all the new sub-menus and having to refresh the menus when you go back (via ..)

**Comment by cesarDevOp** [comment]
@anxdpanic I have news about the problem of changing resolution (I think video attribute), I get urls from firebug and I get:

which works 
`#EXTM3U
#EXT-X-TWITCH-INFO:ORIGIN="swift",CLUSTER="akamai_vod",REGION="EU",MANIFEST-CLUSTER="akamai_vod",USER-IP="xx.xx.xx.xxx"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="Source",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4751178,CODECS="avc1.428020,mp4a.40.2",RESOLUTION="1280x720",VIDEO="chunked"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/chunked/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="144p30",NAME="144p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=120293,CODECS="avc1.42C00C,mp4a.40.2",RESOLUTION="256x144",VIDEO="144p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/144p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="240p30",NAME="240p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=181990,CODECS="avc1.42C015,mp4a.40.2",RESOLUTION="426x240",VIDEO="240p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/240p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=336841,CODECS="avc1.42C01E,mp4a.40.2",RESOLUTION="640x360",VIDEO="360p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/360p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=783176,CODECS="avc1.42C01E,mp4a.40.2",RESOLUTION="852x480",VIDEO="480p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/480p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="540p30",NAME="540p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=525592,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION="960x540",VIDEO="540p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/540p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p30",NAME="720p30",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=928919,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION="1280x720",VIDEO="720p30"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/720p30/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1998133,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION="1280x720",VIDEO="720p60"
https://vod046-ttvnw.akamaized.net/v1/AUTH_system/vods_ddc2/riotgames_24903185760_625119605/720p60/index-dvr.m3u8`


and which not works:
`#EXTM3U
#EXT-X-TWITCH-INFO:ORIGIN="swift",CLUSTER="akamai_vod",REGION="EU",MANIFEST-CLUSTER="akamai_vod",USER-IP="xx.xx.xx.xxx"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="Source",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8277558,CODECS="avc1.64002A,mp4a.40.2",RESOLUTION="1920x1080",VIDEO="chunked"
https://vod189-ttvnw.akamaized.net/v1/AUTH_system/vods_6606/lvpes_24908471216_625449946/chunked/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="high",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1140030,CODECS="avc1.4D401F,mp4a.40.2",RESOLUTION="1280x720",VIDEO="high"
https://vod189-ttvnw.akamaized.net/v1/AUTH_system/vods_6606/lvpes_24908471216_625449946/high/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="low",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=503876,CODECS="avc1.42C01E,mp4a.40.2",RESOLUTION="640x360",VIDEO="low"
https://vod189-ttvnw.akamaized.net/v1/AUTH_system/vods_6606/lvpes_24908471216_625449946/low/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="medium",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=614649,CODECS="avc1.4D401E,mp4a.40.2",RESOLUTION="852x480",VIDEO="medium"
https://vod189-ttvnw.akamaized.net/v1/AUTH_system/vods_6606/lvpes_24908471216_625449946/medium/index-dvr.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="mobile",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=177967,CODECS="avc1.42C00D,mp4a.40.2",RESOLUTION="400x226",VIDEO="mobile"
https://vod189-ttvnw.akamaized.net/v1/AUTH_system/vods_6606/lvpes_24908471216_625449946/mobile/index-dvr.m3u8
`
edit: removed ip

**Comment by anxdpanic** [comment]
@cesarDevOp thanks, should be resolved in master if any follow up please use #225 so we can keep this to version 2.

@Giacom thanks for the feedback. my main use device is an rpb2 too. So far only the api requests are cached. When new additions are done will also be going back through for some performance/cosmetic updates.  * seems api requests weren't being cached either, fixed now.

**Comment by anxdpanic** [comment]
Just added the last new feature I can think of or that has been suggested. Over the next few days will make a pass to make any changes that may cause breakage. After that will bump to beta for performance and bug fixes.

**Comment by anxdpanic** [comment]
Pushed to beta1 today, creating new favorites etc should be safe now. There were some bugs fixed in this push that should also improve performance.

If you run into any bugs please post a debug log with version along with any contextual information you feel may be relevant.
Thanks!

**Comment by tofof** [comment]
Hooray for in-addon follow! 

Not sure how current my version is (probably about a year out of date now), so forgive me if these have already been addressed. (Phone makes searching old issues and separating these difficult.)

1. Chat overlay gets stuck open if login fails. Ignores clicking close button.

2. No indication of how to reopen chat if closed.

3. Followed games list displays all games rather than only ones with current streams.

Love the plugin, keep up great work!

**Comment by anxdpanic** [comment]
Thanks. Not much can be done with chat, that project itself would require some updates. Games no longer just returns live channels there is also a section for Clips, so that behavior for followed games hasn't changed.

**Comment by anxdpanic** [comment]
Shooting for end of this week for release point, so there may be a few quicker version bumps for any bugs to ensure fixes get tested. 

@Giacom Things are running better on my rbp, has this improved for you as well? and you are also now able to control which items(all main sub menus) are on the main menu. You can go as far to remove all the default main menu items and add all sub menus to the main menu.

Thanks again everyone for testing. 👍

**Comment by MrSprigster** [comment]
@anxdpanic You've done a great job with this! Thanks again.

When you feel it's ready for release, feel free to move it to the main
branch and create a release and I'll process the submission to the Official
Kodi Addon repository.

**Comment by anxdpanic** [comment]
~~Forgot to add, I have not been able to find a stream/vod that uses the Audio Only transcode, if anyone has an example of a stream/vod that does it would be appreciated~~

Audio only added now

**Comment by Giacom** [comment]
@anxdpanic Thanks, I'll test out the customisation menu system.

Found an issue whilst quickly testing the latest version, related to external requests to play a twitch stream. The chrome extension ["Play to Kodi"](https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden?hl=en) is no longer compatible and can no longer tell the plugin to watch a Twitch stream. Perhaps there an API change that broke compatibility or it could be something else?

**Comment by anxdpanic** [comment]
It has already been resolved in Play to Kodi and will be included with their next update. Was reported by another user to them. Reference to that report is included above.

**Comment by poison25** [comment]
I am running kodi and spmc on my nvidia shield 1.4.6 alpha 2 worked great.
Wanted to try the 2.0 version so I added the test repo and it updated to 2.0.0 beta3
After that twitch stoped working can't open the app.
Tried deinstalling twitch and reinstalling beta3.  
Tried deininstalling kodi and spmc, fresh install of spmc and twitch  beta 3. 
Won't start. 

Today it updated it self to beta 5 still not working.


P.S.
Twitch 2.0.0 beta x won't start on fire tv kodi either while 1.4.6 alpha2 works great

**Comment by anxdpanic** [comment]
If you can post a full [debug log](http://kodi.wiki/view/debug%20log), would be happy to take a look for you.

**Comment by poison25** [comment]
Thanks here is an spmc log



edit:
full debug log

**Comment by anxdpanic** [comment]
Just pushed a fix. If you manually check for updates, the update with the fix should show up soon. Thank you for reporting and providing the logs to have this resolved.

**Comment by poison25** [comment]
beta 7 fixed the problem that the app won't open 

but

after i enter my auth token 
the app says "failed to connect to twich api" 
and closes the app 
every time after that the app won't open with the same error.

deinstall and reinstall twich lets me open the app and enter the token again but then the same error

**Comment by anxdpanic** [comment]
Thanks, I just pushed another set of updates. Hopefully resolves the issue, also added additional logging to that area to see if it provides any further information if it still occurs.

**Comment by zaboris** [comment]
I've just tried installing the 2.0 alpha 8 (or whatever version it is right now lies in anxdpanic's repo) from scratch, after uninstalling the 1.4.6~alpha2, and it still doesn't work. Running Andriod 4.4.2, Kodi 16.1, log files attached
[kodi.log.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/930929/kodi.log.txt)

**Comment by poison25** [comment]
Client I'd mismatch
Go get new token

Error

**Comment by anxdpanic** [comment]
@zaboris  if you install the repository zip above you will get the updated versions. That error is resolved.

@poison25 That means the oauth token wasn't generated using Get OAuth token link. So you just need to follow the link you are given to get a new one. If you are confident that you are using the new oauth token. Settings - Cache - reset and possibly reboot (may be pyo related).

**Comment by poison25** [comment]
i am using the goo.gl/arFEqk link to creat the token

reset reboot reinstall always "client id mismatch"

cant open any stream also always error "look in log File"

**Comment by anxdpanic** [comment]
the client id issue was introduced in the last one. Just got that resolved, and your new error resolved as well. So hopefully smooth sailing now. :)

**Comment by poison25** [comment]
Thx.
Works great.

**Comment by anxdpanic** [comment]
Great to hear 👍 I don't have any way to directly test for those os/environments, so thank you for your patience and confirming. 

@zaboris The latest betas should be resolved for you now as well. If you are able to confirm, that would be great. 

Thanks again!

**Comment by zaboris** [comment]
@anxdpanic Hello! 
Using 2.0 alpha 8 from your beta repo (is it the latest one?), I keep getting errors like poison25 did: client id mismatch. Cannot play any streams. Won't show my followed channels. Tried opening the link goo.gl/arFEqk on my device, logging on twitch via browser and copying that oauth token to kodi, without any success ;( Tried clearing cache, rebooting whole device.

[kodi2.log.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/934837/kodi2.log.txt)

**Comment by anxdpanic** [comment]
The latest version is beta9, manually checking for updates should get you the new one.

**Comment by zaboris** [comment]
Had to manually reinstall repo from zip, after that it allowed me to install the beta9. **Works just fine so far!!** Notifications, clips - everything is working as intended! 

@anxdpanic Thank you very much for hard work!

**Comment by anxdpanic** [comment]
And thank you for confirming 👍

**Comment by MrSprigster** [comment]
@anxdpanic It seems 1.4.6 is starting to have issues with the evolution of the Twitch API and as a result I suspect it may be the right time to release 2.0.0 at its current stage of development. Any additional bug fixes can be added in future minor releases. What are your thoughts?

Sprig

**Comment by anxdpanic** [comment]
@MrSprigster Filtering may need some tweaking, I haven't been able to reproduce as of yet though. Not breaking by any means and should be fine. Intended to do it last night but both days have been derailed :) I should be able to wrap up everything tomorrow morning and coordinate the last bits with you whenever you're available. That sound alright?

**Comment by MrSprigster** [comment]
Sounds good to me. Thank You for putting so much effort into this.  Big thanks to the testers who provided feedback too.

**Comment by henriklb** [comment]
Looking forward to 2.0. Thank you for your hard work. Greatly appreciated!

**Comment by schlegp** [comment]
Hey, sorry if this is not the right place to ask for help, but after skimming the internet for a while, I have found nothing and am out of ideas. I'm trying to use the Addon.AddonExecute JSON-RPC command to open a stream. Sadly I have no idea which params are needed.
Could anyone direct me to a location/file, where I can find all the possible params for using this?

**Comment by cmsimike** [comment]
@schlegp What I found that worked is:
First create a bookmark to the item you want (I created one to the 'following' screen
Look at your bookmarks.xml in your kodi directory.
The information you need to make the api call should be in there


I would like to re-iterate that my current version seems broken (the alpha version of 1.4.6 i think). I look forward to the final release!

**Comment by Baerht** [comment]
using the version 2.0,0 beta 10 and I cant find the field where I cant input my twitch user name

**Comment by Bananaburger** [comment]
Hi, thank you for all of the work you guys have done on this app. I'm not sure if this belongs in a separate issue post, but ever since I updated today (beta 10) I've run into a problem. There's a streamer I enjoy watching and often puts his stream as "Not Playing", which makes it so a game doesn't have to be selected when you go live. Ever since I switched, I haven't been able to see this stream listed in my Following page, making it impossible to view the stream at all. If anyone knows a solution, that would be great.

Thanks!

**Comment by anxdpanic** [comment]
@schlegp the params for playing;
videos are { mode: play, video_id: <video_id> }
streams are { mode: play, name: <channel_name>, channel_id: <channel_id> } 
clips are { mode: play, slug: <clip_slug>, channel_id: <channel_id> } 
optional parameter for playback are { ask: true, player: true }, ask will force asking for quality, and player will use Kodi Player() instead of setResolvedUrl which can be useful from certain contexts.

@Baerht the oauth token provides username/user id, the new api uses id's not names (introduction of name changes) 

@Bananaburger Can you provide the name of the channel? I don't know any using that myself, though I suspect it's something missed in the new api.

And huge thank you to everyone for testing and feedback! 👍

**Comment by MrSprigster** [comment]
Version 2.0.0 has now been submitted to the Official Kodi Addon Repository. 

Changes should go live within 24 hours (unless the Kodi team require any amendments)

**Comment by MrSprigster** [comment]
https://github.com/xbmc/repo-plugins/pull/1181
https://github.com/xbmc/repo-scripts/pull/494

**Comment by Bananaburger** [comment]
@anxdpanic: The channel name is stereotonetim. A few other things I noticed when I switched to 2.0:

A) When viewing a VOD and the chat option is enabled, the chat will connect to a channel called #None. 

B) After updating, VODs that I had previously watched will not play anymore. This is possibly due to a problem with the conflicting versions and old information not being compatible, possibly involving bookmarked times. Haven't tried clearing out the old info manually but I have tried doing "Reset function cache" which didn't work.

C) Not really a bug, but in the followers list the channels used to be sorted alphabetically. Now under Following > Channels it seems like the channels are all scrambled. Not sure how they're sorted now or if they're sorted at all.

I feel like there was something else, I'll edit this post if I can remember what it was. Again, thank you all for your work on this project.

**Comment by anxdpanic** [comment]
Thanks I will look into that, and see what I can find out.
Will address A on github for the next version next chance I get, thanks for mentioning it. #285 resolves.
For B old favorites and shortcuts will not be compatible.
For C, there is no longer alphabetical sort but if you open the context menu on the Channels folder you can change the sorting parameters that are provided by the api. This is also the case for the vod menus, and wherever else the api allowed.

Also anyone that has installed the testing repository, the update to 2.0.0 will come from the official repository so you can uninstall the testing repository now and not miss any updates.

**Comment by anxdpanic** [comment]
V2 is live on the official repository, just confirmed update locally. Thanks again for everyone's participation. 👍
