### ISSUE TITLE
Only first 25 followed channels are parsed

### ISSUE THREAD

**Issue by grocal** [anxdpanic/plugin.video.twitch#25]
Hi!

According to [TwitchAPI - follows documentation](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-usersuserfollowschannels) default call for followed channels returns only first 25 items therefore only those 25 items are analyzed for being online. It's a problem for anyone who, like me, has more than 25 followed channels because if any online followed channel is not on that 25 first items list - I won't see it in TwitchTV addon for XBMC.

Solution is quite easy.
1. Increase limit for retrieved items to 100 (maximum allowed) by adding limit=100 to url used for retrieving followed channels - _users/{0}/follows/channels?limit=100_. That would retrieve maximum amount of data we can with one call. 
2. Every call returns url link for next "chunk" of data (_[_links][next]_) and total count of followed channels (_[_total]_). We just have to iteratively call for next chunk of data until there are no followed channels returned while collecting those returned channels after every call.

I could fix that on github but my python knowledge is actually very low so it's better to leave that in more capable hands.

Greetings!

**Comment by ccaspers** [comment]
I will have a look into it, when I find some time. It seems to be possible but note that multiple requests will slow down the display of channels ;)

**Comment by grocal** [comment]
Glad I have only 90 followed channels :P
