### ISSUE TITLE
_fetchItems() returning NoneType

### ISSUE THREAD

**Issue by nalle** [anxdpanic/plugin.video.twitch#280]
Hi,

Today the plugin started behaving badly when opening Following, logs returned 
TypeError: object of type 'NoneType' has no len()

Dug through the plugin code and found that the return data from the twitch api gave us this:
{
	u '_total': 8, u 'streams': None, u '_links': {
		u 'followed': u 'https://api.twitch.tv/kraken/streams/followed',
		u 'self': u 'https://api.twitch.tv/kraken/streams?channel=xxx&limit=100&offset=100&stream_type=live',
		u 'summary': u 'https://api.twitch.tv/kraken/streams/summary',
		u 'next': u 'https://api.twitch.tv/kraken/streams?channel=xxx&limit=100&offset=200&stream_type=live',
		u 'featured': u 'https://api.twitch.tv/kraken/streams/featured',
		u 'prev': u 'https://api.twitch.tv/kraken/streams?channel=xxx&limit=100&offset=0&stream_type=live'
	}
}

Where _fetchItems() tries to return items[key] where key is streams in the previous dict.

Not sure what long term effects it will have but changing
        return items[key] if items else []
to
        return items[key] if items[key] else []
fixed the issue and allowed me to list following again and play the stream.

Not really expecting a result or to dig further into it, just though someone might want to know and have a look at it :)

**Comment by Tomalak** [comment]
This is caused by `twitch/api.py`, function `_fetchItems` right at the end of the file.

This function currently reads

``` python
    def _fetchItems(self, url, key):
        items = self.scraper.getJson(url)
        return items[key] if items else []
```

but it should read

``` python
    def _fetchItems(self, url, key):
        items = self.scraper.getJson(url)
        return items[key] if items and items[key] else []
```

because apparently Twitch started to return `null` for certain keys. 

Modifying the file accordingly fixes the error for now.

**Comment by MrSprigster** [comment]
I recommend you guys try 2.0 Beta 10. Details here: https://github.com/MrSprigster/Twitch-on-Kodi/issues/235

**Comment by Tomalak** [comment]
@MrSprigster Is it worth it to make a PR for this?

**Comment by MrSprigster** [comment]
Are you experiencing the issue while testing 2.0 Beta 10? If not then don't waste your time updating old code as release of 2.0 is fairly imminent.

**Comment by Tomalak** [comment]
Not tested 2.0 beta yet. 

This seems to be a fairly trivial fix and having a working fallback version isn't the worst thing in the world, I think. :)

**Comment by Tomalak** [comment]
It's not clear to me where to get the beta from, I am afraid to say. I don't do this every day.

**Comment by MrSprigster** [comment]
Feel free to submit a PR. Beta is available by installing the testing repository using install from zip in Kodi, you'll then be able to update to the latest testing release as it's released Link(https://raw.githubusercontent.com/anxdpanic/__testing_repository/master/zips/repository.anxdpanic.testing/repository.anxdpanic.testing-0.0.1.zip )

**Comment by Tomalak** [comment]
Okay, here it goes #281.

**Comment by anxdpanic** [comment]
Thanks. :) v1 has been moved to branch '1.x.x'.  I can't see maintaining it for back up for much longer, the v3 api used in that version is already deprecated and to be discontinued in less than a year.

**Comment by Tomalak** [comment]
@MrSprigster FYI Version 2 beta seems to work for me, apart from a stray "your ID is not valid" dialog that popped up in the middle of a running stream after I successfully registered my ID. We'll see.

The one thing I'm not a big fan of right off the bat is that I have to navigate two menu levels up and two menu levels down each time I want to switch between a live stream and a recorded one. The v1 view that showed online and offline followings next to each other was friendlier. :-|

**Comment by anxdpanic** [comment]
@Tomalak Those were separated for a couple reasons; pagination (think 100's-1000+), channels/offline has api supported sorting (context menu)

**Comment by Tomalak** [comment]
@anxdpanic I guess it takes some getting used to. Then again I'm not following 1000 channels (I have a hard time believing anybody does) so for someone like me it more than doubles the workload for something that used to be easy. That's a bit of a bummer.
