### ISSUE TITLE
Couple of streams doesnt play

### ISSUE THREAD

**Issue by MrMuhs** [anxdpanic/plugin.video.twitch#287]
Hello,

since couple of weeks i got some issue with a raising number of streams, they aren't playing anymore. I guess there is some ongoing change on twich?
If i open an effected stream from my follow list, i get for example this:

08:06:01 567.136414 T:1680098368  NOTICE: [xbmcswift2] Request for "/createFollowingList/" matches rule for function "createFollowingList"
08:06:03 569.140747 T:1680098368  NOTICE: Thread BackgroundLoader start, auto delete: false
08:06:06 572.300842 T:1680098368  NOTICE: Thread LanguageInvoker start, auto delete: false
08:06:07 572.515076 T:1680098368  NOTICE: -->Python Interpreter Initialized<--
08:06:07 572.971741 T:1680098368  NOTICE: [xbmcswift2] Request for "/playLive/monstercat/-2/" matches rule for function "playLive"
08:06:08 574.410217 T:1967747072   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/monstercat/-2/]

Googling this, it seams like some generic error from the xbmc, so before digging deeper, i'd like to ask here what this is about, as you most probably know about it ;D

[kodi.log.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/963814/kodi.log.txt)

**Comment by anxdpanic** [comment]
There is a new version waiting for review on the official repository.
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.0.0

#235 and https://github.com/MrSprigster/Twitch-on-Kodi#login for more information regarding this version as well.

**Comment by MrMuhs** [comment]
OK, cool - so i have to install it manually from the Repo? or does it get automatically updated from the official soon?

**Comment by anxdpanic** [comment]
It should come from official in the next few days, depending on how long review takes. 

You can also install manually from the first link, install from zip for both of the files there. script.module.python.twitch needs to be installed first, and then plugin.video.twitch.

**Comment by MrMuhs** [comment]
Ok, if its about days i will just wait them (or install from repo in a week or two ;)) - thanks a lot!
