### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by Evergetic** [anxdpanic/plugin.video.twitch#288]
I have version 1.4.5 and (obv) it's not working. I have OSMC on a Raspberry Pi. I have the Kodi add-on repository from which I have the twitch add-on. It's not giving me any updates and I'm seeing 1.4.6 (even 2.0) is already out.

**Comment by MrSprigster** [comment]
The Minimum version of Kodi to be presented with v2.0.0 is Isengard. If you don't see an option to update then you may need to up update Kodi first

**Comment by Evergetic** [comment]
I have kodi 17 (should be latest)

**Comment by MrSprigster** [comment]
It could also take some time from being accepted in the submission repository to being available as an update in Kodi

**Comment by Evergetic** [comment]
Any idea how long such a thing could take?

**Comment by MrSprigster** [comment]
When their public update repository syncs with their submission repository. Unfortunately, I'm not privvy as to when or how often that happens so we will just have to be patient.

**Comment by Evergetic** [comment]
Alright, I'll just have to be patient and wait then. Thanks!

**Comment by MrSprigster** [comment]
If you're desperate for 2.0.0, there's instructions how to install beta 10 (which is pretty much identical to the release) in the 2.0.0 testing thread in issues

**Comment by Evergetic** [comment]
Oh really? I'll check it out when I get home, thanks :)

**Comment by anxdpanic** [comment]
I was just able to update from the official repo, all should be good for updates now. :)

**Comment by MrSprigster** [comment]
@anxdpanic it's still offering me v1.4.5 on official repository (I'm on Kodi 17.2). So it may take a little longer to sync across add-on repositories for all versions.

**Comment by MrSprigster** [comment]
Also still listed as 1.4.5 ( https://kodi.tv/addon/plugins-video-add-ons/twitch )

**Comment by anxdpanic** [comment]
Strange, on the same version and updated. Wonder if that's related to local cache. I would expect that page likely has an 8-24hr cache as well.

**Comment by MrSprigster** [comment]
Yep, ISP cache. Went through VPN and bam it appeared.
