### ISSUE TITLE
Cannot see the whole URL on my Kodi

### ISSUE THREAD

**Issue by pernix84** [anxdpanic/plugin.video.twitch#289]
Installed 2.0.0 and I now need to register the Twitch addon on Kodi on twitch API. Went to "Get Auth Token" option, pressed it, I can only see the part of the Twitch API URL (the UI trims the rest)
I extracted the my client_id, but I would need additional parameters which is not visible.
(Using Jarvis and default UI)

**Comment by anxdpanic** [comment]
This is with confluence jarvis? can you confirm the resolution as well, would like to resolve this if possible.

This url will work for a bit: https://goo.gl/arFEqk

**Comment by pernix84** [comment]
Yes, default Confliuence, I don't know the res but I would assume Full HD 1920x1080. Took a picture to bet able to better see
![18215984_10208267650878426_37360422_o](https://cloud.githubusercontent.com/assets/6803332/25557126/1742443c-2d0b-11e7-97ae-79454909e89a.jpg)

**Comment by anxdpanic** [comment]
Thanks, that url should have been shortened to a goo.gl url, so that narrows things down a bit. The url I posted should work to generate a token in the mean time.

**Comment by pernix84** [comment]
Thanks @anxdpanic!

**Comment by anxdpanic** [comment]
#295 closes
