### ISSUE TITLE
Playback failed on latest github version.

### ISSUE THREAD

**Issue by bbck** [anxdpanic/plugin.video.twitch#29]
Commit 2c16714fee broke the addon for me. I'm using raspbmc on my raspberrypi and no streams are able to play. Rolling back to the previous commit fixes the problem.

```
07:20:11 T:2840077376  NOTICE: Thread XBPyThread start, auto delete: false
07:20:11 T:2840077376  NOTICE: -->Python Interpreter Initialized<--
07:20:12 T:2840077376  NOTICE: [xbmcswift2] Request for "/playLive/dreamhacksc2/" matches rule for function "playLive"
07:20:12 T:2840077376 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
07:20:13 T:3038388224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/dreamhacksc2/]
```

**Comment by ccaspers** [comment]
I could not reproduce that error, not meaning that it doesn't exist. I will add some debug-calls to the plugin in the next few days, so we can check whats really going wrong there.

**Comment by StateOfTheArt89** [comment]
I got my raspberry pi back to life to check for this error. I was able to reproduce it.

**Comment by prometheanfire** [comment]
I am also able to reproduce it, base OS is xbmcbuntu.

23:09:58 T:3077691152  NOTICE: Starting XBMC (12.2 Git:32b1a5e), Platform: Linux (Ubuntu 11.10 - XBMCbuntu, 3.0.0-32-generic i686). Built on May  2 2013

**Comment by ccaspers** [comment]
what about the current version?

**Comment by bbck** [comment]
Tried the latest version on a stream with and without a subscription and they both worked.

**Comment by ccaspers** [comment]
great - so the issue seems to be resolved for now
