### ISSUE TITLE
Constant popups about bad OAuth token

### ISSUE THREAD

**Issue by Orphis** [anxdpanic/plugin.video.twitch#291]
Since the update, I constantly get error messages about a bad OAuth token.
The problem is: it is working fine, I get to see my followed channels, games and all of that just fine. So it is working fine. I regenerated once, but still have the issue.

Have other people seen this too?

**Comment by anxdpanic** [comment]
Which popup, Client-id mismatch, missing scopes, or not valid? You can try refreshing cache(settings-cache), and possibly restarting Kodi(may be service related). If that doesn't resolve can you post a debug log?

**Comment by StripedBanana** [comment]
I have this message every time I start up the extension, but only once though, so not that annoying. FYI I haven't put in any credentials yet (I don't want to).

**Comment by Orphis** [comment]
Invalid OAuth. I have restarted Kodi several times and still get those. Once I even got a message when I was watching a local file too.

There isn't much outstanding in the logs beside the OAuth error when the service starts and later a GetDirectory error (for which I don't get any notification).

> 04:55:34.127 T:139992605116160  NOTICE: Twitch: Service: Start
01:25:11.357 T:139992644450048   ERROR: Twitch: Error: Current OAuth token is invalid.
01:25:11.357 T:139992644450048  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
01:26:27.803 T:139991875303168  NOTICE: Twitch: Calling |settings| for mode |settings| with pos args |[]| and kwargs |{}|
01:26:36.296 T:139992646285056  NOTICE: Twitch: Calling |get_token_url| for mode |get_token_url| with pos args |[]| and kwargs |{}|
01:26:37.084 T:139991875303168  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
01:26:37.121 T:139993830314176   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?mode=settings
01:26:37.122 T:139993830314176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?mode=settings) failed
01:26:37.834 T:139991875303168  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
01:27:57.214 T:139990768023296  NOTICE: Twitch: Calling |get_token_url| for mode |get_token_url| with pos args |[]| and kwargs |{}|
01:29:31.987 T:139992571004672  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
01:29:35.625 T:139992571004672  NOTICE: Twitch: Calling |following| for mode |following| with pos args |[]| and kwargs |{}|
01:29:46.521 T:139992571004672  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['channels']| and kwargs |{}|
01:29:50.133 T:139991875303168  NOTICE: Twitch: Calling |following| for mode |following| with pos args |[]| and kwargs |{}|
01:29:52.652 T:139991875303168  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
01:29:56.975 T:139991875303168  NOTICE: Twitch: Calling |settings| for mode |settings| with pos args |[]| and kwargs |{}|
01:30:09.681 T:139991875303168  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|

**Comment by anxdpanic** [comment]
A log with debugging turned on should provide more information. http://kodi.wiki/view/Log_file
Can you confirm you generated the new oauth token through the add-on settings - Login - Get OAuth token ?

**Comment by Orphis** [comment]
Yes I did. Interestingly, I haven't had the error all day so far...

**Comment by eobet** [comment]
I also get this error lately.

I cannot generate a new OAuth token via the add-on menu popup. Simply nothing happens when I click OK.

I have however pasted my OAuth token from the Twitch.tv control panel, but I still get the error message.

**Comment by anxdpanic** [comment]
@eobet 
Nothing should happen when you click OK. And the old token, or self created will not work unless you have set up the redirect uri correctly as well(not for regular users). 
First if you have anything entered in Settings - Developer, clear those out and click OK to save the settings.
Then follow https://github.com/MrSprigster/Twitch-on-Kodi#login to generate a token.

If this fails, a debug log of you trying the process, or more details will be required to help resolve.

**Comment by eobet** [comment]
That worked, thanks!

Still perhaps worth noting that I got the error message in the first place, after having it work flawlessly for several months...
