### ISSUE TITLE
Channels doesn't appear in the "live channel" directory when classified in "communities"

### ISSUE THREAD

**Issue by idoric** [anxdpanic/plugin.video.twitch#292]
It seems that when online and classified in "communities", a followed channel doesn't appear in the "live channel" directory.

Example: I follow https://www.twitch.tv/mahyars. When online and classified in https://www.twitch.tv/communities/Talk-Shows, that channel is not visible in the "live channel" directory of the twitch plugin.

**Comment by anxdpanic** [comment]
Does mahyars use "Not Playing" for their game? The community should have no effect, all my following lists are playing in/part of a community and show fine. It has been brought up that "Not Playing" is not showing though.
Will look further into this next chance I get.

**Comment by idoric** [comment]
I'm not sure what "Not Playing" is. Do you mean no little rectangle (with visual of the game, or talk show...) at bottom right of the thumbnail on the https://www.twitch.tv/directory/following page? If that's what you're talking about, then he used "Not Playing". (On Mahyar's chain, this happens only when it is classified in communities. This explains my mistake.)

**Comment by cmsimike** [comment]
EXBC is currently live but is not showing up in my follow list (despite me following them). I can search for them, however. Their game is showing up as [Unknown Game] and I can wtch the stream if I search.

Screen shot of the channel:
![image](https://cloud.githubusercontent.com/assets/204378/25785340/d4057742-3332-11e7-9a55-a3f99bb9f950.png)

**Comment by MrSprigster** [comment]
Confirmed. I am also experiencing this behavior.

**Comment by cmsimike** [comment]
People in EXBC chat are saying it is classified under 'not playing' but I tried to look for that channel but didn't see EXBC show up in it either

**Comment by anxdpanic** [comment]
https://help.twitch.tv/customer/portal/articles/2672652-irl-faq
Q: What does “Not Playing” mean? If I set my game to Not Playing, how will people find my content.
A: If none of the official categories listed in the Community Guidelines fits your stream or video, you are welcome to share by selecting Not Playing. Your followers will be able to see your stream or video, but it will not be discoverable in any of our official content categories. We plan on improving discovery around non-gaming content in 2017.

They are also not showing up on the Twitch website for me. I think it sends out live notifications via twitch for "Not Playing" streams, but does not publish them anywhere other than search. We may see this behavior change in the future. But as of now it's not available from the api.

**Comment by cmsimike** [comment]
EXBC is showing up in my following listing on the site
![image](https://cloud.githubusercontent.com/assets/204378/25785879/77095f7e-333f-11e7-9519-20d24ad0800f.png)

**Comment by anxdpanic** [comment]
Thanks, they are for me now too. Strange, will check into it more 👍

**Comment by anxdpanic** [comment]
Assuming I got old cache from twitch in add-on and website after following them. They show up via the api call now, and blacklist was inadvertently filtering them. Should be fixed with #296
