### ISSUE TITLE
Twitch live channels not updating after Kodi has been idle for a time

### ISSUE THREAD

**Issue by Baerht** [anxdpanic/plugin.video.twitch#293]
Ive noticed that if I have left Kodi idle for a while. When I start the addon it shows the popup saying twitch cashe being updated but when I go to 'live streames' all is shown is the streams that were live before I went afk. I have found that I have to exsit the add-on -> exist kodi -> go to the App page of the tvbox -> select Kodi -> clear the app cashe -> stop Kodi -> exist to main menu and restart Kodi. At this point I can restart the Add-on -> Following Live Channels. Now the current live streamers show up. I am used the latest build 2.0.0. Other then this hiccup the add-on runs good.

**Comment by anxdpanic** [comment]
Not sure which cache pop up you would be seeing, the only time the add-on should notify of cache is when you clear it via settings. Our cache is only valid for 3 minutes(default) and will be overwritten. I leave idle overnight and use the context menu to refresh the list in the morning without issue pretty every day.

If you can provide a debug log, I will definitely take a look.

**Comment by Baerht** [comment]
sry for not getting back to you. I seem to have fixed the issue if I turn the' Automatic refresh live preview cashe' interval down to below 5 min
