### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by crowly0** [anxdpanic/plugin.video.twitch#294]
Past broadcasts and video highlight list has a strange sort order or isn't sorted, would be nice if it was sorted by newest date / last broadcast first or that we could select how the list is sorted. 

"Sort by" i grayed out, or doesn't exist depending on the skin, in view options menu, and toggling "Sort: Decending/Ascending" doesn't change anything.

**Comment by anxdpanic** [comment]
Will get Kodi list/page sorting added. The full result sorting should be available by right clicking (context menu) of the Past Broadcasts folder.

**Comment by anxdpanic** [comment]
#295 adds Kodi's sort methods
