### ISSUE TITLE
Search input box reappears upon going up from search results

### ISSUE THREAD

**Issue by grocal** [anxdpanic/plugin.video.twitch#297]
Steps to reproduce (tested on 2.0 official build and Kodi 17.1 fresh install of both):

- Run Kodi, go to Twitch addon
- Navigate to Search and hit enter
- Navigate to Channels and hit enter
- Input box shows up. Type search query, for example _dexbonus_ 
- Results list shows up
- Navigate to "up folder" entry (two dots: **_.._**) and hit enter

**Result**: Search input box shows up again

**Expected**: No search input box should show up only the list of searching categories

**Comment by anxdpanic** [comment]
That's the expected behavior, in the future cached searches may also be at that '..' level of search.

**Comment by grocal** [comment]
Can you explain more why it's expected? I'm navigating back a level up from search results. Why am I asked to enter search query? I'm not - as a user - trying to search anything any more just go back from my results. I was seriously puzzled when I stumbled upon this functionality and for me it felt clearly as a bug of some sort.

**Comment by anxdpanic** [comment]
The prompt for search is on its own level, which is was intended to be a level of 'new' + cached results in the future. Also allows Kodi or the user to refresh the search results without prompt again, and external add-ons/skins/favs to call search. As a user I expect either behavior, I may want to re-search for different or miss-typed request in this case. I can look to have it bypassed, if it can be managed without breaking those functions.
