### ISSUE TITLE
REGRESSION: Favorited games list truncates

### ISSUE THREAD

**Issue by tofof** [anxdpanic/plugin.video.twitch#298]
REGRESSION: Favorited games list truncates after some arbitrary number of games, failing to offer 'next page'. 

I can't get to the listings for any of my favorited games that start with e...z.  
Haven't counted precisely, but it's around 25 (two-ish screens that are 13ish lines long in my theme).

Related: The 'displayed items per page' setting (changed to 100) doesn't change the number of displayed items in this section, though works elsewhere.

**Comment by anxdpanic** [comment]
Mine isn't truncating. Have you tried resetting cache or checking since (3min should be default cache timeout), if not can you provide a debug log?

**Comment by tofof** [comment]
Further information:
- It truncates at **exactly 25** items. 
- To be clear, this is "followed games" not "browse games". 
- I had the "items per page" on the default of 25 when I first noticed the problem - I tried changing it (to 100) in response, with no luck.
<br>

Today's attempts, per your instructions:
1. Cleared function cache using addon's cache tab, no change.
2. Tried setting items per page to 70. No change.
3. Set items per page back to 100. No change.
 ---attached log begins---
4. Restarted kodi, no change.
5. Cleared both live preview cache and function cache, no change. 
6. Tried "followed games" from both main menu and from within "following" submenu, no change.
7. Shutdown kodi
---attached log ends---  
[kodi.old.log.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/985269/kodi.old.log.txt)
<br>

And then with full debugging logging on:
1. Restarted kodi.
2. Tried "followed games" from main menu and within following submenu.
3. Iterated through available views, all truncate at 25 items.
4. Cleared live preview cache and function cache.
5. Tried "followed games" from main menu and within following submenu.
6. Iterated through available views, all truncate at 25 items.
[kodi.log.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/985296/kodi.log.txt)

**Comment by anxdpanic** [comment]
Thank you, should be all set with #300 , this also requires MrSprigster/script.module.python.twitch@b40ebd69e2ca47bb01d636383b2fc5476a2ea2ab
