### ISSUE TITLE
REGRESSION: No more 'media info' view/information

### ISSUE THREAD

**Issue by tofof** [anxdpanic/plugin.video.twitch#299]
REGRESSION: Prior version of the plugin supported 'media info' in the 'view as' choices; new version only has 'list', 'big list', and 'thumbnail'.

This is definitely a feature loss: Media info used to display information including language, viewer count, and whether the mature flag is set. These are basically unavailable now.

Admittedly you can clutter the title with the viewer count if you like, an option that already existed in prior versions too.
You can't view language of streams anymore without it (you can filter them, but not view). 
There's no way at all to view the value of the mature flag.

**Comment by anxdpanic** [comment]
These are visible in Widelist in Estuary, and made available via Plot. This regression is at the requirement of the official repository. These are 'videos', not 'tv shows' or 'movies' and these are the views we get for videos. If the information isn't available in your favorite skin you will have to speak with them about adding that view for 'videos'.
