### ISSUE TITLE
API calls and video urls failing

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#301]
Hi,

Before I get too deep into this, I want to be clear that I understand that Twitch on Kodi does not deal with videos at all however I do not believe it is a video playing problem or a problem with my network.

For about a week or so now, streams will fail playing after a certain amount of time (ill be watching and suddenly it lags out) and the same will happen for API cals. Here is some logs about it:

```
07:45:41.850 T:139838430897920  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'channel_id': '67852884', 'name': 'exbc'}|
07:45:42.670 T:139839106574720  NOTICE: VideoPlayer: Opening: https://video-edge-c2b5c8.lax03.hls.ttvnw.net/v0/CtgBYpTvqgrwj1fpqgdJAqsX8kpaKj1syDsRxFhR0bB7KS2A7GmRbEeaOoA4UHROsWr7anDl9YrtIRkaTZVnVQcZ07cefk8V83C37Ly3fBRJanKr-oig6ctjk2i5ep_quOvzwCJxuvj-BV55q36rt4wNIv3tZd8utVcN_W9NMJLoXNuMdyyqSTxjWakRspBzQ3hK-XcH77vFCnlDzzlcLQz9EPoV5w-cLg4exMkGxcgyZGr_IEA1MvBHAoTxsPSJq6uXC6Nvmd59bdZZHuuZeuamp_bp-4-8-JZfEhA2KERSc9qitz8LR-cwxBzlGgyIR2YTx9LSqx-nrCE/index-live.m3u8
07:45:42.671 T:139839106574720 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
07:45:42.674 T:139835973019392  NOTICE: Creating InputStream
07:45:42.854 T:139835973019392  NOTICE: Creating Demuxer
07:45:43.424 T:139835973019392  NOTICE: Opening stream: 1 source: 256
07:45:43.424 T:139835973019392  NOTICE: Creating video codec with codec id: 28
07:45:43.424 T:139835973019392  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
07:45:43.425 T:139835973019392  NOTICE: Creating video thread
07:45:43.425 T:139838430897920  NOTICE: running thread: video_thread
07:45:43.425 T:139835973019392  NOTICE: Opening stream: 0 source: 256
07:45:43.425 T:139835973019392  NOTICE: Finding audio codec for: 86018
07:45:43.427 T:139835973019392  NOTICE: Creating audio thread
07:45:43.427 T:139837340374784  NOTICE: running thread: CVideoPlayerAudio::Process()
07:45:43.428 T:139838430897920  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating VDPAU(1920x1080)
07:45:43.428 T:139838430897920  NOTICE: VDPAU::Open: required extension GL_NV_vdpau_interop not found
07:45:43.428 T:139838430897920  NOTICE:  (VDPAU) Close
07:45:43.437 T:139835668190976  NOTICE: COutput::OnStartup: Output Thread created
07:45:43.437 T:139837340374784  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
07:45:43.709 T:139839106574720  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
07:45:43.743 T:139839106574720  NOTICE: GL: NPOT texture support detected
07:45:43.743 T:139839106574720  NOTICE: GL: Using GL_ARB_pixel_buffer_object
07:45:43.743 T:139839106574720  NOTICE: Using GL_TEXTURE_2D
07:45:43.744 T:139839106574720  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
07:45:43.754 T:139839106574720  NOTICE: GL: NPOT texture support detected
07:45:43.754 T:139839106574720  NOTICE: GL: Using GL_ARB_pixel_buffer_object
07:45:45.652 T:139838430897920 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
07:45:46.154 T:139838430897920 WARNING: Previous line repeats 1 times.
07:45:46.155 T:139838430897920  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 16636
07:45:46.656 T:139838430897920 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

.....
07:46:03.749 T:139837608810240 WARNING: CPythonInvoker(0, /home/mike/.kodi/addons/plugin.video.twitch/resources/lib/service.py): the python script "/home/mike/.kodi/addons/plugin.video.twitch/resources/lib/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE
07:46:04.186 T:139838430897920 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
07:46:08.681 T:139837348767488 WARNING: Previous line repeats 2 times.
07:46:08.681 T:139837348767488   ERROR: CPythonInvoker(11, /home/mike/.kodi/addons/plugin.video.twitch/resources/lib/routes.py): script didn't stop in 5 seconds - let's kill it
07:46:10.963 T:139837340374784  NOTICE: CVideoPlayerAudio::Process - stream stalled
```

Here is what I find interesting:

loaded url:
Opening: https://video-edge-c2b5c8.lax03.hls.ttvnw.net/v0/CtgBYpTvqgrwj1fpqgdJAqsX8kpaKj1syDsRxFhR0bB7KS2A7GmRbEeaOoA4UHROsWr7anDl9YrtIRkaTZVnVQcZ07cefk8V83C37Ly3fBRJanKr-oig6ctjk2i5ep_quOvzwCJxuvj-BV55q36rt4wNIv3tZd8utVcN_W9NMJLoXNuMdyyqSTxjWakRspBzQ3hK-XcH77vFCnlDzzlcLQz9EPoV5w-cLg4exMkGxcgyZGr_IEA1MvBHAoTxsPSJq6uXC6Nvmd59bdZZHuuZeuamp_bp-4-8-JZfEhA2KERSc9qitz8LR-cwxBzlGgyIR2YTx9LSqx-nrCE/index-live.m3u8

timeout waiting for buffer:
07:45:46.656 T:139838430897920 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

other script failures:
/home/mike/.kodi/addons/plugin.video.twitch/resources/lib/routes.py): script didn't stop in 5 seconds - let's kill it

I have also seen failures in other api calls, like loading followed channels.

I have tried the video url being loaded in many other players (VLC) on different machines, and the stream also fails while trying to play it there after a few minutes.

Now here's the interesting part - other Twitch clients on my network play fine! Testing vid Apple TV, and multiple browsers on different computers.

I guess my first question is whether or not anyone else is seeing this? The issues seem specific to the api calls and urls generated by the plugin, and I know recently v2 of the plugin was released using a newer version of the api. Maybe the problem is on twitch's end? Though seems a bit unlikely given how long this has been going on.

**Comment by anxdpanic** [comment]
I don't see anything there to suggest add-on/Kodi in that snippet, and haven't experienced any twitch side issues recently. 

The video portion of twitch's api is unsupported and doesn't track with their api versions. They are returning you that url and it's timing out simply. Either their end, isp-aws or network/environment related to that device. If you try choose quality and choose the lowest available will the failing stream then load?

API timeouts/failures could be caused by the same issue.

**Comment by cmsimike** [comment]
The lower bandwidth versions seem to have the same issue, meaning it starts playing for a bit then stops or the player can't continue playing correctly (pausing then speeding up then pausing).

Anyway, thanks! That is what I suspected. Everything I've seen seems to _suggest_ an issue on Twitch's side but it's mind blogging how some clients can work well and the URLs generated this way just don't.

**Comment by cmsimike** [comment]
Looking into it a bit further, the URLs being loaded via twitch.com are:
https://video-edge-c2b5c8.lax03.hls.ttvnw.net/v1/playlist/CpwCfGCD0e2eJC6pqyQ9v-e6ezUxx6adk_SFoxmBkRyPnRaOh1JaDuOTsK_vkZGsj0F6LBE6wW-yD0OITn_8rI_x3NDzS6DXlpbPbGqdWELhQVxky1ue5Ukh8fh1T7oF5y7B99psbogmNc4TKM5vmVv1n3GXb58Vcp-t6oOlrDntJpWOeqMZOJ4gOJgH-vpmAlAd4sCo5IApHixkmB5sdObJmzuic_9kxQ_54V-s6tJmybIuFFhDWMLaWQW2y0ye0K3d_aTLbesTV_6t8oQigTODRdu8JwPJyj6l2Q15HWyzsGzAguUr-ISipAMojcVDP9xhWRYNpCEAZtOnEx1VNgTFeBM2zXjByAjsg3Brp5yyModAtvk_ZPWaPMN8088SEDsK5D1cXnmtozGa26GnCeEaDLIsnXDSeR8a3bl8-Q.m3u8

Not sure it makes a whole lot of difference (notably the /v1/ vs /v0/ path) or the playlist path (maybe i am looking at the hls segments?) but I thought I'd throw it out there.

**Comment by anxdpanic** [comment]
If they are starting and you experience that, it could also be ffmepg related. If you enable debug logging and component logging for ffmpeg, you can see more clearly if ffmpeg is getting/dumping or not getting anything at all. Still would be nothing on our end we could do, but may narrow it down for you.

Yea, we parse the original m3u8 for the those m3u8s, and pass the one provided by the chosen quality.

**Comment by cmsimike** [comment]
I am closing this for now. It definitely isn't plugin-specific, but I don't understand why the same url would play fine in browser but fail in VLC (same computer).
