### ISSUE TITLE
How to use the old playLive route with v2?

### ISSUE THREAD

**Issue by dnn1s** [anxdpanic/plugin.video.twitch#303]
Hi there,

in previous versions, you were able to use JSON-RPC and send a plugin://plugin.video.twitch/playLive/streamername/quality to Kodi to start playing a certain stream. I used this in a web app that makes controlling Kodi easier for my girlfriend (you know, WAF and stuff ;-) ).

This doesn't work anymore in v2. What's the new format? Browsing through the source code, I couldn't find any explicit hints like in 1.4.5.

Until v2, I sent this over an established web socket connection:

```
{
"jsonrpc":"2.0",
"method":"Player.Open",
"id":"Player.Open",
"params":{
   "item":{
      "file":"plugin://plugin.video.twitch/playLive/joshog/-2/"
      }
   }
}`

**Comment by anxdpanic** [comment]
the params for playing;
videos are { mode: play, video_id: <video_id> }
streams are { mode: play, name: <channel_name>, channel_id: <channel_id> }
clips are { mode: play, slug: <clip_slug>, channel_id: <channel_id> }
optional parameter for playback are { ask: true, player: true }, ask will force asking for quality, and player will use Kodi Player() instead of setResolvedUrl which can be useful from certain contexts.

**Comment by anxdpanic** [comment]
if you don't know the ID's required, you can create a favorite to their stream/channel and check the favorites.xml to see the url needed, or open their stream/channel and view the log.

**Comment by dnn1s** [comment]
@anxdpanic 
Which method should the parameters be passed to? Could you please provide a full example? :)

**Comment by anxdpanic** [comment]
plugin://plugin.video.twitch/?mode=play&channel_id=26610234&name=cohhcarnage

**Comment by xevz** [comment]
@anxdpanic 
Couldn't the play method just extract the channel ID if it's not provided, like before? Now browser extensions and other similar stuff need their own API access for something that the Kodi plugin can lookup just fine.

**Comment by anxdpanic** [comment]
Actually the other way around is what should have been done in the first place, and oversight by me. Channel names are no longer reliable as Twitch APIv5 relies on id's with the inclusion of name changes.

I have simplified the PLAY route a bit, now only channel_id is required for live, video_id for vods, and slug for clips. 

Channel id's can be obtained by extensions without api access, there was at least one that made the appropriate changes during testing. If you require it for reference let me know and I will dig it up for you.

**Comment by xevz** [comment]
Oh, if you can find it, that would really help. :)

**Comment by anxdpanic** [comment]
Sorry about the delay, found it:
https://github.com/khloke/play-to-xbmc-chrome/commit/e70d756367292a32a07ef5e3ce493ae0d144d7ba
