### ISSUE TITLE
Cant see the link to get the oauth token

### ISSUE THREAD

**Issue by Tzelios** [anxdpanic/plugin.video.twitch#308]
I did what u say: "The prompted url is case-sensitive, if your skin's text is all UPPERCASE you will need to switch to Estuary/Confluence to see the proper url", i tried to change a lot of themes but the problem remains. I can see this so far "https://api.twich.tv/kraken/oauth2/authorize?state=redirect_uri...".

**Comment by anxdpanic** [comment]
Have you been able to get a goo.gl link yet?

**Comment by Tzelios** [comment]
I guess that's a sort link? I did not get it yet. But is this link for everyone the same right? So why is not posted publicly here?

**Comment by anxdpanic** [comment]
This should work for you. https://goo.gl/arFEqk

edit: K to lowercase

**Comment by Tzelios** [comment]
i took the OAuth Token but this time i take an error: <<Connection Faild, failed to connect to Twitch API>>

**Comment by anxdpanic** [comment]
With the issue getting the shortUrl(request failing to google) and the connection failed(request failing to twitch api), it sounds like network issues. If you post a link to a full debug log, can take a look.

**Comment by Tzelios** [comment]
https://www.dropbox.com/s/u747bzm1j8id5qv/kodi.log?dl=0

**Comment by anxdpanic** [comment]
That pretty much shows the same thing, can't connect to the url. What happens if you open https://api.twitch.tv/kraken/ in browser? should be '{"error":"Bad Request","status":400,"message":"No client id specified"}' and does a youtube video work? Enabling debugging and re-running -might- add more to the picture. 

Right now it looks like add-on is doing what it is supposed to but can't connect due to something else.

**Comment by Tzelios** [comment]
Yes it shows "{"error":"Bad Request","status":400,"message":"No client id specified"}". When i press the sign in Youtube says "You must enable two applications so that YouTube is functioning properly", let me upload it again this time with YouTube error.
https://www.dropbox.com/s/u747bzm1j8id5qv/kodi.log?dl=0

**Comment by anxdpanic** [comment]
Looks like something happened with your installation. script.module.requests is missing parts it seems.
Installing this from zip will resolve the import error with the other addon. http://mirrors.kodi.tv/addons/krypton/script.module.beautifulsoup/script.module.beautifulsoup-3.2.1.zip

And re-installing http://mirrors.kodi.tv/addons/krypton/script.module.requests/script.module.requests-2.12.4.zip should hopefully resolve the issue with requests. (youtube and twitch add-ons both rely on it.)

If that doesn't resolve it for you, I'd suggest backing up and starting fresh.

**Comment by Tzelios** [comment]
Thank you very much.....that was the solution...... thanks for your time.
