### ISSUE TITLE
Channel with game type None, not displaying on Live channels

### ISSUE THREAD

**Issue by phantom-voltage** [anxdpanic/plugin.video.twitch#309]
This may be related to #292, since the channel in question was streaming without a game selected. As far as I can tell, there is no community associated with this channel, either.

Could not view the live channel, nor the previous broadcasts in the Kodi Twitch TV add-on. 

The channel doesn't show up in Following > Live Channels.
Past broadcasts, uploads, clips, result in no items found when in Following > Channels > Channel_Name

The channel in question was https://www.twitch.tv/ptychomancer. 

![2017-05-25-131704_1280x800_scrot-cropped](https://cloud.githubusercontent.com/assets/12504384/26468966/3e553f74-414d-11e7-9ad6-474531a8cc10.png)

In the log, it looks like game=None.

Version: 2.0.0
Log snippet attached:
[gistfile1.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/1030160/gistfile1.txt)

**Comment by anxdpanic** [comment]
Have you tried updating to latest master from https://github.com/MrSprigster/script.module.python.twitch and here as well? This should be resolved there

**Comment by phantom-voltage** [comment]
Yes, I thought the latest master would have fixed it as well. I manually deleted the old script.module.python.twitch, and reinstalled the Twitch plugin as well as the script.module.python.twitch. It now works.

Thank you very much.
