### ISSUE TITLE
[Feature Request] Hide VodCast

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#312]
Hi,

Is it possible to detect which followed channels are live vs playing a vod? Seems to be a new twitch "feature" where a stream can play an already-recorded vod. It would be nice to have an option to hide these!

**Comment by anxdpanic** [comment]
Waiting to confirm if it's staying this way or if it will be changed. Seems strange that vodcasts are returning on stream_type=live instead of stream_type=playlist. 

Currently the api for vodcasts returns :
'broadcast_platform': 'playlist',
 'is_playlist': False,
 'stream_type': 'watch_party'

**Comment by cmsimike** [comment]
Thanks!!

**Comment by anxdpanic** [comment]
So far no movement here. Since vodcast is not _just_ used as a playlist substitution I'm leaning more towards color highlight instead of hiding. thoughts?

**Comment by anxdpanic** [comment]
added colorized version to master, if you'd like you try it out

**Comment by cmsimike** [comment]
Thanks - I am a bit late on this (been afk). My preference would be for an option to hide those in the settings, but colorization might be fine. As long as I can train my eye to skip the non-live feeds, I think I'll be happy.

**Comment by anxdpanic** [comment]
I'm not a fan of seeing the 'live playlist' use case, the issue I see with a hard hide of all of them is we'll miss out on the other use cases. Original/first time recorded content viewed live with viewers, prerecorded preshows etc. 

String filtering of titles might alleviate some of this as well in the future.
