### ISSUE TITLE
Past Broadcasts

### ISSUE THREAD

**Issue by Chris0706** [anxdpanic/plugin.video.twitch#313]
Hey, 

I dont think Past Broadcast Option for Abos isnt working properly. It doesnt show the most recent ones and I cant even find them.. Sorting is also really weird. Am I doing something wrong?

**Comment by anxdpanic** [comment]
For sorting, https://forum.kodi.tv/showthread.php?tid=134538&pid=2587058#pid2587058

Not sure who Abos is, https://www.twitch.tv/abos ?

**Comment by Chris0706** [comment]
Sorry i ment followed channels (Abonnements)

**Comment by Chris0706** [comment]
The kodi sorting is not helpful at all. The Broadcast are really mixed up and you cant find any Broadcasts belonging together in one Page.. I just want it like in the old App.. Historic listing of past Broadcasts from the latest to last..

**Comment by anxdpanic** [comment]
The link I posted is showing using the context menu on Past Broadcasts to change the add-ons/api sort method. Kodi's builtin sorting applies only per page.

**Comment by Chris0706** [comment]
Yeah I understood that. But the sorting mechanism doenst help at all for this kind of menu.. 
You just want to see the latest Broadcast a Streamer had.. But when you open the Menu it's not sorted at all, completly mixed up. So using context menu sorting doesnt bring you forward in finding the latest stream..

**Comment by anxdpanic** [comment]
The 'Change sort by' context menu item of the 'Past Broadcasts' folder choose 'Time', it is sorted by 'Views' by default. Time will sort last broadcast to first broadcast

**Comment by Chris0706** [comment]
http://imgur.com/a/Qc1bS

Look here. That's what I get when I open Past Broadcast.. They are like 1 to 3 months in the past and not following any order.. 

In old Version the first Page showed the latest Broadcast instead..

**Comment by anxdpanic** [comment]
Just tested changing sort by from the context menu, and all working fine here. If the previous instructions on how to change the sorting to Time doesn't work for you, please provide a debug log.

**Comment by Chris0706** [comment]
Are we talking about the same menu? http://imgur.com/a/rnvAE

It's not showing me change sort by only the order..

**Comment by Chris0706** [comment]
http://imgur.com/a/eehtU

Thats the only other menu I find.. And it hasn't the option either

**Comment by anxdpanic** [comment]
https://forum.kodi.tv/showthread.php?tid=134538&pid=2587058#pid2587058 <- right click on past broadcasts like in that screenshot

**Comment by Chris0706** [comment]
Okay sorry for the trouble *facepalm*

But to be honest it's not the most intuitively position..

**Comment by anxdpanic** [comment]
No trouble and thanks for the feedback, will keep that in mind for future. 👍  Also the default has already been changed to Time in the master branch, just not in the official release yet.
