### ISSUE TITLE
Failed to connect to Twitch API

### ISSUE THREAD

**Issue by lcvass** [anxdpanic/plugin.video.twitch#316]
Started happening recently, error shows up on start or in get get OAuth token. LibreELEC 7.90, Rpi3. Downloaded from kodi repository.

**Comment by anxdpanic** [comment]
It's been working consistently for myself, so we're going to require further information to help. Please provide a link to a [debug log](http://kodi.wiki/view/Log_file).

**Comment by anxdpanic** [comment]
Looks like there was also a site wide issue approximately the same time this was posted and has since been resolved. Are you able to confirm if this is now resolved for you?

**Comment by lcvass** [comment]
It's fixed! Thanks.
