### ISSUE TITLE
Error watching some streams

### ISSUE THREAD

**Issue by podbiker** [anxdpanic/plugin.video.twitch#32]
First of all, thanks for the great work with this plug-in. It is a great pleasure for me to finally watch my favourite streams on the b ig screen. Unfortunately I ran into a problem I could not resolve.

When I try to view the channel of taketv the error below shows up in the xmbc log. It seems that only some streams are affected while others play just fine.

I am using the latest raspbmc with the twitch (v1.0) plug-in from the xbmc-repository.

In order to try and deal with the problem I already updated librtmp to the latest available version.

Unfortunately the problem was not resolved by this step.

---

20:25:20 T:2869949504  NOTICE: [xbmcswift2] Request for "/playLive/taketv/" matches rule for function "playLive"
20:25:20 T:2869949504 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
20:25:21 T:2869949504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'token'
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 187, in <module>
                                                PLUGIN.run()
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/pi/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(*_items)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 21, in wrapper
                                                return func(_args, **kwargs)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/default.py", line 141, in playLive
                                                rtmpUrl = resolver.getRTMPUrl(name, videoQuality)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/twitch.py", line 113, in getRTMPUrl
                                                if self._streamIsAccessible(stream)
                                              File "/home/pi/.xbmc/addons/plugin.video.twitch/twitch.py", line 131, in _streamIsAccessible
                                                if not stream[Keys.TOKEN] and re.match(Patterns.IP, stream.get(Keys.CONNECT)):
                                            KeyError: 'token'
                                            -->End of Python script error report<--
20:25:21 T:3041087488   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/taketv/]
20:25:21 T:2869949504  NOTICE: Thread Background Loader start, auto delete: false

**Comment by TUDOFuchs** [comment]
same here.

**Comment by ccaspers** [comment]
Yep we'll hopefully be able to push a new release within the next few days.

**Comment by podbiker** [comment]
Good to hear.

I had some success in the meantime.

I tried the last version from Middlle, which he posted in the twitch thread on the xbmc forums. It works with the above stream.

Perhaps that helps with the sollution.

If you need testing on raspbmc, let me know, I'm happy to help.

**Comment by StateOfTheArt89** [comment]
Should be fixed with: 35ac843fbf4c97c700db79d3266bd1474c8a4253

**Comment by lordthumper** [comment]
Hi,

Thanks alot for the update, it works on latest Raspbmc.

Once an error occured "User Token Error". Here's the log snapshot:

02:51:03 T:2925524032  NOTICE: -->Python Interpreter Initialized<--
02:51:04 T:2925524032  NOTICE: [xbmcswift2] Request for "/createListOfGames/0/" matches rule for function "createListOfGames"
02:51:06 T:2933912640  NOTICE: Thread Background Loader start, auto delete: false
02:51:08 T:2933912640  NOTICE: Thread XBPyThread start, auto delete: false
02:51:09 T:2933912640  NOTICE: -->Python Interpreter Initialized<--
02:51:11 T:2933912640  NOTICE: [xbmcswift2] Request for "/createListForGame/League+of+Legends/0/" matches rule for function "createListForGame"
02:51:13 T:2933912640 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
02:51:14 T:2925524032 WARNING: Previous line repeats 19 times.
02:51:14 T:2925524032  NOTICE: Thread Background Loader start, auto delete: false
02:51:16 T:2925524032  NOTICE: Thread XBPyThread start, auto delete: false
02:51:16 T:2925524032  NOTICE: -->Python Interpreter Initialized<--
02:51:16 T:2925524032  NOTICE: [xbmcswift2] Request for "/playLive/mlglol/" matches rule for function "playLive"
02:51:16 T:2925524032 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
02:51:17 T:3041484800   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/mlglol/]
02:51:17 T:2933912640  NOTICE: Thread Background Loader start, auto delete: false
02:51:23 T:2933912640  NOTICE: Thread XBPyThread start, auto delete: false
02:51:23 T:2933912640  NOTICE: -->Python Interpreter Initialized<--
02:51:24 T:2933912640  NOTICE: [xbmcswift2] Request for "/playLive/mlglol/" matches rule for function "playLive"
02:51:24 T:2933912640 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
02:51:26 T:3041484800  NOTICE: COMXPlayer: Opening: rtmp://justintvlivefs.fplive.net/justintv2live-live/stream_720p_user_mlglol swfUrl=http://www-cdn.jtvnw.net/widgets/live_embed_player.rba44673091039dd7a2493939d027fcdaf5aa465f.swf?channel=mlglol&referer=http://www.leagueoflegendsstreams.com/home/showstream.php&userAgent=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/28.0.1500.63%20Safari/537.36&channel=mlglol swfVfy=1  jtv=a7cf0bb7bd59428b7c566d5cc3aa38025738054d:{\22swfDomains\22:\20[\22justin.tv\22,\20\22jtvx.com\22,\20\22xarth.com\22,\20\22twitchtv.com\22,\20\22twitch.tv\22,\20\22newjtv.com\22,\20\22jtvnw.net\22,\20\22wdtinc.com\22,\20\22imapweather.com\22,\20\22facebook.com\22,\20\22starcrafting.com\22],\20\22streamName\22:\20\22stream_720p_user_mlglol\22,\20\22expiration\22:\201372557085,\20\22server\22:\20\22l3\22} live=1
02:51:26 T:3041484800 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
02:51:26 T:2933912640  NOTICE: Thread COMXPlayer start, auto delete: false
02:51:26 T:2933912640  NOTICE: Creating InputStream
02:51:27 T:2933912640   ERROR: rtmp server sent error
02:51:27 T:2933912640  NOTICE: Creating Demuxer
