### ISSUE TITLE
Authentication failed, Error 401

### ISSUE THREAD

**Issue by niel** [anxdpanic/plugin.video.twitch#322]
I've started seeing this again today. Looks like issue #318 again.

**Comment by anxdpanic** [comment]
I cannot reproduce, try clearing function cache. If still an issue, please advise how to reproduce and/or provide a debug log.

**Comment by MrSprigster** [comment]
No issues here either

**Comment by niel** [comment]
Weird. Today it's working again, nothing else has changed it just works.
Apologies for the noise.
