### ISSUE TITLE
[Feature Request] Use channel logo as notification icon for live notifications 

### ISSUE THREAD

**Issue by miawgogo** [anxdpanic/plugin.video.twitch#331]
Currently Twitch-on-Kodi used the Plugin Icon for live notifications due to it not passing a icon to the notify function. It would be nice when a channel comes online the channels logo/avatar is used in the notification as it makes it easier to see who went online at a glance.

**Comment by anxdpanic** [comment]
hah, I am actually just testing this now locally. The startup notifications will remain the same if more than 3 online, but all other notifications will include logo and their current game as well as notify on game changes. Looks very similar to the twitch app toast.

**Comment by anxdpanic** [comment]
I've updated the alpha zip @ https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.1.0-alpha if you'd like to try it out.
