### ISSUE TITLE
channel always asks me to pick a quality

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#335]
Hi,

The twitch channel, kitboga, always prompts me to pick a quality whenever I tune in. No other twitch channel I watch does this.
Currently my video quality in the settings is set to Source. There seems to be no source option in the prompt I receive.

**Comment by anxdpanic** [comment]
I've added to my following so I can hopefully catch online tomorrow, to see if no source quality is in error or not. Looks like next stream is scheduled for Thurs 9pm. 

Default qualities are per stream, so you can use context menu and choose a default quality for that particular stream to stop the pop up in the mean time.

**Comment by rh4m** [comment]
I have the same issue on that channel(kodi 17.3)

**Comment by anxdpanic** [comment]
@rh4m with the same channel? only a single stream doing it? which quality do you have set?

**Comment by anxdpanic** [comment]
@cmsimike It looks like Source is behind channel sub restriction. Do you happen to have a sub and can you see source via website?

**Comment by rh4m** [comment]
@anxdpanic at the same channel, but this afternoon at some chinese channel as well(was exploring and didn't read your question yet, so I haven't written the name down). Video quality is set to source here.

**Comment by cmsimike** [comment]
@anxdpanic gotcha, confirmed. thank you very much for looking into this.
