### ISSUE TITLE
twicht framedrop and streams close after a few minutes

### ISSUE THREAD

**Issue by rh4m** [anxdpanic/plugin.video.twitch#338]
After a kodi update yesterday (pi 2b build 17.3) twitch streams have a lot of framedrop and after a few minutes the stream closes completely. When I reopen a stream, the same happens and I can watch up to 5 or 6 minutes before it closes again.

To exclude as many factors on my side, I have done a totally clean instal of kodi, i have reset router and such, changed network cables all to find out the problem still exists and don't appear on my tablet when I'm watching the same stream on my tablet as well.

I did find the following errors in the log viewer for Kodi from the time the problem occured, but I'm too inexperienced to know what they mean:

22:33:46.774 T1534063600 ERROR: Got MSGQ_ABORT or MSGQ_IS_ERROR return true
22:33:46.774 T1534063600 NOTICE: thread end: video_thread
22:33:46.774 T1418720240 NOTICE: waiting for video thread to exit
22:33:46.774 T1418720240 NOTICE: deleting video codec
22:33:46.874 T1959092224 ERROR: Control 500 in window 10025 has been asked to focus, but it can't

I hope this information is enough to fix, cause I have been a very satisfied user of your add-on for quite a few years and hope I can keep using it for many more.

Thanks in advance

**Comment by anxdpanic** [comment]
Most cases this is out of our hands, you can post a [debug log](http://kodi.wiki/view/Debug_log) of you reproducing the issue and we can take a look. 

Outside of that, I would update to 17.4 if possible. With an updated inputstream.adaptive(2.0.10+) you could try out the latest alphas with inputstream.adaptive enabled.
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.1.0-alpha

**Comment by rh4m** [comment]
I played around a bit and noticed that when i had a framedrop, if I quickly paused and then played the stream, it would continue normally(until next framedrop or until the stream would stop by itself).

To make it even weirder, last friday, as sudden as tbe issue had apeared a few days before, it disappeared again out off the blue(no reboots or changes in setup all).
In my research I did read about other people having simulair issues come and go as in my case.

Since for me this issue is "magically gone", if up to me you can close this issue.
I hope if ever needed this info will help you to solve future issues.

Thanks in advance!

**Comment by anxdpanic** [comment]
Going to close, with link to other currently open issue #307
