### ISSUE TITLE
Difficulty logging in on AlexELEC because no Web browser

### ISSUE THREAD

**Issue by fragmental** [anxdpanic/plugin.video.twitch#342]
I'm using AlexELEC(which I believe is based on LibreELEC) on an android box with an am logic s805.  I'm trying to log into the twitch add on but it gives me a link that I can neither copy, nor select.  I don't think a Web browser is available for this combination of hardware and software.  There is a Web viewer add on but it doesn't work very well.

**Comment by anxdpanic** [comment]
That is expected, it should be a goo.gl shortened url. Visit that url in browser on phone or pc and you will have to authorize with Twitch, and then you will receive the oauth token you need to input in the add-on settings.

**Comment by fragmental** [comment]
@anxdpanic thank you for your response.  


I typed the goo.gl url into another device, and then typed the oauth code from the other device into my android box and it worked as expected.  The oauth code was a lot of characters to manually copy, and it's not exactly an elegant solution.  But I understand how difficult this login authorization stuff can be and I appreciate the work you and the other developers have done to create this add-on, and keep it updated.
