### ISSUE TITLE
Thumbnails not refreshing

### ISSUE THREAD

**Issue by konrad-lapinski** [anxdpanic/plugin.video.twitch#343]
When I go to my favourite channels, the thumbnails don't refresh.

**Comment by anxdpanic** [comment]
If you mean favourites(add-on is not accessed to display these) those will not refresh until going in add-on to a live stream display. If you mean in Following - Live, check that it's enabled and what you have set for the time between. If not able to resolve please post a [debug log](http://kodi.wiki/view/Debug_log) reproducing the issue.

**Comment by konrad-lapinski** [comment]
Yes, so I had to turn that option on in settings. Should be on my default I think.
