### ISSUE TITLE
Default quality not Source

### ISSUE THREAD

**Issue by konrad-lapinski** [anxdpanic/plugin.video.twitch#345]
Hey. I've been having problems with your addon. It stuttered, lagged and stopped at times. I set default quality to Source by right-clicking a stream and now it doesn't stutter after 30 min of testing. Seems like default quality isn't Source by default.

**Comment by anxdpanic** [comment]
The default is Source, if you start a stream that doesn't have a Source quality it will prompt you for a quality choice. The stuttering, lagging, etc is reported in #307. 

If you feel the quality isn't being picked correctly in your case please re-open this issue with a [debug log](http://kodi.wiki/view/Debug_log) reproducing the issue.
