### ISSUE TITLE
Add capability to run stream from channel name instead of channel id

### ISSUE THREAD

**Issue by antoine-morisseau** [anxdpanic/plugin.video.twitch#348]
Hello,

i'm using the chrome plug-in Play-to-kodi in order to start a twitch stream on Kodi 
(link on the store : https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden 
and the github issue : https://github.com/khloke/play-to-xbmc-chrome/issues/126), 
but recently it don't work anymore since the Twitch add-on use a channelid in order to start a stream.

I searched a little and found that twitch offer and api that could get a channel id from its channel name 
https://dev.twitch.tv/docs/v5#translating-from-user-names-to-user-ids

[log_twitch_add_on.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/1507631/log_twitch_add_on.txt)
Here is some log from the kodi.log file  if it can help

So is it possible to add the capability of the twitch add-on to start stream from the channel name instead of channel id ?

It will allow external software to remotely use the twitch add-on more easily.

**Comment by anxdpanic** [comment]
Added to the latest alphas
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.1.0-alpha

**Comment by antoine-morisseau** [comment]
wow thank you sooooo much ! i could not dream to get a feature request, accepted and implemented so quickly ! 👍
