### ISSUE TITLE
Teams page only lists first 25

### ISSUE THREAD

**Issue by kokarn** [anxdpanic/plugin.video.twitch#35]
This is in a way related to #28 in that it doesn't paginate as it should.

The problem here is that there are more than 100 channels so just maximizing to 100 isn't a solution. 

Maybe using the _links->next to check if there are any more streams following this and maybe use that for pagination?
### EDIT

After reading throught #28 it's clear it's exactly the same, only for teams instead.

**Comment by StateOfTheArt89** [comment]
see 0393a95d974e7f0cbdc43c69b0c1fbcd40901dd1
