### ISSUE TITLE
Ridiculous amount of DNS queries

### ISSUE THREAD

**Issue by fragande** [anxdpanic/plugin.video.twitch#350]
I recently installed Pihole and I'm having trouble with the Twitch plugin quickly filling the logs on RAM drive with a ridiculous amount of DNS queries. It's making several each second similar to this one:

Dec 29 09:16:47 dnsmasq[10302]: query[A] video-weaver.arn03.hls.ttvnw.net from 192.168.1.**
Dec 29 09:16:47 dnsmasq[10302]: cached video-weaver.arn03.hls.ttvnw.net is 52.223.198.1

Is this normal behavior? If not, any idea what could be causing this? Playing the same HLS stream in VLC results in a lot less queries.

**Comment by anxdpanic** [comment]
I can't see the add-on itself causing that, that would be Kodi/ffmepg making requests to those urls. 
If I were to guess based on the little information, Kodi and Pihole are on the same system and VLC is on another. In that case, dnsmasq would be Kodi's system based cache, and the system VLC is installed on would have it's own system cache before using Pihole where needed.

More information regarding setup and a debug log showing the playback of something on your system while the issue is happening might reveal more.

**Comment by fragande** [comment]
Sorry for the lack of info. Kodi is running on a Raspberry Pi and Pihole on an OrangePi Zero so not on the same system. VLC was run from a Windows machine using livestreamer to extract the stream.

I'm not sure what debug log is relevant but the entries (which I'm guessing are making these DNS queries) in kodi.log while playing a stream looks like this:

```
16:24:57.425 T:1473766384    INFO: ffmpeg[57D7E3F0]: [hls,applehttp] Opening 'https://video-edge-c681d8.arn03.hls.ttvnw.net/v1/segment/CtgCefxcd2rHNtbvfAwh44G3Kz68rH4f8J1bKC-IT8aXlCC5N0Iuq8Dk7NueFlMgPIQAkSj4nKIZ02SG7zKC4QhDteK_1E2aMQ9uFReAJBe02T5pevYBNCMgGkvvFAfRI1x24z1Wh__0h3LcOhxiCdPu2u2lhmfGMKEC8fDZ6lWivQ8UGqW4WGI-KQ0h7FsPjSb-zCBVj5YczC75Dq86CrAdKhiRwlnf6unH_8W3osR7NqQH71RU8D6Le0Z-Sw2Z7vdL2lZ9Ntoc3u5zVlZs2lUYCEqqe-2kOCHp_689axFC3nuutdc19kTGfiT54oUvF6u_HT9OZUGAESFz1A9KPVd3nG_eK9dNe3mCsiBbitAf3ROIE-0q2JHHHx94KFnAluNm8zpMis6JuhDpMjwDnJJskSK1HbulLvx9YuepLLC7RJHP13a_ScUYgLml84s9zXiBng6fezZhEO8SEKW_GxZ7TeweKh_zPAl5BQIaDMzGb492P4c_2AbopQ.ts' for reading
16:24:57.844 T:1473766384    INFO: ffmpeg[57D7E3F0]: [hls,applehttp] Opening 'https://video-edge-c681d8.arn03.hls.ttvnw.net/v1/segment/CtgC16NaqouWYMZjznKtTjwqG0NiWezsKQKUcyyUBUCVA93bkQ6JepOaG5b2MlguNL62hoTRgSOLj-ohAgDMIFUXE_zkdN0H-COipEK8PFv10SgJkwhIQcuENY7mTQSUciRapaYvrKy4gZeD8bTs2f5Rk7ovDi2TRX03-SszIFYIsL-bKowyOcsrT2r9CtVjrrlQ7pcPk2X79Mj3xwe5YNk8LgObwYvblNmRz1SrRGbFPMQex1ICob5UumAB7hmDyEW4ib5XOGX7ZnnELywW7CFLOMVL1EcXYIP07FTvb7aWM6T7yfJlxAuqvpLMyu_xVlzua6A1pRKQYMPocyrAGIyTGzB-HC0VOTy7JZxmfoHsqwDtWFAwLtp3m8L_dGSvrInQ0ms-A6lIPJ4jkVzLYTSS0HfRw2BrV0CNRuW1kX4EYYMjAYcdmLzkzDU_1SR0MGedvkT9WhLkfdgSEEZ92qK0eWSDnw7Ctn9sRKYaDGLSacYDzLn_zR8tFQ.ts' for reading
16:24:59.694 T:1473766384    INFO: ffmpeg[57D7E3F0]: [hls,applehttp] Opening 'https://video-edge-c681d8.arn03.hls.ttvnw.net/v1/segment/CtgCEz89noo0hdBT0fbv-itc_JnDq9DW1sLlRSKVMRzdWs4rWQQRa5BgkFAuh6ta9L93txsl2G19nDk2iK8aNI_fE0kLMt3wpHsVHhv3k0fUc-1BsYLtVaLRTgHFb7e1EsZg1fkVNrTG9vgaGVhAiLSDBHIq4mwSJbfEnKQ6LA1w-subjp5L70kY9G6kInZNwCAz7phpiHuNCCnahmPqotnUxZVGHdkqnRz68me_0yMiDvoiAEApK351C81t9mnurlzXX6qJaBTdOIgK7jiXYnUiLwMPYixNLTpZmHtySJ8oK2BSH3w8k9iTLKJit8P0Bg1ZwcAYU_v5NIadVpj9zfgNvl73q2TMOsbU-j-3oHCwpR95-EFh5s0-xoQ7vtQsKMGM7woILzY48oAE5-cgjP9Our0M54Wa6lJXxCWz7-8KwUxjzNfXfzh4bIO5jh_OIKQg-pLdgfkOyjcSEPLFL_TzFaydMYFH9wyMYJEaDKlCSa_uBVqLfWIZkg.ts' for reading
```

**Comment by anxdpanic** [comment]
As suspected it is the hls segments being grabbed by ffmepg, which is not something we can change. 

Windows does cache DNS locally, so I would think the OS Kodi is running from is not caching locally so Pihole is getting every request. I don't believe OSMC caches DNS requests by default, not sure about LibreElec and others but I'm guessing they don't as well.

If the OS allows you to, configuring dnsmasq or unbound on the same system as Kodi as a dns cache should resolve the issue. Though for Kodi you may even consider bypassing the Pihole, not sure what benefit it brings to Kodi.

**Comment by fragande** [comment]
Ah, I see. That explains a lot. I do run OSMC. I didn't know about local DNS caching at all and was wondering why playing a HLS stream in Windows didn't have the same results. I'm running some other services on the Pi but none that really benefits from being "behind" Pihole so you made a good point. I went ahead and bypassed it. I'll look into enabling local DNS cache if I get some spare time.

Thank you for your patience, learned a lot.
