### ISSUE TITLE
Twitch error

### ISSUE THREAD

**Issue by j44m** [anxdpanic/plugin.video.twitch#354]
Everytime i try to open twitch addon i get the error "twitch error" check logfiles. So here is the logs.
https://paste.ubuntu.com/26410583/

**Comment by j44m** [comment]
would appreciate it if someone could help

**Comment by anxdpanic** [comment]
The module got updated on the official repo before the add-on which caused the issued.
The add-on is now on the official repo, so updates will resolve this once the cache is updated.
If you don't want to wait for that, you can install 2.1.0 from zip here: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.1.0

**Comment by j44m** [comment]
Thanks. Issue solved. Glad you took some time to explain. Should be more heroes like you around this World sir
