### ISSUE TITLE
VodCast colorisation is broken

### ISSUE THREAD

**Issue by TheGoblinHero** [anxdpanic/plugin.video.twitch#358]
Looks like twitch now returns stream_type = 'rerun' instead of old 'watch_party'. I do not know if  'watch_party' type is also possible now. I suggest colorizing everything with stream_type != 'live'.

**Comment by anxdpanic** [comment]
Thanks for the heads up. Will look into it before migrating to the new api.

**Comment by anxdpanic** [comment]
It's in master now, if no other reports this week. Will add to releases as 2.1,2 this weekend.
