### ISSUE TITLE
User Token Error

### ISSUE THREAD

**Issue by ivalkenburg** [anxdpanic/plugin.video.twitch#36]
For a few days now i've been having issues getting streams to play. I get the error "User Token Error" for streams that used to play fine. It seems to happen randomly. Sometimes i try again later to see it start just fine. Not sure what could cause this. Quality is set to Best possible.

04:06:28 T:140509703919360   DEBUG: [xbmcswift2] Handling incoming request for /playLive/manvsgame/
04:06:28 T:140509703919360  NOTICE: [xbmcswift2] Request for "/playLive/manvsgame/" matches rule for function "playLive"
04:06:28 T:140509703919360 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
04:06:28 T:140511365838656   DEBUG: LIRC: Update - NEW at 164714125:160 0 KEY_OK_UP devinput (KEY_OK_UP)
04:06:29 T:140509703919360   DEBUG: LocalizeStrings: no strings.po file exist at /storage/.xbmc/addons/Twitch.tv-on-XBMC/resources/language/English, fallback to strings.xml
04:06:29 T:140509703919360    INFO: Scriptresult: Success
04:06:29 T:140511365838656   DEBUG: WaitOnScriptResult- plugin returned failure
04:06:29 T:140511365838656   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/manvsgame/]
04:06:29 T:140511365838656   DEBUG: Playlist Player: one or more items failed to play... aborting playback

I use the latest openelec.

**Comment by ccaspers** [comment]
this seems to be a duplicate of #34
