### ISSUE TITLE
search history

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#360]
Kind of tiring typing in the name of a channel too often, how about a search history? Would be much appreciated. Something like the YouTube add-on's (https://github.com/jdf76/plugin.video.youtube)

Thanks

**Comment by anxdpanic** [comment]
If you'd like to test and confirm I've added it for the next version.
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.0-dev

**Comment by anxdpanic** [comment]
2.2.0 is now on the official repository, includes a separate search history for each type of search.
