### ISSUE TITLE
message flooding debug log

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#364]
I'm seeing an alarming amount of 
`DEBUG: Twitch: Using method cache for: |addon.api.Twitch.get_followed_streams| -> |39|`
in my logs when enabling debug. according to how often it's supposedly repeating, there are entries thousands of times a second.

```
09:41:16.326 T:139652006655744   DEBUG: Twitch: Using method cache for: |addon.api.Twitch.get_followed_streams| -> |39|
09:41:18.953 T:139653448312576   DEBUG: Previous line repeats 16506 times.
09:41:18.953 T:139653448312576   DEBUG: Thread JobWorker 139653448312576 terminating (autodelete)
09:41:18.954 T:139652006655744   DEBUG: Twitch: Using method cache for: |addon.api.Twitch.get_followed_streams| -> |39|
09:41:19.106 T:139653646628608   DEBUG: Previous line repeats 951 times.
09:41:19.106 T:139653646628608   DEBUG: Thread JobWorker 139653646628608 terminating (autodelete)
09:41:19.106 T:139652006655744   DEBUG: Twitch: Using method cache for: |addon.api.Twitch.get_followed_streams| -> |39|
09:41:19.151 T:139654482099072   DEBUG: Previous line repeats 284 times.
09:41:19.151 T:139654482099072    INFO: CheckIdle - Closing session to http://www.msftncsi.com (easy=0x7f03646b7ae0, multi=(nil))
09:41:19.151 T:139652006655744   DEBUG: Twitch: Using method cache for: |addon.api.Twitch.get_followed_streams| -> |39|
09:41:20.873 T:139652652779264   DEBUG: Previous line repeats 10858 times.
```

I'm not sure what's calling addon.api.Twitch.get_followed_streams so often, if that's what I'm reading. I do have a shortcut to my followed, currently live streams in my favorites, but no widgets displaying any twitch content. it does also actually update the cache properly when it's supposed to (or so it seems). is this proper behavior when the debug level is enabled?

kodi 17.6 on debian 9
twitch plugin 2.1.1 from the default repo

**Comment by anxdpanic** [comment]
That is definitely not proper behavior. I can't tell without more of the log but do you see any lines starting with 'Service: Now online', 'Service: Was online' around the times this is happening? The service would be the only thing able to do this so much in the background on our end, though I don't see that would cause anything like that.

**Comment by ghost** [comment]
I see a few from hours ago, but I don't have any currently followed streams live over the last few hours.

triggering debug messages in the log by moving the cursor, I can see the twitch message is being logged repeatedly, without any followed twitch streamers' status change. there are actually no other messages besides these, from the core or any plugin, between the button press messages.

I can create a clean .kodi directory and try just adding the twitch plugin? I ask because the kodi package for debian 9 (stable) is currently 17.1, so I had this install build 17.6 from the testing repository. that's the only other non-standard thing I can think of to rule out, though I am still building the maintained debian 17.6 package, the same one the binary is built from for anyone running debian testing or unstable.

is it possible something skin/UI related is bugged, and making that call to the service repeatedly? I can also try a clean version of a different skin (currently using rapier) without making any other settings changes. I'll go ahead and try those and report back- maybe you have another suggestion? (I know you need helpful info)

**Comment by anxdpanic** [comment]
Nothing else should be able to affect the service, but something could be trying to load a direct route. Skin or helper services would be my first thought, I would try changing to estuary and restarting first, if that doesn't resolve it then back up .kodi and try fresh twitch add-on only. A full debug log of it happening might help if possible.

**Comment by anxdpanic** [comment]
Were you able to resolve this?

**Comment by anxdpanic** [comment]
Closing due to no follow up, please re-open if require further assistance with this.

**Comment by astrilchuk** [comment]
This issue is happening on a brand-new install of LibreELEC 9.0.1 (Kodi 18.1) on a Raspberry Pi 3 with version 2.4.1 of the addon.

Here's what I'm seeing in the debug log:

```
2019-02-28 08:52:28.382 T:1707008880   DEBUG: Twitch: Using method cache for: |twitch_addon.addon.api.Twitch.get_followed_streams| -> |39| (ENCODED)                                       │                                                            
2019-02-28 08:54:17.703 T:1491923824   DEBUG: Previous line repeats 285383 times.                                                                                                          │                                                            
2019-02-28 08:54:17.703 T:1491923824   DEBUG: Thread JobWorker start, auto delete: true                                                                                                    │
2019-02-28 08:54:17.703 T:1707008880   DEBUG: Twitch: Using method cache for: |twitch_addon.addon.api.Twitch.get_followed_streams| -> |39| (ENCODED)                                       │
2019-02-28 08:54:47.703 T:1491923824   DEBUG: Previous line repeats 78455 times. 
```

If there's any more information I can provide please let me know.

**Comment by anxdpanic** [comment]
Need to see the complete debug log for context.
If you have Twitch add-on 'Settings - General - Live Notifications - Enabled' enabled, try disabling that and restarting to see if it continues. If not try with it re-enabled.

**Comment by astrilchuk** [comment]
Here's my kodi.log:

[kodi.log](http://ix.io/1CeQ)

I'll try disabling/enabling live notifications to see if that changes anything and report back.

Fyi, the reason I noticed this as an issue is due to one of the Pi cores being pegged at 100%.

**Comment by anxdpanic** [comment]
is that a single log or a couple stitched?

**Comment by astrilchuk** [comment]
That is from a single file - it was pasted as-is.

**Comment by astrilchuk** [comment]
Here is a new log with detailed logging enabled and live-notifications disabled:

**redacted**

I am not seeing a core pegged at 100% - though I'm not sure it happened 100% of the time.  I'll keep monitoring.

**Comment by anxdpanic** [comment]
Something is definitely doesn't seem right as far as Kodi/Libreelec is concerned (your addons get listed multiple times and time jumps). 
The time jump:
```
2018-06-22 07:11:58.879 T:1937310368  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
2019-02-27 14:13:10.754 T:1937310368  NOTICE: initialize done
```
All installed add-ons are relisted (around 7x and should only be once when Kodi starts)
``` 
2018-06-22 07:11:55.741 T:1937310368  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
```

The new log looks more like I would expect to see, something was really strange in the first log.

**Comment by astrilchuk** [comment]
I had enabled the detailed kodi logging after boot with the first posted log.  In retrospect I should've rebooted before posting the first log but I didn't want to lose any relevant information.

**Comment by astrilchuk** [comment]
This is also occurring on another older instance of Kodi that I've recently upgrading to LibreELEC 9.0.1.  I disabled live-notifications on that one and the log messages stopped.

**Comment by anxdpanic** [comment]
I was going to ask for the second log with debug logging enabled from start, but you beat me to it. Your first log does show symptoms which I've never seen (add-ons being re-listed).

Does it start happening again if you re-enable live notifications?

**Comment by astrilchuk** [comment]
I've re-enabled live notifications, restarted, and the messages are showing in the log once again (with a core pegged at 100%).

**Comment by anxdpanic** [comment]
If you have the time, can you follow someone that is currently live then restart when enabled. Your last log was showing 0 online followed streams, so that may help pinpoint the issue.

**Comment by astrilchuk** [comment]
I followed CohhCarnage and I'm not seeing any messages and the CPU is no longer pegged at 100%.

**Comment by anxdpanic** [comment]
Thank you, I think I found the issue. I will ping you when I have a test version ready 👍

**Comment by astrilchuk** [comment]
Wow, that's awesome!  Thanks for looking at this.

**Comment by anxdpanic** [comment]
Thank you for helping get to the bottom of it. 
I'm currently looking into closed captions so the test version will be delayed at least a few hours. This is the minor change to fix the issue if you'd like to apply it manually: https://github.com/MrSprigster/Twitch-on-Kodi/commit/7e4fd62f4255632ed23b47eff1ba28e1429b627e#diff-2c13613eee9b7cf1136e800511b86319

**Comment by astrilchuk** [comment]
I applied the change to `service.py`, rebooted, and can confirm that with no channels live I no longer see spammed messages in the log.

Thanks!

**Comment by anxdpanic** [comment]
Thank you for confirming

**Comment by anxdpanic** [comment]
2.4.2 with this fix is submitted to the official repository. The zips for official and unofficial versions can be found: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.2
