### ISSUE TITLE
Cache Removal not working

### ISSUE THREAD

**Issue by genauder** [anxdpanic/plugin.video.twitch#366]
Hey,

I did a fresh libreelec install on my NUC. Now the Cache Removal feature of your Twitch addon doesnt work anymore. No matter what I configure in the settings the cache removal wont load. Feels like the addon doesnt have the permission to delete any files. Can you please help me?

Thanks!

**Comment by genauder** [comment]
Kodi 17.6, Libreelec 8.2.4. Was working before with Libreelec 8.2.3, after a downgrade to that version however still doesnt work anymore. Installed on a SSD.

**Comment by anxdpanic** [comment]
Not sure what would be happening, will need a [debug log](https://kodi.wiki/view/Log_file)

**Comment by genauder** [comment]
...
I hope it helps...

**Comment by anxdpanic** [comment]
I don't see any errors relating to the live stream previews. Are you able to generate a log of you opening the context menu on Featured Streams and directly choosing 'Clear live preview cache'

**Comment by genauder** [comment]
There isn't even the "Clear live preview cache" option in the context menu. Reinstallation also doesn't help. Maybe uninstall the addon, delete the plugin folder and try to reinstall again?

**Comment by anxdpanic** [comment]
In order for that context menu to show, you need to enable Settings -> Live Previews -> Live Preview Settings
In order for it to happen automatically you need to enable Settings -> Live Previews -> Automatically clear live preview cache

**Comment by genauder** [comment]
Oh boy I'm stupid... :D
It's working now, thanks. :)

**Comment by anxdpanic** [comment]
Good to hear it's working for you 👍 :)
