### ISSUE TITLE
Update number?

### ISSUE THREAD

**Issue by gofirst2220** [anxdpanic/plugin.video.twitch#373]
When I manually enter update number in the files but it fails to install.

I'm on Kodi 18.0 alpha on Windows 10 (64-bit)

**Comment by anxdpanic** [comment]
Not sure what you mean, can you provide more information please.

**Comment by gofirst2220** [comment]
@anxdpanic  I mean this:


    <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
      <addon id='plugin.video.twitch' version='2.2.1' name='Twitch' provider-name='A Talented Community''>
     <requires>
        <import addon='xbmc.python' version='2.20.0'/>
        <import addon="script.module.python.twitch" version="2.0.0"/>
        <import addon="script.module.requests" version="2.9.1"/>
    </requires>
    <extension point='xbmc.python.pluginsource' library='resources/lib/routes.py'>
        <provides>video</provides>
    </extension>
    <extension point="xbmc.service" library="resources/lib/service.py" start="login"/>
    <extension point='xbmc.addon.metadata'>
        <platform>all</platform>
        <news>
     2.2.2
     [upd] close chat on playback stopped [ccope]
     [upd] service start parameter to login

     2.2.1
     [add] allow Adaptive as default quality
        </news>
        <assets>
            <icon>icon.png</icon>
            <fanart>fanart.png</fanart>
        </assets>
        <language></language>
        <source>https://github.com/MrSprigster/Twitch-on-Kodi</source>
        <license>GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007</license>
        <forum>http://forum.kodi.tv/showthread.php?tid=134538</forum>
        <summary lang='da_dk'>Twitch video plugin</summary>
        <description lang='da_dk'>Se dine favorit gaming streams!</description>
        <summary lang='de_de'>Twitch video plugin</summary>
        <description lang='de_de'>Schaue die besten Gaming-Streams!</description>
        <summary lang='en_gb'>Twitch video plugin</summary>
        <description lang='en_gb'>Watch your favorite gaming streams!</description>
        <summary lang='es_es'>Twitch video plugin</summary>
        <description lang='es_es'>¡Mira los streams de tus juegos favoritos!</description>
        <summary lang='fr_fr'>Twitch video plugin</summary>
        <description lang='fr_fr'>Regardez les streams de vos jeux favoris !</description>
        <summary lang='nl_nl'>Twitch video plugin</summary>
        <description lang='nl_nl'>Bekijk je favoriete gaming-streams!</description>
        <summary lang='nb_no'>Tillegg for Twitch</summary>
        <description lang='nb_no'>Se dine favorittstrømmere!</description>
        <summary lang='pl_pl'>Twitch video plugin</summary>
        <description lang='pl_pl'>Oglądaj ulubione programy TwitchTV!</description>
      </extension>
    </addon>

This should show up as

    <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
    <addon id='plugin.video.twitch' version='2.2.2' name='Twitch' provider-name='A Talented Community'>
    <requires>
        <import addon='xbmc.python' version='2.20.0'/>
        <import addon="script.module.python.twitch" version="2.0.0"/>
        <import addon="script.module.requests" version="2.9.1"/>
    </requires>
    <extension point='xbmc.python.pluginsource' library='resources/lib/routes.py'>
        <provides>video</provides>
    </extension>
    <extension point="xbmc.service" library="resources/lib/service.py" start="login"/>
    <extension point='xbmc.addon.metadata'>
        <platform>all</platform>
        <news>
         2.2.2
         [upd] close chat on playback stopped [ccope]
         [upd] service start parameter to login

         2.2.1
         [add] allow Adaptive as default quality
        </news>
        <assets>
            <icon>icon.png</icon>
            <fanart>fanart.png</fanart>
        </assets>
        <language></language>
        <source>https://github.com/MrSprigster/Twitch-on-Kodi</source>
        <license>GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007</license>
        <forum>http://forum.kodi.tv/showthread.php?tid=134538</forum>
        <summary lang='da_dk'>Twitch video plugin</summary>
        <description lang='da_dk'>Se dine favorit gaming streams!</description>
        <summary lang='de_de'>Twitch video plugin</summary>
        <description lang='de_de'>Schaue die besten Gaming-Streams!</description>
        <summary lang='en_gb'>Twitch video plugin</summary>
        <description lang='en_gb'>Watch your favorite gaming streams!</description>
        <summary lang='es_es'>Twitch video plugin</summary>
        <description lang='es_es'>¡Mira los streams de tus juegos favoritos!</description>
        <summary lang='fr_fr'>Twitch video plugin</summary>
        <description lang='fr_fr'>Regardez les streams de vos jeux favoris !</description>
        <summary lang='nl_nl'>Twitch video plugin</summary>
        <description lang='nl_nl'>Bekijk je favoriete gaming-streams!</description>
        <summary lang='nb_no'>Tillegg for Twitch</summary>
        <description lang='nb_no'>Se dine favorittstrømmere!</description>
        <summary lang='pl_pl'>Twitch video plugin</summary>
        <description lang='pl_pl'>Oglądaj ulubione programy TwitchTV!</description>
      </extension>
    </addon>

Because it shows the version number in Kodi as **2.2.1** instead of **2.2.2** which could indicate that nothing has changed since last version even though there are changes.

However, after making those changes nor downloading a newest version from the repo, results in 

> Add-on couldn't install from Zip file.
> See log for information

In the notification that popped up.

Edit: it works fine on Android with the changes but the changelog doesn't show up in news section in the add-on info screen.

**Comment by anxdpanic** [comment]
I've updated the latest release, the zip is available: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.2
