### ISSUE TITLE
Sharing from Yatse or kore

### ISSUE THREAD

**Issue by scottismyname** [anxdpanic/plugin.video.twitch#382]
Using android, if I have a twitch stream playing, and I try to play it on my Kodi install (RPi 3 running LibreElec), I can see the command getting sent to the plugin, but it's getting aborted without starting the stream.  I turned on debugging within LibreElec and here is what I see in the logs

https://pastebin.com/dNC1MT0E

Not sure if I'm missing any information, but any help would be appreciated!

edit: I should note, that using the plugin directly works like a charm.

**Comment by anxdpanic** [comment]
It appears that they are using version 1 routes.
Live streams should be: plugin://plugin.video.twitch/?mode=play&channel_name=$CHANNELNAME
Videos should be: plugin://plugin.video.twitch/?mode=play&video_id=$VIDEOID

**Comment by scottismyname** [comment]
So just to be clear, the authors of the Yatse and Kore remote need to update their code to send the right route?

**Comment by anxdpanic** [comment]
Long term yes, I've added backwards compat. routes, installing from latest master should resolve this now.

**Comment by scottismyname** [comment]
Thank you so much! What is the best way of installing the latest master?

**Comment by Tolriq** [comment]
For the record as answered you really should install the Yatse plugin to avoid all problems due to those addon changes ;) (And to support a million more things ;))

@anxdpanic what is the proper call for clips? https://clips.twitch.tv/SuspiciousCheerfulTriangleBlargNaut

**Comment by scottismyname** [comment]
@Tolriq This worked! Thanks!

**Comment by anxdpanic** [comment]
@skaforey You'd 'Download ZIP' from the 'Clone or download' button, and then Install from zip from within Kodi. If Tolriq's solution is working I wouldn't worry too much about it, will be making the next version available after I've had a chance to look further into the issues with clips.

@Tolriq Clips are currently not working due to recent changes by Twitch, but the call for clips is;
plugin://plugin.video.twitch/?mode=play&slug=SuspiciousCheerfulTriangleBlargNaut

**Comment by Tolriq** [comment]
@anxdpanic Thanks, next  version will use new path for users that do not use Yatse addon and Kore does not support twitch so you actually may already want to remove the legacy path support ;)

**Comment by anxdpanic** [comment]
Thank you, I've went ahead and removed it. 👍
