### ISSUE TITLE
Addon will not launch

### ISSUE THREAD

**Issue by AdamSzopa** [anxdpanic/plugin.video.twitch#388]
Hi,
I recently updated the plugin on my Philips TV, and now it will not work. I'm attaching the 
[kodi.log](https://github.com/MrSprigster/Twitch-on-Kodi/files/2229023/kodi.log)

**Comment by anxdpanic** [comment]
Without debug logging enabled, my best guess would be you need to install https://github.com/MrSprigster/script.module.python.twitch/releases/tag/2.0.1

If it's still an issue provide a log with debug logging enabled. https://kodi.wiki/view/Log_file

**Comment by AdamSzopa** [comment]
Hi,
@anxdpanic your suggestion worked! It was a bit of pain to download and copy this using the remote control of the TV, but it works :)

**Comment by anxdpanic** [comment]
Good to hear, it should have automatically installed with the add-on from the official repo. Something must have went wrong during that process, it shouldn't happen again if you're required to start fresh at any point.
