### ISSUE TITLE
VODs 404ing

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#389]
Hi,

Just right now, I went to watch a Kitboga VOD and the Twitch Kodi plugin is reporting a 404:
```
10:46:28.914 T:140071514343168 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
10:46:29.389 T:140071514343168  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'video_id': 'v289088750'}|
10:46:29.583 T:140071514343168   ERROR: Twitch: Error |Not Found| |[404]|
10:46:29.616 T:140076564916608   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?video_id=v289088750&mode=play]
```
However it seems to load fine from the site:
https://www.twitch.tv/videos/289088750

**Comment by anxdpanic** [comment]
This appears to be on twitch's end, that api end point is returning 404 for all videos.

**Comment by cmsimike** [comment]
Thank you!

**Comment by tofof** [comment]
I'm also getting 404 on all vods. 
Happened yesterday (approx 24 hours ago) and now, but there was a period (18 hrs ago) when vods were working normally.

Is there any workaround?

**Comment by anxdpanic** [comment]
It's fixed in master, waiting on a couple things before I bump the version.
https://github.com/MrSprigster/Twitch-on-Kodi/pull/391

**Comment by anxdpanic** [comment]
I bumped the version with the fix, https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.4
