### ISSUE TITLE
Error 404 when trying to playback

### ISSUE THREAD

**Issue by adrockadrock** [anxdpanic/plugin.video.twitch#390]
tried multiple channels/videos, every one gives me a 404 error when i try to start playback of anything.

last few lines of my kodi.log showing the error:

10:26:46.852 T:184  NOTICE: Twitch: Calling |list_channel_videos| for mode |channel_video_list| with pos args |['archive']| and kwargs |{'channel_id': '7832442', 'game': None}|
10:26:49.094 T:8592 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
10:26:49.428 T:8592  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'video_id': 'v289752309'}|
10:26:49.721 T:8592   ERROR: Twitch: Error |Not Found| |[404]|
10:26:49.747 T:6984   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?video_id=v289752309&mode=play]

**Comment by CoreyPenIT** [comment]
I can watch live streams but get the same error when trying to watch past broadcast videos.

**Comment by anxdpanic** [comment]
It's fixed in latest master, waiting on a couple things before I bump the version.
https://github.com/MrSprigster/Twitch-on-Kodi/pull/391

**Comment by anxdpanic** [comment]
I bumped the version with the fix, https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.4

**Comment by CoreyPenIT** [comment]
Thanks for the quick response!
