### ISSUE TITLE
Getting a 500 error when going to past broadcasts (Kodi on Libreelec)

### ISSUE THREAD

**Issue by mriswithe** [anxdpanic/plugin.video.twitch#394]
Running kodi on LibreElec. Plugin version 2.2.3. I can view live streams, but yesterday when I went to past broadcasts, it would show me videos then when I attempted to view the video I received a 404 error. 

Now when I go to past broadcasts it errors and pops up a notification that I received a 500 error. This is happening with two separate machines running the same libreelec and twitch plugin. 

Looking at the twitch changelog for their API I am not seeing anything that looks like it directly would affect this, but I haven't worked with their API at all before. 

Likely the problem is with the twitch API, but not sure if I am doing something wrong/different that is causing this.

**Comment by anxdpanic** [comment]
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.4 includes a fix for vods. If not resolved please include a debug log.

**Comment by anxdpanic** [comment]
The 500 error someone else reported as well on the forum, is a separate server side issue(not resolved by 2.2.4) . All is working here atm and is likely a temporary hiccup.

**Comment by mriswithe** [comment]
Thanks for the insanely fast response. Is there a delay before updates get pushed to the Kodi repo? I am ignorant of that process. Either way I will upgrade and test again once I am done at dinner. I will close the ticket out if there are no issues

**Comment by anxdpanic** [comment]
👍  The add-on has to be submitted and undergo review before making it to the official repo. atm, just waiting a couple days to submit, allowing early adopters time to report if any new issues have been introduced.

**Comment by mriswithe** [comment]
Makes sense, I will keep an eye out for any goofiness. Installed the update and I can start past streams now. Closing the ticket. Thanks for all your awesome work.
