### ISSUE TITLE
Cant Play VODs anymore Not found [404]

### ISSUE THREAD

**Issue by PsychoOnTour** [anxdpanic/plugin.video.twitch#395]
Hello since a couple Days i cant Play VODs anymore i always get the error Not found [404] on all VODs. Already reinstalled Kodi and the newest Twitch addon but the same error appears. 
Live Channel works as always.

`09:40:47.780 T:18446744072300369168 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:40:48.265 T:18446744072300369168  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
09:40:51.730 T:18446744072418197544 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:40:52.365 T:18446744072418197544  NOTICE: Twitch: Calling |settings| for mode |settings| with pos args |[]| and kwargs |{}|
09:41:39.374 T:18446744072404341376 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:41:40.557 T:18446744072404341376  NOTICE: Twitch: Calling |main| for mode |main| with pos args |[]| and kwargs |{}|
09:41:40.814 T:18446744072291183320   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?mode=settings
09:41:40.816 T:18446744072291183320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?mode=settings) failed
09:41:44.965 T:18446744072425002480 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:41:46.004 T:18446744072425002480  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['live']| and kwargs |{}|
09:41:49.779 T:18446744072425740776 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:41:50.457 T:18446744072425740776  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'channel_id': '22186976'}|
09:41:52.064 T:18446744072291183320  NOTICE: VideoPlayer: Opening: https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CpADWDFg6tdkTSjhS6bLanOAwDGX8hhwAFEoxueQJMX9VWv7MAcQjhfbQSE8bzjZG619HTJ9ewDJxGkFt1Etrhx7MhF14hmvGkJo5LINtJ6f8qVhZctO9qmLeBAn-hc2B0pm1AkrPsAPrM0rKEuU2619CGwp6FIgYDg96LkoaHsYM0UVa-8Fv2edQuUAQ7rLmv7x4GOhJh0sGe70WlLjkA3MSGubWFh8HUqYVLXWh6bRwFWYb0dMaIjMLXmLtGTQIiyFHSUpPmAcixy4s91uhrFY6qU9Uodm68kUlfU54piGHx8BpCC-55q4kts04q0WC8-0c-KHY7_9eEuYgNHQ4e94dbOS2n_5S2QLqTuM_48PKrfBdiFtg0YOQ_xRlikUWbLIIK94JiWW0__2L-5rv4AZlKHMWZrWyyycSNPKsnMpRIMWqKfDFrVv7IPaFQNnotyE0kI3jUXLhjIpqrhibK53JwX_C43k6mxqRQcdfJrMjWunFdMFCMQzbar9K-pP6hMZXdCdKfP_tfFFLUA0QmVD_RIQgjB7-GPAMM6vey491MjXxBoMwEAt4f-p0Qkos5br.m3u8
09:41:52.065 T:18446744072291183320 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:41:52.065 T:18446744072366527712  NOTICE: Creating InputStream
09:41:52.071 T:18446744072366527712  NOTICE: Creating Demuxer
09:41:54.197 T:18446744072366527712  NOTICE: Opening stream: 1 source: 256
09:41:54.198 T:18446744072366527712  NOTICE: Creating video codec with codec id: 28
09:41:54.478 T:18446744072366527712  NOTICE: Creating video thread
09:41:54.479 T:18446744072366527712  NOTICE: Opening stream: 0 source: 256
09:41:54.479 T:18446744072366527712  NOTICE: Finding audio codec for: 86018
09:41:54.481 T:18446744072366527712  NOTICE: Creating audio thread
09:41:54.482 T:18446744072429955576  NOTICE: running thread: video_thread
09:41:54.486 T:18446744072429225048  NOTICE: running thread: CVideoPlayerAudio::Process()
09:41:54.497 T:18446744072429225048  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
09:41:54.634 T:18446744072293295824  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
09:41:54.658 T:18446744072293295824  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60208 m_frames: 3763 m_frameSize: 8 channels: 2
09:41:56.451 T:18446744072291183320  NOTICE: Using GL_TEXTURE_2D
09:41:56.451 T:18446744072291183320  NOTICE: GL: Using MediaCodec (Surface) render method
09:41:56.452 T:18446744072291183320  NOTICE: GL: NPOT texture support detected
09:41:57.454 T:18446744072395397656  NOTICE: ES: Client  from ::ffff:192.168.178.32 timed out
09:41:57.988 T:18446744072429955576 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
09:42:03.680 T:18446744072291183320  NOTICE: CVideoPlayer::CloseFile()
09:42:03.681 T:18446744072291183320  NOTICE: VideoPlayer: waiting for threads to exit
09:42:03.745 T:18446744072366527712  NOTICE: CVideoPlayer::OnExit()
09:42:03.745 T:18446744072366527712  NOTICE: Closing stream player 1
09:42:03.746 T:18446744072366527712  NOTICE: Waiting for audio thread to exit
09:42:03.807 T:18446744072429225048  NOTICE: thread end: CVideoPlayerAudio::OnExit()
09:42:03.807 T:18446744072366527712  NOTICE: Closing audio device
09:42:03.894 T:18446744072366527712  NOTICE: Deleting audio codec
09:42:03.894 T:18446744072366527712  NOTICE: Closing stream player 2
09:42:03.895 T:18446744072366527712  NOTICE: waiting for video thread to exit
09:42:03.961 T:18446744072429955576  NOTICE: thread end: video_thread
09:42:03.963 T:18446744072366527712  NOTICE: deleting video codec
09:42:04.056 T:18446744072291183320  NOTICE: VideoPlayer: finished waiting
09:42:04.100 T:18446744072291183320   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
09:42:04.165 T:18446744072291183320  NOTICE: CVideoPlayer::CloseFile()
09:42:04.165 T:18446744072291183320  NOTICE: VideoPlayer: waiting for threads to exit
09:42:04.165 T:18446744072291183320  NOTICE: VideoPlayer: finished waiting
09:42:04.165 T:18446744072291183320  NOTICE: CVideoPlayer::CloseFile()
09:42:04.165 T:18446744072291183320  NOTICE: VideoPlayer: waiting for threads to exit
09:42:04.165 T:18446744072291183320  NOTICE: VideoPlayer: finished waiting
09:42:04.254 T:18446744072308372128  NOTICE: APEP Common Routines: Now I'm stopped at 49%
09:42:04.554 T:18446744072426573864 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:05.122 T:18446744072426573864  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['live']| and kwargs |{}|
09:42:06.068 T:18446744072402200728  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
09:42:08.687 T:18446744072424028984 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:09.440 T:18446744072424028984  NOTICE: Twitch: Calling |following| for mode |following| with pos args |[]| and kwargs |{}|
09:42:15.413 T:18446744072432908016 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:16.302 T:18446744072432908016  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['channels']| and kwargs |{}|
09:42:23.976 T:18446744072428443984 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:24.367 T:18446744072428443984  NOTICE: Twitch: Calling |list_channel_video_types| for mode |channel_videos| with pos args |[]| and kwargs |{'channel_id': '14371185', 'display_name': 'Northernlion', 'channel_name': 'northernlion'}|
09:42:26.356 T:18446744072420223128 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:27.405 T:18446744072420223128  NOTICE: Twitch: Calling |list_channel_videos| for mode |channel_video_list| with pos args |['archive']| and kwargs |{'channel_id': '14371185', 'game': None}|
09:42:30.523 T:18446744072427133432 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:31.225 T:18446744072427133432  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'video_id': 'v289579694'}|
09:42:31.949 T:18446744072427133432   ERROR: Twitch: Error |Not Found| |[404]|
09:42:32.001 T:18446744072291183320   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?video_id=v289579694&mode=play]
09:42:40.386 T:18446744072430101824 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:40.870 T:18446744072430101824  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'video_id': 'v289191369'}|
09:42:41.604 T:18446744072430101824   ERROR: Twitch: Error |Not Found| |[404]|
09:42:41.666 T:18446744072291183320   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?video_id=v289191369&mode=play]
09:42:43.376 T:18446744072298875128 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:43.849 T:18446744072291183320   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?channel_id=14371185&channel_name=northernlion&display_name=Northernlion&mode=channel_videos
09:42:43.853 T:18446744072291183320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?channel_id=14371185&channel_name=northernlion&display_name=Northernlion&mode=channel_videos) failed
09:42:44.135 T:18446744072298875128  NOTICE: Twitch: Calling |list_channel_video_types| for mode |channel_videos| with pos args |[]| and kwargs |{'channel_id': '14371185', 'display_name': 'Northernlion', 'channel_name': 'northernlion'}|
09:42:44.290 T:18446744072420175840 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|
09:42:45.056 T:18446744072291183320   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?content=channels&mode=followed
09:42:45.058 T:18446744072291183320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?content=channels&mode=followed) failed
09:42:45.074 T:18446744072420175840  NOTICE: Twitch: Calling |list_followed| for mode |followed| with pos args |['channels']| and kwargs |{}|
09:43:00.785 T:18446744072291183320 WARNING: Label Formating: $VAR[MovieStudioLogoVar] is not defined
09:44:36.202 T:18446744072395397656 WARNING: Previous line repeats 15 times.
09:44:36.202 T:18446744072395397656  NOTICE: ES: Client  from ::ffff:192.168.178.32 timed out
09:47:06.583 T:18446744072402200728  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
`

**Comment by anxdpanic** [comment]
Version with the fix is here: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.2.4

**Comment by anxdpanic** [comment]
If that doesn't resolve the issue for you, will need a full log with debugging enabled.

**Comment by PsychoOnTour** [comment]
thx didnt see there was already a fix now everything works again thank you very much

**Comment by anxdpanic** [comment]
Good to hear 👍
