### ISSUE TITLE
Twitch lag, just started

### ISSUE THREAD

**Issue by r33p0phph** [anxdpanic/plugin.video.twitch#396]
Hi,

First thanks for the app on kodi.

This is a problem with the app for kodi/Raspberry PI, today the app started having problems with the feed from twitch.
After 1-3 min stream it buffering and ends by closing app.

I tested internet, Raspberry PI, cables and i reinstalled the app.

I have no problem with twitch on pc/mac/android in the house on same internet.
And i would know if the internet is bad, has the kid is playing Fortnite and has not had any problems.

I also could stream a movie with not problems also on the Raspberry PI.

Raspberry PI is a 3 b with libreelec newest version.
Version 2.2.4

**Comment by r33p0phph** [comment]
Did a clean install of the PI. Used the zip from here and the problem is still there. Only addons with the problem.

**Comment by anxdpanic** [comment]
I have experienced no issues, this is likely a connection issue between you and twitch and not an issue with your internet as a whole.

Others report that using InputStream Adaptive helps with similar issues. 

To use InputStream Adaptive, go to **Add-ons -> VideoPlayer InputStream** and enable **InputStream Adaptive** if it's not already, then in the Twitch add-on settings go to **General** and enable **Use inputstream.adaptive** and change **Video Quality** to **Adaptive** 

If it's still an issue, you can post a [log with debugging enabled](https://kodi.wiki/view/Log_file) and I will take a look, though it's likely nothing we can resolve on this end.

**Comment by r33p0phph** [comment]
Hi Anxdpanic,

Thanks for the msg back.

Here is the log  -  http://ix.io/1jQa

I just want to let you know. 
This problem is ONLY on raspberry Pi and not on windows/mac/android all on the same internet.

But you may see something in the log.

Thanks.

EDIT:

I went and installed Kodi and the twitch app ONLY on my pc.

Here is the log from that: https://paste.ubuntu.com/p/WwB6vgJTHD/

Also i did give "InputStream Adaptive" a chance, but it lags and picture vs sound are not matching.

Hope you can use some more data.

**Comment by r33p0phph** [comment]
Btw, here is a log with Adaptive ON.

https://paste.ubuntu.com/p/FZbkHXZ4tb/ i have removed some private lines in the log. 

I can´t even get sound and video to match.

Also i ran this app for 1+ year and have never had any problems with it before now.

**Comment by r33p0phph** [comment]
Here is log from other Raspberry pi v2

https://paste.ubuntu.com/p/q5Jh49tWqJ/

I was getting Error "python.twitch: GET QUERY" on the screen and found this in log script.module.python.twitch: GET QUERY on line 598-601

This was a 100% new and clean install. Only Twitch was on it.

**Comment by r33p0phph** [comment]
02:02:13.999 T:1501291424  NOTICE: Twitch: Service: Shutdown
02:02:14.042 T:1501291424 WARNING: CPythonInvoker(1, /storage/.kodi/addons/plugin.video.twitch/resources/lib/service.py): the python script "/storage/.kodi/addons/plugin.video.twitch/resources/lib/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE
02:02:15.364 T:1501291424 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |12/31/18|

**Comment by anxdpanic** [comment]
From the logs, it looks like everything is in order as far as the add-on and nothing we can do to address this. I don't see any GET QUERY errors in the logs to know why you would have gotten that. (No play impact from those though)

Looks like Kodi's video player/ffmpeg are dropping segments to try to keep up, and on the Windows machine shows a lot of hardware acceleration/decoder errors. 

Seeing the bandwidth of the Source stream is >8500000 it's unlikely you'll get that to play smoothly on a pi/2(Using one myself). Next time try opening the context menu on the stream and choose 'Play choose quality' and try stepping down in quality if you find it's working at a lower quality you can 'Set default quality' in the same context menu.

Sorry, wish I had a more clear cut answer/solution for you.

**Comment by r33p0phph** [comment]
Hi,

I have done every option from 180p to source and it´s the same.

I´m getting a friend in Denmark to test this for me also.
Will see if his i doing the same.

EDIT: He didnt see any problems.

The funny part is that its only with this script there is problems with twitch.

I can even stream it from pc to chromecast and have not lag or buffering.

Don´t know if you looked in all the logs, but i did find it as typed Error "python.twitch: GET QUERY" and also it came up on screen 2-3 time.

**Comment by anxdpanic** [comment]
You're right I missed it(must have searched the same log twice last time), I doubled checked everything jic as well.

The get query failure is an api request failure, which is either twitch hiccup or a connectivity issue.

Outside of those errors the rest of the add-on seems to be doing as expected, and only fails once Kodi/FFmpeg or InputStream Adaptive have taken over. Given that it's happening with both and shows dropping segments, timeouts, etc. I wouldn't expect those to be the issue either.

Not sure what it'd be at this point, but it's presenting similar to a connectivity issue and between your friend, myself and no new reports it seems isolated to your place.

**Comment by dale7344** [comment]
Hi, 

I also am seeing laggy playback on a Raspberry Pi 2, after updating from OpenElec to latest LibreElec.

I put my details on the libreelec forum [here](https://forum.libreelec.tv/thread/12974-bad-twitch-playback-on-raspberry-pi-2/)

- OpenElec based on Kodi 17.3 with twitch addon 2.2.4 works fine.
- LibreElec current and alpha fails (about 8.5fps)
- OSMC current fails in the same way

Perhaps the OP might like to try the [last release of OpenElec](http://releases.openelec.tv/OpenELEC-RPi2.arm-8.0.4.img.gz) to see if that works in his situation. It would at least rule out internet issues if it does.

**Comment by r33p0phph** [comment]
> Perhaps the OP might like to try the last release of OpenElec to see if that works in his situation. It would at least rule out internet issues if it does.

I would love to, but Openelec is not working on Pi 3 b+ yet. Has not seen a update for a long time.

I have a friend that has same ISP here and will go there today and test to see if it´s the same on the line.

Right now im thinking it could be a problem with the router/modem from Frontier as i started getting the problem after i got a new one from them.

**Comment by Neclord9** [comment]
I also have frontier & had this same issue with buffering. Went ahead and tested it with my vpn on and have not had a problem since.

**Comment by anxdpanic** [comment]
@r33p0phph have you determined the cause of the issue?

**Comment by cmsimike** [comment]
I had frontier and previously confirmed https handshake timeout between my apartment and AWS. Similarly I've had AWS requests failing for other services (like doordash). I confirmed similar behavior on someone else's frontier a city away.

As mysterious as the problem started, it went away. I could not do anything to actually fix the issue and multiple emails to twitch with the output of openssl client didn't help.

**edit** for what it's worth, during the time I was seeing twitch timeout issues, work (a town north of where I lived on a different ISP) had no issues, and tunneling my traffic from home through work fixed any twitch issue i saw.

**Comment by cmsimike** [comment]
https://github.com/MrSprigster/Twitch-on-Kodi/issues/307#issuecomment-303167447 a comment of mine regarding what i was seeing with ssl handshake timeout.

**Comment by cmsimike** [comment]
For what it's worth, as I am settling into my night to watch Twitch, I am definitely seeing twitch live stream lag. VODs are fine to watch but live streams keep dropping out for me. it also takes a bit for the VOD to actually start

**Comment by r33p0phph** [comment]
Hi,

So after some days, the app was working with Adaptive mode.
And I was happy with that.
And also the last 2-3 days I could even stream without it.
But tonight it´s SO BAD again. 
I can´t stream anything on twitch on Kodi.
Also, I'm seeing the Python error in the upper right corner after the app crashes. 
I have rebooted the box, internet and all.
Right now I have to use phone or pc to watch Twitch.

**Comment by cmsimike** [comment]
I think the python error you're seeing is an HTTP request failing to twitch.

**Comment by r33p0phph** [comment]
I could be.
It would play for 1-5 min if it started and then just cut out of the app.
Up to today, it has been working just fine, I have been using it every day for hours with no problem.

**Comment by cmsimike** [comment]
It 100% is the connection from frontier (which I have) to twitch (which I've had issues with for a few days (and have in the past with similar issues) - today is the first day that it is better) and not the plugin.

What I've noticed (and I don't know if Kodi can do this, as this feature might depend on it more than anything) is other twitch steaming apps in situations like this will pause for a quick second, then downgrade the connection to a lower bitrate version, assuming your connection is slow. The problem isn't the connection is slow, but there is a connectivity problem between frontier and twitch. By virtue of requesting a different stream, you have an opportunity to reconnect and most of the time it works.

**Comment by r33p0phph** [comment]
Is that telling us the Kodi is bad or the coding of this app?
As I can watch Twitch just fine on the same network on their app or website. Even in Source without any problems.

**Comment by anxdpanic** [comment]
The add-on itself really has no control over that part of the playback. Would be Kodi/ffmpeg or inputstream.adaptive handling the actual playback. 
I sort of have the opposite issue, where 90% of live streams on the website are okay, but barely an issue in the add-on, and vods are literally unplayable for me on the website and again barely an issue in the add-on.

**Comment by r33p0phph** [comment]
I will close this ticket now.
It´s back to working okay. 
I can now also run "normal" 720p60 in some hours off the day.
Thanks, for all that looked into this.
