### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#4]
in XBMCbuntu everytime when I try to acces anything in TwitchTV plugin i get JSONerror - xbmc.log

> 10:54:37 T:8204080   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?url=&mode=featured&siteIndex=0
> 10:54:37 T:8204080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?url=&mode=featured&siteIndex=0) failed
> 10:54:37 T:2939157360  NOTICE: -->Python Interpreter Initialized<--

**Comment by StateOfTheArt89** [comment]
Which version of XBMCbuntu are you using?

**Comment by ghost** [comment]
I found this issue on 12.04 Ubuntu with XBMC installed as standalone app and 11.0 XBMCbuntu.. also on some openelec builds with raspberry pi. with clean install and also with latest updates of system. 

Currently iam running 12.04 Ubuntu and XBMC 11.0 with pulse package and issue is still present.

**Comment by ghost** [comment]
windows 7 - xbmc12 frodo beta, also xbmc11 ->>

20:41:17 T:3036  NOTICE: Thread Jobworker start, auto delete: true
20:41:17 T:2920  NOTICE: Thread XBPyThread start, auto delete: false
20:41:17 T:2920  NOTICE: -->Python Interpreter Initialized<--
20:41:17 T:2920  NOTICE: [xbmcswift2] Request for "%s" matches rule for function "%s"
20:41:17 T:3912  NOTICE: Thread Background Loader start, auto delete: false
20:41:18 T:3128  NOTICE: Thread XBPyThread start, auto delete: false
20:41:18 T:3128  NOTICE: -->Python Interpreter Initialized<--
20:41:19 T:3128  NOTICE: [xbmcswift2] Request for "%s" matches rule for function "%s"
20:41:20 T:3904  NOTICE: Thread Background Loader start, auto delete: false

**Comment by ccaspers** [comment]
probably irrelevant - many changes were merged since the issue was opened
