### ISSUE TITLE
IRC Overlay

### ISSUE THREAD

**Issue by cr08** [anxdpanic/plugin.video.twitch#40]
To make this one a quick and easy explanation: Twitch's chat is (obviously) based on IRC and their own semi-hidden documentation shows how to connect in a standard IRC client to any given channel.

If you check out the Twit addon for XBMC it has an option to overlay the IRC chat at the bottom of the screen.

If that could be done with the Twitch addon that would be pretty cool. :)

**Comment by tepesware** [comment]
+1

**Comment by StateOfTheArt89** [comment]
It seems the irc integration is easier than I thought. The Twit plugin uses another plugin to deal with irc: http://wiki.xbmc.org/index.php?title=Add-on:IrcChat

I will try to get it to work with this plugin.

**Comment by Smultie** [comment]
Any progress?

**Comment by MrSprigster** [comment]
@Smultie not yet, it seems like everyone is busy at present. Feel free to submit a contribution if you are capable.

Sprig
