### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by shaka3** [anxdpanic/plugin.video.twitch#409]
![](https://i.imgur.com/DGUdaJc.jpg)

When I try to access those channels (with encoding issues) on Android, Kodi (v18) crashes.

Log: https://paste.ee/p/2bwbZ

Sorry for my bad english.

**Comment by anxdpanic** [comment]
Can you try with:
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.3.4-beta
and
https://github.com/MrSprigster/script.module.python.twitch/releases/tag/2.0.4-beta

**Comment by anxdpanic** [comment]
These versions are now on the official repository. If this is still occuring, please re-open the issue with a complete debug log.
