### ISSUE TITLE
Chat auto scroll not working

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#416]
I have been noticing more and more lately that the chat when watching a stream will sometimes not properly follow and stay at the recent messages. on the bottom Occasionally it will pop back to the middle of the scroll area, other times it goes to the top. This seems to happen on both large and small streams and any video quality.

Rebooting and updating the addon does not seem to resolve this. Is there a setting or other option that may have been reset for me? Me sending a message does not seem to affect the behavior positively or negatively.

Twitch for kodi version 2.3.5
OSMC Oct 2018.10-1 (Kodi for Raspberry Pi)

**Comment by anxdpanic** [comment]
Chat uses a different add-on/script, https://github.com/divingmule/script.ircchat, development has been idle for ~3 years there.

**Comment by ghost** [comment]
Thanks for that info. Not saying this project, but would it be worth someone forking that and maintaining it?

**Comment by ghost** [comment]
Looks like rebooting the media center helps but is awkward. Cleanly exiting chat before switching streams seems to help sometimes as well.

Going to close this since it's an unmaintained dependency and not related to this add on directly.
