### ISSUE TITLE
Live stream search

### ISSUE THREAD

**Issue by PIXELSTURM** [anxdpanic/plugin.video.twitch#422]
Since 2 days the searching for live streams seems to be broken.
Greets.

**Comment by anxdpanic** [comment]
Just tested and it's working as intended. The last time I had this issue, searching on the Twitch site also returned no live results. 

Confirm if the issue exists on the website. If it is working for live streams on the website; Clear cache in Settings - Maintenance, reproduce the issue with debug logging enabled, and post the resulting log.
https://kodi.wiki/view/Log_file

**Comment by PIXELSTURM** [comment]
Yeep, currently it works again.

Had cleared caches etc. pp. Maybe Twitch was testing or got probs.
Next time i'll have logs. :)

Thanks and greetings.
