### ISSUE TITLE
share twitch video from android to kodi

### ISSUE THREAD

**Issue by efirshik** [anxdpanic/plugin.video.twitch#423]
share twitch video from android to kodi with official app Kore not work. 

twitch addon version 2.4.1
kore 2.4.6

**Comment by anxdpanic** [comment]
As far as I'm aware Kore doesn't have support for Twitch. An alternative would be to use Yatse which does support twitch content.

**Comment by efirshik** [comment]
@anxdpanic on Yatse work fine. big thx.

**Comment by anxdpanic** [comment]
Good to hear :)
