### ISSUE TITLE
Issues with python-twitch on Rpi3b+ Kodi

### ISSUE THREAD

**Issue by k3lt** [anxdpanic/plugin.video.twitch#434]
Hey, im using RetroPie and installed Kodi 18 on it.
I'm having some serious issues with this addon, i have RTMP & InputStream adaptive enabled, also InputStream enabled & adaptive video quality selected in Twitch addon.
When i open a stream for the first time it plays fine, but whenever i close the stream the addon completely "breaks", screen is dim and it's super zoomed in, i actually cannot even tell if i'm still in the twitch app or in kodi menu, i can still move around menu and i hear UI sounds so it's not crashed..
It looks like this: https://i.imgur.com/fDREcTv.jpg

I'm using Raspberry Pi3b+, Kodi is connected to the TV with HDMI if it makes any difference.
Any suggestions what could be wrong and if can i fix it?

**Comment by anxdpanic** [comment]
Looks like an issue with a refresh rate change or something. 
Would need a debug log showing the issue to hopefully see what is happening.

May be worth going to Kodi Settings - System - Display (at Expert level), choose Whitelist and select which resolutions/refresh rates you want whitelisted.

**Comment by anxdpanic** [comment]
You can close your issue @ https://github.com/ingwinlu/python-twitch/, we don't use that project we use https://github.com/MrSprigster/script.module.python.twitch/ which is based off of ingwinlu's.

**Comment by k3lt** [comment]
> You can close your issue @ https://github.com/ingwinlu/python-twitch/, we don't use that project we use https://github.com/MrSprigster/script.module.python.twitch/ which is based off of ingwinlu's.

I dont understand what you mean really, i have all resolutions / refresh rates whitelisted, which im supposed to disable?

Edit:
I just tried enabling debugging to get some logs, opened some random stream and backed out just fine.. it's not happening anymore, i'm so confused.. i guess it's 'resolved'.

Edit2:
It happened again, this time in different streaming app so it must be some issue with Kodi itself..

**Comment by anxdpanic** [comment]
To test I meant to whitelist only resolutions you would want to change to, and not any low resolutions. 
By description it seems to happen when refresh rate change is likely to happen and looks like resolution/scale is way off in the pic. Without a log it's all guess work though.

If you're unable to resolve it, I would get a debug log capturing the issue, and post to the appropriate forum (kodi, osmc, libreelec, etc).

**Comment by anxdpanic** [comment]
Looks like a solution is found for this issue, https://www.reddit.com/r/kodi/comments/at8vzo/i_get_stuck_here_everytime_i_stop_a_video_in_kodi/
Hope that helps 👍
