### ISSUE TITLE
Kodi 17.6 Twitch Error

### ISSUE THREAD

**Issue by AidenBane** [anxdpanic/plugin.video.twitch#435]
Hi,

since yesterday im not able to use your very nice twitch addon at my raspi 2 with kodi 17.6.
When i try to open a stream i get the message "Twitch Error".

Would you please help me?

Yours sincerly
Aiden

**Comment by anxdpanic** [comment]
Will need a debug log to hopefully see what is happening.
Information on how to obtain that: https://kodi.wiki/view/Log_file

**Comment by AidenBane** [comment]
> Will need a debug log to hopefully see what is happening.
> Information on how to obtain that: https://kodi.wiki/view/Log_file

http://paste.kodi.tv/qicohubove

Here is my Logfile. TY

**Comment by anxdpanic** [comment]
Something has your search database locked, you can reboot and delete the databases from Settings - Maintenance or manually from your userdata folder w/ Kodi shutdown. 

Further support will require a clean log with [banned add-ons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons) removed and debug logging enabled.

**Comment by AidenBane** [comment]
> Something has your search database locked, you can reboot and delete the databases from Settings - Maintenance or manually from your userdata folder w/ Kodi shutdown.
> 
> Further support will require a clean log with [banned add-ons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons) removed and debug logging enabled.

Would you please explain me, how to "reboot and delete the databases from Settings - Maintenance"?

**Comment by anxdpanic** [comment]
Reboot which ever machine Kodi is running on, open the Twitch add-on Settings - Maintenance and delete each search history database.

**Comment by AidenBane** [comment]
Ok. Thank you very much! Its working again. ;)
/solved&closed
