### ISSUE TITLE
goo.gl links no longer work

### ISSUE THREAD

**Issue by ehl0el** [anxdpanic/plugin.video.twitch#443]
google shut down their link shortening service causing the link that comes up when clicking "Get OAuth Token" to not be there anymore. How do I go about obtaining my OAuth token now?

**Comment by anxdpanic** [comment]
Thanks for reporting, this should be resolved now with 2.4.3~beta3
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.3

**Comment by anxdpanic** [comment]
Closed by 4de9642fd106fc0479fa71218bdd80ffc1f7f387
