### ISSUE TITLE
OAuth token generation flow broken

### ISSUE THREAD

**Issue by ccope** [anxdpanic/plugin.video.twitch#448]
The goo.gl  URL shortner was shut down 03/30/2019, so now you get an error in Kodi when you try to get a new oAuth token.

https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

**Comment by anxdpanic** [comment]
It's fixed in 2.4.3, available https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.3 It was also just added to the official repository ~2 hours ago, and will be available from there soon. 

The url is : https://twitchaddon.page.link/iNhr
