### ISSUE TITLE
Main Menu Settings have no effect

### ISSUE THREAD

**Issue by Kinc4id** [anxdpanic/plugin.video.twitch#453]
No matter what I activate or deactivate in the main menu settings, the main menu always shows the same entries.

**Comment by anxdpanic** [comment]
I just double checked here, and the main menu settings are working as expected. 
Which menu's exactly, and have you entered a oauth token?
A complete [debug log](https://kodi.wiki/view/Log_file) would be helpful as well.

**Comment by Kinc4id** [comment]
Can't give you a debug log right now, but yes I have entered an oauth token and this works as expected. I see my subscriptions and all this. But no matter what I turn on or off in the main menu settings it changes nothing in the actual add on.

I remember that the YouTube Add On had a similiar issue when I used it some time ago. Maybe its the same cause?

**Comment by anxdpanic** [comment]
I don't recall any reports from the YouTube add-on or from this add-on. Hopefully with the debug log we'll be able to figure it out.

**Comment by fragande** [comment]
Stupid question but are you making sure to hit OK after doing changes instead of backing out? I've done that mistake ... Changes are not saved if you don't.

**Comment by anxdpanic** [comment]
Please re-open with the log if the issue is still valid.

**Comment by anxdpanic** [comment]
I happened to finally reproduce the issue shortly after closing it. Resolved in master and next version.

**Comment by anxdpanic** [comment]
2.4.8 is on the official repository now
