### ISSUE TITLE
RPI4 hdmi selection

### ISSUE THREAD

**Issue by gawdsed** [anxdpanic/plugin.video.twitch#456]
I had put in a ticket thinking that my RPI4 had issues with streaming, ended up being an issue with the hmdi port the stream is sent to. 

As you may know, the RPI4 now has 2 displays, well... the HDMI 2 works for kodi, libreelec and everything, but the app will send the video stream to HMDI 1.

Not sure if that's something easy to fix or not, most likely need to put in some logic to determine the hdmi port being used and stream to it.

**Comment by anxdpanic** [comment]
This is something outside the scope of the add-on, we're unable to help resolve that issue.
