### ISSUE TITLE
infinity loading on json api request

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#458]
Hi,
I tried to start a twitch video via json request.
In the kodi werb interface, "api-browser/Player.Open"
with params:
{"item": { "file": "plugin://plugin.video.twitch/play/?video_id=thevideoID}}

Kodi starts loading, but never stops. Only way to stop it is to restart Kodi.

**Comment by anxdpanic** [comment]
Sorry for the late reply, what you are looking for is
```
{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"plugin://plugin.video.twitch/?mode=play&video_id=v539674942"}}}
```
see: https://kodi.wiki/view/Add-on:Twitch
