### ISSUE TITLE
Twitch.tv Addon freezing XBMC (on Linux)

### ISSUE THREAD

**Issue by svms1** [anxdpanic/plugin.video.twitch#46]
Hello!

Under certain circumstances the addon freezes XBMC completely, requiring me to kill the task (usually SSH -> pkill -9 XBMC) and restart the XBMC session.

I noticed this behaviour under following circumstances:
- When (accidentally) pressing the "skip back" button.
- Sometimes while trying to open a stream, the stream seemingly loads forever (i.e. it doesn't load at all), but there is no way to cancel it apart from killing the task.

I'm using XBMCbuntu and haven't had the chance to test it on Windows.

It would be awesome if you'd find the time to fix this since it can be very annoying on a remote controlled HTPC. And as a frequent user of the addon this appears on a pretty regular basis. Of course after the HLS fix since there are no streams working at the time.

**Comment by MrSprigster** [comment]
These freezes were related to RTMP and is fixed as a consequence of the implementation of HLS so this can be closed.
