### ISSUE TITLE
How do i update to latest version on Raspbian?

### ISSUE THREAD

**Issue by k3lt** [anxdpanic/plugin.video.twitch#465]
```
sudo apt-get update
sudo apt-get upgrade
```
Doesn't find any update, do i have to install it manually?
My kodi version:
> kodi is already the newest version (2:18.4-6~buster).

**Comment by fragande** [comment]
The latest version in the Kodi repository seems to be 2.4.5 so yes, you'd have to install it manually. Installing from zip files is pretty straightforward, but I think you have to enable installing from unknown sources in the Kodi system settings first if you haven't already. Then `Install from zip file` and be sure to follow the instructions for the latest release: `Install script.module.python.twitch-2.0.10.zip before installing this release`.

**Comment by k3lt** [comment]
Thank you it was easy, for some stupid reason i didnt think it will be possible to update it from within Kodi.. (don't ask why)
