### ISSUE TITLE
[Solved!] - [410] this API has been removed.

### ISSUE THREAD

**Issue by yustAnotherUser** [anxdpanic/plugin.video.twitch#466]
Everything seems to work fine until I try to start a video. The message above appears and the loading stays forever until i press back. Which gives me another error message which tells me to check to logs.
Where are these logs? I'm on OSMC.

Best regards

**Comment by AymericAbrac** [comment]
Same for me, since 2 weeks... i'm on Kodi/RaspBerry 4
Last but not least, It seems LG remove Twitch add-on from there "SmartTV" OS.

**Comment by fragande** [comment]
See issue #461. Twitch has severely limited the use of the API endpoint and third party application client ID's are no longer working. You need to manually update to the latest version (install from zip files) as 2.4.5 is the latest in the Kodi repository as of now.

**Comment by yustAnotherUser** [comment]
Thanks fragande,

works like a charm!

For everybody else who might read this:
1. Get this file:
https://github.com/MrSprigster/Twitch-on-Kodi/archive/master.zip
its this repository as a ZIP-File but in version 2.4.7. as time of this writing.
2. Move it somewhere where you can access it from your Kodi installation.
In Kodi:
Head over to Settings/Addons
and choose Install from Zip
Navigate to the file and select it
Wait a few seconds for the confirmation that is has updated the Twitch Plugin in the right upper corner. No need to deinstall the old version.

Thanks guys, have a nice day!

**Comment by fragande** [comment]
Happy to hear you got it sorted!

I do however think it's better to check [releases](https://github.com/MrSprigster/Twitch-on-Kodi/releases) and get the zip file(s) there. Sometimes there are instructions too, as in the case of 2.4.6 ( `Install script.module.python.twitch-2.0.9.zip before installing this release` ). I'm _guessing_ you need `script.module.python.twitch-2.0.9` for 2.4.7 to work properly too and I don't think it gets updated by only installing the master zip, so if you run into trouble again try installing that zip manually as well.

**Comment by anxdpanic** [comment]
Shouldn't need to install `script.module.python.twitch-2.0.9/10` first anymore. `script.module.python.twitch v2.0.10` is in the official repository now, so it should auto install when installing the add-on zip.

**Comment by AymericAbrac** [comment]
Thank you so much everybody !
It works fine ! 
HF

**Comment by anxdpanic** [comment]
2.4.7 was merged into the official repository, will be available when caching allows

**Comment by ghost** [comment]
Currently using version 2.4.10 and have this same issue. Added the OAuth Token but still the same.

**Comment by oolivero45** [comment]
I just wanted to add that I’m also experiencing the issue, with version 2.4.10 of the addon, running Kodi v18.6 on LibreElec v9.2.1 on a Raspberry Pi 4B.

I’ve tried downloading the repository manually and installing from ZIP as suggested in this issue, but found that it didn’t make any difference.

If there’s any information such as log files which would be helpful for you to have, let me know and I’ll send them over.

**Comment by tenpaiyomi** [comment]
Chiming in as well, 2.4.10, getting the 410 error.  FireStick 4K.

**Comment by mase76** [comment]
Here, too.

**Comment by AlphaCentauri** [comment]
Manjaro 20.0 and Twitch 2.4.10, also still have this issue.

**Comment by jmaruiz** [comment]
Installed 2.5.1 using the addon browser and manually via zip and still experiencing 410 error. Running on Raspberry Pi (Raspbian) if that helps diagnose.

**Comment by nip10** [comment]
Getting the same error. Running Twitch 2.5.1 on Kodi 18.6 on Raspbian

**Comment by anxdpanic** [comment]
1. Remove anything from **Settings** - **Developer**

---

2. **Settings** - **Login**
    - **OAuth Token** is your generated oauth token
    - **Private API Credentials - OAuth Client ID** \***MUST**\* be **kimne78kx3ncx6brgo4mv6wki5h1ko**
    - **Private API Credentials - OAuth Token** should left be blank unless you require subscriber only vods/streams. To obtain this token see, https://github.com/anxdpanic/Twitch-on-Kodi/issues/461#issuecomment-552670340

---

3. Run **Settings** - **Maintenance** - **Reset function cache**

---

If that doesn't resolve the issue, open a new issue and please provide the complete debug log. https://kodi.wiki/view/Log_file

**Comment by jmaruiz** [comment]
@anxdpanic  This did seem to make a difference, but didn’t fully fix it for me. What did happen is that the stream could now launch, but it took almost an entire minute after selecting the stream. Also, it was audio only for some reason, with a black screen. 

I decided to try out LibreElec instead and everything above worked perfectly. It may be an issue with Raspbian. Unfortunately I only have one SD card available atm so I can’t provide the log since I overwrote it with the new OS, apologies.

**Comment by nip10** [comment]
@anxdpanic Thanks for the help. I got it working. It was a wrong token in the **Private API Credentials - OAuth Token** field.
