### ISSUE TITLE
Cannot Get OATH token

### ISSUE THREAD

**Issue by SuperMagicom** [anxdpanic/plugin.video.twitch#468]
The link https://twitchaddon.page.link/eetJ is no longer resolving. Cannot get the token.

**Comment by anxdpanic** [comment]
It's loading for me

**Comment by MrSprigster** [comment]
Loading for me also.

**Comment by ghost** [comment]
I get the same error, go to get oauth token on my android box, and then go to my tablet or laptop type in the url in chrome and then i get the below message

Requested URL (https://twitchaddon.page.link/eetj%20notfound) must be a parseable URI, but possibly incomplete to be a DynamicLink.

**Comment by anxdpanic** [comment]
It's case-sensitive, https://twitchaddon.page.link/eetJ the J is uppercase

**Comment by SuperMagicom** [comment]
Seems to work intermittently. When I posted it wasn't work and shortly thereafter it started resolving again. I'm guessing it's the url shortener.

**Comment by ghost** [comment]
> It's case-sensitive, https://twitchaddon.page.link/eetJ the J is uppercase

Thank you that works, the smallest thing was the issue.,
