### ISSUE TITLE
[404] Manifest is resticted (sic)

### ISSUE THREAD

**Issue by asvetlovsky** [anxdpanic/plugin.video.twitch#469]
I'm getting the error:

[404] Manifest is resticted

(The error appears to be spelled "resticted" instead of "restricted")

Whenever I'm trying to play a VOD. I have a valid subscription to the channel, and I've updated my Oauth token using the new link in 2.4.7. Everything seems up to date, and streaming works - however I cannot access VOD right now. 

I'm on LibreELEC 9.2.0 (Kodi 18.5 2019-11-23). 

Here's a snippet from the logfile near the error: https://paste.kodi.tv/emefanowat.kodi

I've also attached the full kodi.log. 
[01_KODI.log](https://github.com/MrSprigster/Twitch-on-Kodi/files/3941250/01_KODI.log)

**Comment by anxdpanic** [comment]
For subscription only vods you'll also need `Settings - Login - Private API Credentials - OAuth Token`
See https://github.com/MrSprigster/Twitch-on-Kodi/issues/461#issuecomment-552670340 for how to get the `auth-token`

Where to put that `auth-token` has changed:
Put the `auth-token` in `Settings - Login - Private API Credentials - OAuth Token`
or you can also edit the `settings.xml` file
```
    <setting id="private_oauth_token">paste_oauth_token_from_the_web_here</setting>
```

Let me know if anything needs clarifying.

**Comment by asvetlovsky** [comment]
Thank you, that did the trick. I had no idea that new types of auth tokens were needed. 

Thank you for the help.
