### ISSUE TITLE
Appears 2.4.7 is having same issue with no playback again

### ISSUE THREAD

**Issue by joshsmithtogo** [anxdpanic/plugin.video.twitch#471]
I just verified that the new add-on isn't playing content again.  Maybe Twitch did something again.  I don't know.

**Comment by anxdpanic** [comment]
Just double checked 2 devices here, both are starting playback no problems

**Comment by joshsmithtogo** [comment]
So I found the problem, I had to revoke the token.  Even though I had entered one prior.  I guess my old token was interfering with the setup.
