### ISSUE TITLE
OAuth Token Issue | Redirect Mismatch error

### ISSUE THREAD

**Issue by ZerGo0** [anxdpanic/plugin.video.twitch#473]
Hey guys,

the addon showed up a prompt the other day that I need to generate a new OAuth token for some reason. I was trying to generate a new one, but when I hit "Continue" then I get redirected to the following page: https://www.twitch.tv/passport-callback?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI and shortly after that I get sent back to the twitch start page.

Am I doing something wrong or is the OAuth part of this addon outdated?

**Comment by anxdpanic** [comment]
Just tested creating a new oauth token with no issue. 

Ensure the settings in `Settings - Developer` are left blank. Otherwise will need a debug log to see what is happening.

**Comment by ZerGo0** [comment]
> Just tested creating a new oauth token with no issue.
> 
> Ensure the settings in `Settings - Developer` are left blank. Otherwise will need a debug log to see what is happening.

I had the official client id in my settings (which I don't need anymore?) and that caused some issues, generating works now, but I get the 410 error now. I haven't grabbed my oauth token from my browser yet, I will do it tomorrow. I hope that it works after that.

**Comment by anxdpanic** [comment]
The official client id and oauth token go in `Settings - Login - Private API credentials`

As long as the client id is filled out (`kimne78kx3ncx6brgo4mv6wki5h1ko`) there you should be able to access streams again (the private oauth token is only useful for subscriber only content)

If it is still giving 410 errors, try `Settings - Maintenance - Reset function cache`

**Comment by ZerGo0** [comment]
> The official client id and oauth token go in `Settings - Login - Private API credentials`
> 
> As long as the client id is filled out (`kimne78kx3ncx6brgo4mv6wki5h1ko`) there you should be able to access streams again (the private oauth token is only useful for subscriber only content)
> 
> If it is still giving 410 errors, try `Settings - Maintenance - Reset function cache`

Okay, I just test it:
1st Test: Using my auth-token from my browser and the official client id in the general tab.
Didn't work, I get a error saying "client-id mismatch".

2nd Test: Using my auth-token from my browser, the official client id in the general and dev tab.
Worked, everything is working again, my last browser auth-token probably just expired and I forgot about that.

Issue solved.
