### ISSUE TITLE
Following Live Channels not sorted anymore

### ISSUE THREAD

**Issue by apo86** [anxdpanic/plugin.video.twitch#474]
The followed live streams are listed in seemingly random order. They used to be sorted by viewer count.
Curiously, all the other live channel views (Browse Live Channels, Browse Games, Browse) are still sorted by viewers.

This started a few days ago, maybe a change in the API with how the followed live streams are returned?

As a workaround I added a line of code to sort the json by viewers right after it is loaded. That works fine for me.
I noticed for some of the other API functions there are sorting parameters, but as a Python noob I have no idea how any of it works. Anyways doesn't seem to be implemented for followed live streams.

**Comment by cmsimike** [comment]
Ditto - trying out the other sort options doesn't get me back to 'sorting by viewer count'

**Comment by lococola** [comment]
> As a workaround I added a line of code to sort the json by viewers right after it is loaded. That works fine for me.

For me it's also not sorting by view count any longer. Can you explain how and what you did to create a workaround?

**Comment by anxdpanic** [comment]
have a fix in place, will be pr'ing shortly

**Comment by anxdpanic** [comment]
The fix is in master now 6a88aa4bf255fd03bafa81456eefda984bf89ee5

**Comment by cmsimike** [comment]
Thank you very much!

**Comment by apo86** [comment]
Looks good, thanks!

**Comment by lococola** [comment]
Perfect, thank you! :)

**Comment by anxdpanic** [comment]
Fixed in https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.8, waiting official repository review.

**Comment by cmsimike** [comment]
Thank you for your continued work on this!
