### ISSUE TITLE
Streams not working for 1 week now

### ISSUE THREAD

**Issue by tobbi007** [anxdpanic/plugin.video.twitch#48]
Hey,
some days ago i wanted to see my favourite streams before going to bed :+1: 
but when i tried to start a stream i get the message "Keine Live Daten verfügbar" (german).

I already tried updating librtmp and i also downloaded the latest master repo from here. nothing helped.
im on openelec 3.2.4.
if you can tell me how to see the logs, i will paste them here.

**Comment by derrod** [comment]
These are known Issues, there are already Issues opened for that. For example https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/45 and https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/43.

We have to wait for the developers to update the App (which they stated they wanted to do in the next few days(?)).

You can find some workarounds here: https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/43#issuecomment-30902354

**Comment by tobbi007** [comment]
if i use the workaround, i cannot even start the addon anymore. guess i have to wait. thanks for the answer

edit:
the workaround works with the twitch addon that is in the xbmc repos, not with the master version of this gitpage.
thanks for helping me :+1:

**Comment by MrSprigster** [comment]
I've created a much improved fix with Quality options working and Auth added in as a future proofing solution. There's now a pull for this. <a href="https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/pull/49">#49</a>

**Comment by tepesware** [comment]
Thx Pull #49 works like a charm for me.

**Comment by MrSprigster** [comment]
Good to hear wwolinski. Thanks for the feedback.
