### ISSUE TITLE
No live channels found via Browse

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.twitch#487]
Using latest 2.4.9 zip, the one that doesn't say "unofficial". 

Right now, I went to:

Browse => Games => Apex Legends => Live Channels

Only a "No streams found" notification is displayed. 

Same for other games I tried (Fortnite, Escape from Tarkov). 

Streams with those games tagged are both in my followed channels and featured live streams. 

Oh hello, Browse => Live Channels also returns empty.

Also, Following => Games => any game => Live Channels 

Guess it has to do with twitch's recent API changes as well?

**Comment by hewwra** [comment]
This is due to a Twitch [bug](https://discuss.dev.twitch.tv/t/kraken-language-and-broadcaster-language-request-parameters-partly-broken/24214)

To work around this bug you should only filter streams by one language and not multiple.

Settings --> General --> Language

**Comment by jmbreuer** [comment]
Ah, thank you for the workaround!
... Wouldn't have started to look THERE.

**Comment by jmbreuer** [comment]
Ah, thank you for the workaround!
... Wouldn't have started to look THERE.

**Comment by anxdpanic** [comment]
2.5.0~alpha1 should resolve this issue, https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0-dev

**Comment by anxdpanic** [comment]
2.5.0 is waiting review on the official repository, release available: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0
