### ISSUE TITLE
VODcasts/reruns not listed under Following Live Channels

### ISSUE THREAD

**Issue by apo86** [anxdpanic/plugin.video.twitch#488]
Following Live Channels list used to show reruns in purple among the list of actual live channels.
This stopped a while ago, I couldn't say exactly when.

I poked around a bit and it looks like the current API call only picks up live live streams.

This one:
https://api.twitch.tv/kraken/streams/followed
According to the Twitch API v5 doc, parameter stream_type should be 'live', 'playlist' or 'all'.

'live' returns only actual live streams, 'playlist' returns an empty list (huh?) and 'all' returns live+reruns.

Changing the function to request 'all' instead of 'live' gives me the stream list like it used to be, reruns included and highlighted. But I don't know if that's the most elegant way to do it.

**Comment by anxdpanic** [comment]
Will try to get this fixed in the next version. Sorry, I complete overlooked the issue when checking for 2.4.10

**Comment by apo86** [comment]
No worries, thanks for your hard work!

**Comment by anxdpanic** [comment]
@apo86 sorry for the long delay, if able please try 2.5.0~alpha1, it should be resolved
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0-dev

**Comment by apo86** [comment]
Yup, looks fine, thanks. And again, no need to apologize :)

**Comment by anxdpanic** [comment]
Thanks for confirming!
2.5.0 is waiting review on the official repository, and the release is available: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0
