### ISSUE TITLE
Notifications seems broken

### ISSUE THREAD

**Issue by hewwra** [anxdpanic/plugin.video.twitch#491]
I never get notifications when streams go live anymore.

This error is in the log:

2020-03-18 21:32:23.963 T:3517248224   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/service.py", line 74, in run
                                                current_live = self.get_followed_streams(twitch, monitor, blacklist_filter)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/service.py", line 147, in get_followed_streams
                                                if streams[Keys.TOTAL] == 0:
                                            KeyError: '_total'

**Comment by anxdpanic** [comment]
Not sure how I hadn't noticed this earlier, fix should be included in https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.10-dev

**Comment by hewwra** [comment]
Notifications seems to work again at least to some degree.
It feels however like there are less notifications now then in the past.
Notifications used to happen both when a streamer went live and when they changed games right?
But now it seems like notifications only happen when a streamer goes live, at least accoring to my limited observations.

Perhaps unrelated but since the last update I sometimes see duplicate entries in the followed streamers node, always at the bottom see [screenshot](https://www.dropbox.com/s/ndfvkrwcdi058ms/screenshot009.png?dl=0)

**Comment by hewwra** [comment]
I enabled debug logging and checked the logs and everything is just fine with the notifications, it was all in my head.
However the issue displayed in the screenshot I posted is still there but its nothing I really care about.

**Comment by anxdpanic** [comment]
Thanks for confirming. I was able to replicate the other issue after a few tries. Will look into it further

**Comment by anxdpanic** [comment]
Submitted to official repository, https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.4.10

[fix] fix live notifications
[fix] fix clips
[fix] double entries in followed live streams
