### ISSUE TITLE
set default video quality by resolution

### ISSUE THREAD

**Issue by CorruptCommit** [anxdpanic/plugin.video.twitch#498]
Greetings,

Is there a way to set the default video quality by resolution, like 480p?  With resent efforts by some sites to make sure we don't overwhelm ISPs, I want to do my part.  My current work around is to set the default video quality to `Always ask`, but that requires some extra click to launch a stream. 

Thanks for a great plugin.

**Comment by kraaa** [comment]
Does always ask work for you? It does nothing for me.

**Comment by CorruptCommit** [comment]
@kraaa 

Yes every time I start a stream, I get a 'Choose Quality' pop up.  I am using Kodi `18.2` and `2.4.10` of this plugin.

**Comment by kraaa** [comment]
> @kraaa
> 
> Yes every time I start a stream, I get a 'Choose Quality' pop up. I am using Kodi `18.2` and `2.4.10` of this plugin.

Ah yeah I forgot I added default to 720p for the streams I watch, thinking that would play 720p 30fps but it always used 60 fps :(
Removed it from my settings and now I can choose 720p 30.

**Comment by anxdpanic** [comment]
You can set the default quality per stream from the context menu. Otherwise I'd suggest finding the bandwidth quality option that is right for you.
