### ISSUE TITLE
Filter streams by broadcaster_language no longer works

### ISSUE THREAD

**Issue by hewwra** [anxdpanic/plugin.video.twitch#499]
You can no longer filter streams by broadcaster_language, it seems like Twitch changed something. However you can now filter by language, [source](https://github.com/twitchdev/issues/issues/66).

**Comment by anxdpanic** [comment]
Should be fixed by #501 and https://github.com/MrSprigster/script.module.python.twitch master (need to package release still)

**Comment by anxdpanic** [comment]
2.5.0~alpha1 should resolve this issue, https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0-dev

**Comment by anxdpanic** [comment]
2.5.0 is waiting review on the official repository, release available: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0
