### ISSUE TITLE
120fps streams

### ISSUE THREAD

**Issue by scottismyname** [anxdpanic/plugin.video.twitch#502]
Not sure when twitch started allowing it, but apparently they allow 120fps streams now. My tv doesn't handle this and causes the video to stop playing but audio is fine. I can fix this by changing the setting to limit to 30fps, but it would be nice to have this option let you limit to 30 or 60.

**Comment by anxdpanic** [comment]
@scottismyname Can you provide a stream that uses 120?

**Comment by anxdpanic** [comment]
btw if you open the context menu on a stream and choose **Set default quality** it will let you choose the default quality for that stream only. So you can do this for problematic channels until another solution is in place

**Comment by scottismyname** [comment]
Oh good to know!

Here is a stream that uses 120fps:
https://www.twitch.tv/itsjstn

**Comment by anxdpanic** [comment]
If able, please try 2.5.0~alpha1
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0-dev
The fps limiter has been changed to a slider so it's easy to expand in the future.

**Comment by anxdpanic** [comment]
2.5.0 is waiting review on the official repository, release available: https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.5.0

please reopen if the new setting doesn't resolve the issue for you
