### ISSUE TITLE
Following Live Streams - Unable to navigate to next page

### ISSUE THREAD

**Issue by anxdpanic** [anxdpanic/plugin.video.twitch#514]
https://forum.kodi.tv/showthread.php?tid=134538&pid=2952082#pid2952082
https://paste.kodi.tv/kotuwikuqo.kodi

Next Page might be shown in error

**Comment by d1qqn** [comment]
same here. is there a solution?

**Comment by Psychoses** [comment]
hi,

i look into that one and just managed to fix this problem, not sure if this is the best soluce.

all in on followed.py

https://github.com/anxdpanic/plugin.video.twitch/blob/4ffbe75ced8504053e7b33d239b294a90489dc51/resources/lib/twitch_addon/routes/followed.py#L59

change it for
`kodi.create_item(utils.link_to_next_page({'mode': MODES.FOLLOWED, 'content': StreamType.LIVE, 'after': cursor}))`
