### ISSUE TITLE
get oauth fails to open dialog

### ISSUE THREAD

**Issue by Takezo36** [anxdpanic/plugin.video.twitch#515]
Hi,

get an oauth token fails to open the dialog in routes/token_url.py
result = kodi.Dialog().ok(heading=i18n('authorize_heading'), line1=i18n('authorize_message'),
                              line2=' %s' % prompt_url)
line2 is scrapped in the 19 api.

**Comment by anxdpanic** [comment]
Thanks for the heads up, it's fixed in #516
