### ISSUE TITLE
Request : Increase max allowed items per page from 100 to 1000. Leave default at 25.

### ISSUE THREAD

**Issue by PVrX** [anxdpanic/plugin.video.twitch#519]
This would be great! It would allow those with better systems to more easily navigate through the kodi addon! I find it tedious to have to hit "next page" over and over!

Edit: making it 2000 would be even better! :)

Thanks ! Eager to hear back.

Cheers!

**Comment by anxdpanic** [comment]
This won't likely ever be done. The new api also has request limits and this will just add to that.  10-20 x 100 Item requests is a lot. Especially if you expect it within a reasonable time frame and not paused waiting for the request limit to allow another request to complete those 10-20 requests.
