### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by Nohac** [anxdpanic/plugin.video.twitch#52]
OS: Arch linux 
Kernel: 3.12.6-1-ARCH
XBMC: 12.3
RTMP: v2.4

xbmc.log:
01:13:32 T:2717842240  NOTICE: -->Python Interpreter Initialized<--
01:13:32 T:2717842240  NOTICE: [xbmcswift2] Request for "/playLive/streamer/" matches rule for function "playLive"
01:13:34 T:3002111872   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/streamer/]

Note: 
I don't know if this helps anything, it was working fine a few days ago and I can't find out anything with that little info from the crash dump..

**Comment by MrSprigster** [comment]
That looks as though you're trying to play a stream by a streamer with the twitch username 'streamer' which of course doesn't exist...  Try downloading my latest pull request and see if it gives you the 'no live data' notification

**Comment by MrSprigster** [comment]
Also which version of the Plugin are you using? (I ask mainly because you referenced RTMP which is no longer relevant)

**Comment by Nohac** [comment]
Sry, I forgot to mention that I modified the streamers name to "streamer". 
I'm using 1.0.2? Tried to update several times.

**Comment by Nohac** [comment]
I'll try to install the one from git which is newer and report back later.

**Comment by MrSprigster** [comment]
If you were using 1.0.2 the one from the git will definitely fix your problem:)

**Comment by Nohac** [comment]
1.0.3 worked, for some reason it's not updated in the xbmc repo. Sorry for being retarded, this issue is solved.

**Comment by MrSprigster** [comment]
It's been submitted to the XBMC Repo but hasn't yet been accepted.

**Comment by MrSprigster** [comment]
Glad you got it up and running..  Enjoy!
