### ISSUE TITLE
[Help Wanted] Can watch progress be stored in MySQL DB?

### ISSUE THREAD

**Issue by pisaman2** [anxdpanic/plugin.video.twitch#520]
Hi
I've recently setup a central MariaDB SQL database, as I have multiple instances of Kodi in the house, and like to keep watch progress synchronized. 

One feature I love with this addon, is that it remembers the last playback position. My question is, is it possible for me to save this in my MySQL DB?

**Comment by anxdpanic** [comment]
That is all stored using Kodi/Kodi Databases, so watched status should be in the database configured for Kodi.
