### ISSUE TITLE
The oauth token link don't work

### ISSUE THREAD

**Issue by gjcq99** [anxdpanic/plugin.video.twitch#521]
I used the twitch addon for 9 months and i don't have any problem. But yesterday i uninstall and re install kodi. When i search the link https://twitchaddon.page.link/eetJ there a page who tell me this "404 There isn't a GitHub Pages site here." And this is the URL:
https://mrsprigster.github.io/Twitch-on-Kodi/token/#access_token=TOKEN-REMOVED&scope=user_read+user_follows_edit+user_subscriptions&token_type=bearer

My version of twitch is 2.5.1.
Sorry for my english, i'm from Perú, please help me

**Comment by MrSprigster** [comment]
Hey @gjcq99,

We moved the repository over to @anxdpanic's account yesterday which has caused the link to break. This is should work for you for now (add your token into the link before you use it, you shouldn't share that publicly): https://anxdpanic.github.io/Twitch-on-Kodi/token/#access_token=PUT-YOUR-TOKEN-HERE&scope=user_read+user_follows_edit+user_subscriptions&token_type=bearer

**Comment by gjcq99** [comment]
Thanks for the answer, it works now.

**Comment by anxdpanic** [comment]
Should be an updated version available from the official repository by tomorrow 👍 Also available as a zip from https://github.com/anxdpanic/Twitch-on-Kodi/releases/tag/2.5.2
