### ISSUE TITLE
Playback of reruns doesn't work

### ISSUE THREAD

**Issue by apo86** [anxdpanic/plugin.video.twitch#529]
It seems like something recently changed in the Twitch API again, resulting in an inability to play reruns (live streams and "past broadcasts" work fine, just the magenta reruns give a "Playback failed" error)

The reason is that
`https://api.twitch.tv/kraken/streams/<ID>?stream_type=all'`
returns
`{"stream":null}`
for reruns.
So do stream_type=live and stream_type=playlist

However, for reasons I can't comprehend, this one:
`https://api.twitch.tv/kraken/streams?channel=<ID>&stream_type=all`
does seem to return the right response.

Unfortunately I'm only playing around with curl, because my brain is not big enough to hack this directly into the kodi addon, so I don't know if it would actually work.

I'd appreciate if you could have a look.
Cheers!

**Comment by Psychoses** [comment]
i have recently experiment the same problem with magenta one.

**Comment by apo86** [comment]
Okay I got it to work.

In script.module.python.twitch/resources/lib/twitch/api/v5/streams.py
changed
`q = Qry('streams/{channel_id}', use_token=False)`
`q.add_urlkw(keys.CHANNEL_ID, channel_id)`
to
`q = Qry('streams', use_token=False)`
`q.add_param(keys.CHANNEL, channel_id)`

And in plugin.video.twitch/resources/lib/twitch_addon/routes/play.py
changed
`result = api.get_channel_stream(channel_id)[Keys.STREAM]`
to
`result = api.get_channel_stream(channel_id)[Keys.STREAMS][0]`

This works for me for both live and reruns. The result of the changed API call seems to suggest that it's possible for more than one stream to be returned (in which case this probably breaks), but I have no idea how or why that might happen.

Use at your own risk, I don't really know what I'm doing.

**Comment by apo86** [comment]
I just received 5.2.4 via official repository and this issue is still present, as well as above workaround still fixes it.
@anxdpanic Do you think this is a viable long term solution and if so would you implement it? Or is this not even a general issue and only something wrong on my end with my API tokens or whatever?
