### ISSUE TITLE
Gone [410] This API has been removed

### ISSUE THREAD

**Issue by isavcic** [anxdpanic/plugin.video.twitch#534]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.3
* Kodi Version: Leia
* Kodi GUI Language: English
* Operating System: Android 9 (Xiaomi Mi Box S)
* Operating System Language: English

------

### Expected Behavior

The streams playing as they did yesterday.

------

### Current Behavior

Twitch API seems to have changed and the streams won't start.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to start any stream, really

------

### Log

Can't include it as I have only "user" access to Kodi

------

### Additional Information

None really

------

**Comment by d0m84** [comment]
Same problem for me since a few days. Is there a fix?

**Comment by d0m84** [comment]
@anxdpanic Are you affected by this as well or is this a local/user issue?

**Comment by anxdpanic** [comment]
I haven't experienced this since the initial fix, and there hasn't been a large influx of complaints. Without a log I'm completely blind on what might be causing it.

**Comment by isavcic** [comment]
I'll try to figure out how to get some logs.

**Comment by anxdpanic** [comment]
You can upload it using the add-on, https://kodi.wiki/view/Log_file/Easy you'll see it mentioned here as `Kodi Logfile Uploader`

**Comment by d0m84** [comment]
@anxdpanic 

Thanks that pointed me into the direction to debug it. The error was:
```
21:50:37.700 T:3406975904   ERROR: Twitch: Error |Gone| |[410] this API has been removed.|
21:50:37.903 T:4096425984   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=123456&mode=play]
```


Before your comment I thought it's a general problem.
Something must have been changed on the Twitch side, but I don't know what.
But I found out how to solve it.

This was my settings.xml which worked before:
```
    <setting id="oauth_client_id" value="kimne78kx3ncx6brgo4mv6wki5h1ko" />
    <setting id="oauth_clientid" value="" />
    <setting id="oauth_redirecturi" value="" />
    <setting id="oauth_token" value="$MY_TOKEN" />
    <setting id="private_oauth_clientid" value="" />
    <setting id="private_oauth_token" value="" />
```

And I changed it according to https://github.com/anxdpanic/Twitch-on-Kodi/issues/466#issuecomment-633727391 and it fixes this issue as well:
```
    <setting id="oauth_client_id" value="" />
    <setting id="oauth_clientid" value="" />
    <setting id="oauth_redirecturi" value="" />
    <setting id="oauth_token" value="$MY_TOKEN" />
    <setting id="private_oauth_clientid" value="kimne78kx3ncx6brgo4mv6wki5h1ko" />
    <setting id="private_oauth_token" value="$MY_TOKEN2" />
```
$MY_TOKEN: Token generated by the plugin/website
$MY_TOKEN2: Browser extract as documented in https://github.com/anxdpanic/Twitch-on-Kodi/issues/461#issuecomment-552670340

If this is the only valid constellation right now it's maybe worth to document it in the _README.md_. I think it's to hard to understand what the 3 client_id settings are used for and which one to use. This might affect a few old users which don't have the "new" default settings.xml which already has the proper value for _private_oauth_clientid_ and everything else empty.

Thanks for your great work!

// UPDATE
I needed to add the second token as well in order to play all my favorite streams. This process should be documented as well IMHO.

**Comment by isavcic** [comment]
```
2020-10-30 22:22:45.723 T:16578   DEBUG: Twitch: Calling cached method: |twitch_addon.addon.api.Twitch.get_live|
2020-10-30 22:22:45.726 T:16578   DEBUG: script.module.python.twitch: GET QUERY: url: |https://api.twitch.tv/api/channels/joshog/access_token|, params: |{'need_https': 'true', 'platform': 'web', 'player_backend': 'mediaplayer'}|, data: |{}|, headers: |{'Authorization': 'OAuth ***********'}|, target_func: |channel_token|
2020-10-30 22:22:45.727 T:16578   DEBUG: script.module.python.twitch: Downloading: |https://api.twitch.tv/api/channels/joshog/access_token?need_https=true&platform=web&player_backend=mediaplayer|
2020-10-30 22:22:46.213 T:16578   DEBUG: script.module.python.twitch: url: |https://api.twitch.tv/api/channels/joshog/access_token| parameters: |{'need_https': 'true', 'platform': 'web', 'player_backend': 'mediaplayer'}|
                                            {
                                                "error": "Gone", 
                                                "message": "this API has been removed.", 
                                                "status": 410
                                            }
2020-10-30 22:22:46.215 T:16578   ERROR: Twitch: Error |Gone| |[410]
```

**Comment by anxdpanic** [comment]
@d0m84 
Your after is the default settings, why you changed them in the first place I don't know.

@isavcic 
Check that `Settings - Login -  OAuth Token` is your generated OAuth token if you have generated one (optional).
Check that `Settings - Login - Private API Credentials - OAuth Client ID` is `kimne78kx3ncx6brgo4mv6wki5h1ko`  (required)
Check that `Settings - Login - Private API Credentials - OAuth Token` is left blank.

All settings under  `Settings - Developers` should be left blank. (required)

**Comment by d0m84** [comment]
@anxdpanic 

Yes I saw that. I'm not sure what the default was when I installed the plugin a few years ago.

However with the default settings a few streams still didn't play. I can watch those without being logged in at all in the browser, but needed the private_oauth_token inside the plugin. This part and how to extract that token could be in the README.md to make it easier for new users.

**Comment by isavcic** [comment]
@anxdpanic that did it, I entered my token in the wrong box.
