### ISSUE TITLE
410 This api has been removed.

### ISSUE THREAD

**Issue by IdotMaster1** [anxdpanic/plugin.video.twitch#538]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.3
* Kodi Version: Kodi 17.6
* Kodi GUI Language: English
* Operating System: iOS 6.1.3
* Operating System Language: English UK

------

### Expected Behavior

I am expecting to be able to watch a stream

------

### Current Behavior

I am not able to watch a stream, i get: 410 This api has been removed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. put oauth
2. try to watch a stream

------

### Log

20:56:27.115 T:129658880  NOTICE: ES: Starting UDP Event server on port 9777
20:56:27.116 T:129658880  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
20:56:29.861 T:140914688 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
20:56:31.608 T:140382208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (10, 'No child processes')
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py", line 14, in <module>
                                                from version_check import service  # pylint: disable=import-error
                                              File "/var/mobile/Library/Preferences/Kodi/addons/service.xbmc.versioncheck/resources/lib/version_check/service.py", line 50, in <module>
                                                DISTRIBUTION = platform.uname()[0].lower()
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 1230, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 965, in _syscmd_uname
                                            IOError: (10, 'No child processes')
                                            -->End of Python script error report<--
20:56:44.085 T:804360192 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
20:57:02.444 T:804892672 WARNING: Previous line repeats 1 times.
20:57:02.444 T:804892672 WARNING: CPythonInvoker(5): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:57:02.766 T:804892672   ERROR: EXCEPTION: No valid addon id could be obtained. None was passed and the script wasn't executed in a normal xbmc manner.
20:57:03.337 T:804360192 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
20:57:15.991 T:804892672 WARNING: Previous line repeats 1 times.
20:57:15.991 T:804892672 WARNING: CPythonInvoker(8): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:57:16.208 T:804892672   ERROR: EXCEPTION: No valid addon id could be obtained. None was passed and the script wasn't executed in a normal xbmc manner.
20:57:16.703 T:804360192 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
20:57:36.052 T:804360192 WARNING: Previous line repeats 3 times.
20:57:36.052 T:804360192   ERROR: Twitch: Error |Gone| |[410] this API has been removed.|
20:57:36.244 T:113688576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=223191589&mode=play]
20:57:37.189 T:121384960 WARNING: DARWINIOS: underflow (0 vs 8192 bytes)
20:57:38.009 T:804360192 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
20:57:40.561 T:804360192   ERROR: Twitch: Error |Gone| |[410] this API has been removed.|
20:57:40.743 T:113688576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=116228390&mode=play]
21:01:01.001 T:804892672 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
21:01:03.583 T:804892672   ERROR: Twitch: Error |Gone| |[410] this API has been removed.|
21:01:03.776 T:113688576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=116228390&mode=play]
21:01:17.726 T:804360192 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
21:01:19.718 T:804360192   ERROR: Twitch: Error |Gone| |[410] this API has been removed.|
21:01:19.893 T:113688576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?channel_id=116228390&mode=play]
21:02:02.436 T:165158912 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
21:02:23.208 T:165613568 WARNING: Previous line repeats 2 times.
21:02:23.208 T:165613568 WARNING: CPythonInvoker(19): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
21:02:23.410 T:165613568   ERROR: EXCEPTION: No valid addon id could be obtained. None was passed and the script wasn't executed in a normal xbmc manner.
21:02:24.064 T:162975744 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|

------

### Additional Information
other issues where not usefull

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/Twitch-on-Kodi/issues/537
