### ISSUE TITLE
Trying to start a stream gives me `[404] this api does not exist`

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#541]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.3
* Kodi Version: 18.9
* Kodi GUI Language: EN
* Operating System: Ubuntu 16.04
* Operating System Language: EN

------

### Expected Behavior

Please describe the behavior you are expecting.

Loading up a person I am following should start the stream

------

### Current Behavior

What is the current behavior?
Browsing to "Followed Live Channels" loads up everyone I am following, however trying to start a stream (which has worked until just right now for me) gives me 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Load up your followed streamer list
2. Select person to watch
3. See error

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

2021-01-14 15:21:23.750 T:140230128555776   ERROR: Previous line repeats 1 times.
2021-01-14 15:21:23.750 T:140230128555776   ERROR: Twitch: Error |Not Found| |[404] This API does not exist|

------

### Additional Information

Please provide any additional information that may be helpful.
Was working fine yesterday.

------

**Comment by anxdpanic** [comment]
Fix is https://github.com/anxdpanic/Twitch-on-Kodi/issues/537#issuecomment-758930864

**Comment by anxdpanic** [comment]
This happened a couple days ago and it seems to be affecting people in a slow roll out, so I'm hesitant to push the update just yet.

**Comment by cmsimike** [comment]
Thank you very much! I knew about that old issue but that was for a separate API (games followed I think) so I opened this. I'll close this out now. Thanks for the help!
