### ISSUE TITLE
Getting adverts on subscribed channels.

### ISSUE THREAD

**Issue by Morgyn** [anxdpanic/plugin.video.twitch#546]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.4
* Kodi Version: 9.2.6
* Kodi GUI Language: English
* Operating System: Libreelec 9.2.6
* Operating System Language: English

------

### Expected Behavior

No Adverts on Subscribed Channels

------

### Current Behavior

Adverts on Subscribed Channels

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Watch a stream you are subscribed to.
2.  Get Adverts.
3.

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/Twitch-on-Kodi/wiki/Subscription-and-Turbo-benefits
