### ISSUE TITLE
"Failed to connect to Twitch API" as soon as I try to open the Twitch addon

### ISSUE THREAD

**Issue by M-Reimer** [anxdpanic/plugin.video.twitch#549]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.4-matrix.1
* Kodi Version: 19.0
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

It should be possible to open the addon which currently fails for me

------

### Current Behavior

Whatever I try to do in the Twitch addon causes an error message

"Failed to connect to Twitch API"

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Add-on
2. Try to open Add-on

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.ubuntu.com/p/bVwPhB7z5C/

Interesting is the part
     2021-03-16 21:00:41.605 T:515     ERROR <general>: TypeError: function takes at most 2 keyword arguments (3 given)

What is going on here?

**Comment by M-Reimer** [comment]
A short follow up: I've reset all settings and created a fresh OAuth token. Now I can access Twitch again.

So this seems to be an UI problem. If the error in my log file wouldn't have happened, I guess the addon would have told me more precisely that something is wrong with my OAuth token.

**Comment by procobain** [comment]
The same problem for me, I solved by creating a new OAuth token, Thank you
