### ISSUE TITLE
The OAuth token buttons in settings don't work with an old OAuth token filled in

### ISSUE THREAD

**Issue by Lucki** [anxdpanic/plugin.video.twitch#550]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.4+matrix.1
* Kodi Version: 19.0
* Kodi GUI Language: German
* Operating System: Arch Linux/Windows 10
* Operating System Language: German

------

### Expected Behavior

* I'm shown the short link to get a new OAuth token in the small popup window when clicking on the button to "Get OAuth token".
* The current OAuth token gets revoked and cleared when clicking on the "Revoke Token"

------

### Current Behavior

There's no popup showing me the short link to create a new OAuth token and the current OAuth token is not cleared on revocation.
Instead there comes a notification in the upper right corner from Kodi with a notice "Failed to connect to Twitch API".

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have your current twitch oauth token invalidated by having it for too long.
2. Try to access the addon, this will fail with "Failed to connect to Twitch API".
3. Try to revoke the current token in the addon settings, this will fail with "Failed to connect to Twitch API".
4. Try to get the short link to create a new OAuth token from the settings, this will fail with "Failed to connect to Twitch API".

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

Sorry, I've already inserted my new OAuth token and won't get this error anymore until the current token gets too old.

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by neo-neo1** [comment]
I’m also experiencing similar. Manually editing the settings file alleviates it.

**Comment by akhilleusuggo** [comment]
alleviates ? Do you mean fix it ?

Because the error logs doesn't point to any miss configuration , in fact was working normal until yesterday evening stopped streams because API dropped . Now the API does allow to login , but not play videos .

**Comment by chemsaf3** [comment]
maybe similar but when i change token i have to do it twice sometimes more. seems to not save right if token already present

**Comment by hegyak** [comment]
I somehow got this to work.

I edited the Settings.XML file Line:
oauth_token
By setting the default value to the One from the Webpage named "Twitch on Kodi"

and
private_oauth_token
By setting the default Value to my auth-token from the Twitch Website.

Then I went into settings, saw it was wrong.  Select "Defaults" and the Proper data was filled in for me.
After that I everything worked.

**Comment by Lucki** [comment]
Confirmed fixed, probably by #586 (https://github.com/anxdpanic/script.module.python.twitch/commit/aa34842e7495c81e90dc4f039ffd4623e9e749cb)

The different issue

> when i change token i have to do it twice sometimes

is still present but unrelated to this issue.
