### ISSUE TITLE
Streams won't srtart

### ISSUE THREAD

**Issue by sangivstheworld** [anxdpanic/plugin.video.twitch#551]
### Context

Today I was trying to watch some streams but the addon gave me an error, I tried using different tokens but they didn't work. I updated the app but it did not work. I can access my account (followed channels etc). When I try opening it it tells me "one or more items failed to play check the log for more information about this message".

* Add-on Version: 2.5.4
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: libreelec 9.2.6
* Operating System Language: English

------

### Expected Behavior

I expected the stream to open

------

### Current Behavior

It doesn't open, it gives me an error message and tells me to check the log

------

### Steps to Reproduce

1. Navigate to the stream
2. Open it

------

### Log

https://pastebin.com/Hg1zV6Dt

------

### Additional Information

It could be a token issue? I am not sure.

------

**Comment by akhilleusuggo** [comment]
same here

**Comment by akhilleusuggo** [comment]
I made mine work . So maybe the API broke something .

- Go to the plugin .
- Settings , manually delete client and private OAuth
- Click revoke OAuth
- Click reset to default
- Close the tab , this should reset `private_oauth_clientid`
- Request a new `oauth_token` ( get token )
- It works .

In my case I'm changing it manually from `userdata/addon_data/plugin.video.twitch` to copy/past .

Good luck 👍
