### ISSUE TITLE
Connection failed, Failed to connect to Twitch API message when I try to open a stream or get or revoke OAuth token

### ISSUE THREAD

**Issue by hiemsmutus** [anxdpanic/plugin.video.twitch#553]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.4+matrix.1
* Kodi Version: 19.0
* Kodi GUI Language: English
* Operating System: Android 7.1.2
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.
I can connect to streams or get or revoke an OAuth token

------

### Current Behavior

What is the current behavior?
I cannot connect to streams or get or revoke an OAuth token

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to connect to stream or get or revoke OAuth token
2. Get error message Connection failed, Failed to connect to Twitch API

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/ajenogepeb.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by Loakii** [comment]
I have similar issues. After doing the oath-token steps from the wiki I managed to consistently get audio without crashes.
I just cant seem to get the video to work. My screen stays black.

All I see in the log now is:

2021-04-21 22:11:29.033 T:2233    ERROR <general>:
                                                   Object: plane        ID: 68
                                                     Property: SRC_X    ID: 9   Value: 0
                                                     Property: SRC_Y    ID: 10  Value: 0
                                                     Property: SRC_W    ID: 11  Value: 108938308
                                                     Property: SRC_H    ID: 12  Value: 61341696
                                                     Property: CRTC_X   ID: 13  Value: 0
                                                     Property: CRTC_Y   ID: 14  Value: 0
                                                     Property: CRTC_W   ID: 15  Value: 1918
                                                     Property: CRTC_H   ID: 16  Value: 1080
                                                     Property: FB_ID    ID: 17  Value: 229
                                                     Property: CRTC_ID  ID: 20  Value: 74
2021-04-21 22:11:29.042 T:2233    ERROR <general>: CDRMAtomic::DrmAtomicCommit - atomic commit failed: Invalid argument
2021-04-21 22:11:29.061 T:2233    ERROR <general>: CDRMAtomic::DrmAtomicCommit - test commit failed: (Invalid argument) - falling back to last successful atomic request

**Comment by anxdpanic** [comment]
fixed in latest version, if persists please re-open.

**Comment by rjousse18** [comment]
I have the same problem on 2.5.10 matrix, kodi 19, libreelec 10 beta RC1
