### ISSUE TITLE
Video stream doesn't start

### ISSUE THREAD

**Issue by tuxrinku** [anxdpanic/plugin.video.twitch#556]
### Context

When I launch a stream through the app, it shows the "commercial break in progress" screen, but at the end kodi just crashes and restart few seconds later. I joined the log. I also saw that error using the `dmesg` command :
`VideoPlayer[5257]: segfault at 7fb7df1b0069 ip 00007fb82a456e42 sp 00007fb7af7fc548 error 4 in libc-2.31.so[7fb82a3bd000+178000]`

EDIT : Some streams seem to work fine while others just crash.

* Add-on Version: 2.5.4
* Kodi Version: 19.0
* Kodi GUI Language: French
* Operating System: Ubuntu 20.04
* Operating System Language: English

------

### Expected Behavior

Stream just opens and plays fine.

------

### Current Behavior

Kodi crashes when the stream is supposed to start.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open a video stream
2. Wait until the commercial ad screen is over
3. Kodi crashes

------

### Log

[kodi.old.log](https://github.com/anxdpanic/Twitch-on-Kodi/files/6385904/kodi.old.log)

------

**Comment by anxdpanic** [comment]
Also try with adaptive quality, but this crash should no longer be occurring. Please re-open if it is
