### ISSUE TITLE
Play non-partnered streams

### ISSUE THREAD

**Issue by OBenned** [anxdpanic/plugin.video.twitch#56]
Will it be possible at some point to play non-partnered streams.

As of now its not possible, but as i understand its because non partners are being streamed as chunked HLS?

**Comment by MrSprigster** [comment]
All streams are now using HLS encoding which we implemented support for in version 1.0.3 of the addon. 

As the latest versions have not yet been accepted into the official XBMC repository, you are most likely running 1.0.2 which does not have the ability to play HLS. 

You can either wait for the updates to be accepted into the Official XBMC Repository (probably within the next 48 hours) or alternatively download the latest version (1.0.6) from git hub (link to zip below) and install manually.

https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/archive/master.zip

Enjoy :)

Sprig

**Comment by OBenned** [comment]
Hi.

I'm already running the 1.0.3 but non-partnered is still a no go.
Partner streams run just fine.

**Comment by MrSprigster** [comment]
Hmm, I have a suspicion why this may be occurring for you.. Which stream quality do you use?

**Comment by OBenned** [comment]
Im running at 720p

I just tried changing to best possible and 360p but with the same result

**Comment by MrSprigster** [comment]
@OBenned, Please would you be so kind as to test my fix and report back, it should solve your problem. Link below:

https://github.com/MrSprigster/Twitch.tv-on-XBMC/archive/master.zip

**Comment by OBenned** [comment]
It works like a charm :)

Keep up the amazing work

**Comment by MrSprigster** [comment]
Excellent :), thank you for reporting the bug and for testing the fix.

Glad to help! :+1: 

Sprig

**Comment by OBenned** [comment]
No problem ;)
