### ISSUE TITLE
Feature Request for selecting multiple languages for streams (instead of all or a single language)

### ISSUE THREAD

**Issue by Stebs** [anxdpanic/plugin.video.twitch#564]
In Settings/General/Change languages, it seems one can only select one entry (all, da, de etc.).
It would be nice if one could select several languages, so streams in all the languages one can understand are shown.

If this is somehow possible, please make it more prominent/easier to do, I was not able to do it with remote, mouse or keyboard. (even tried some manual entries in storage.json).

If this is not possible at all, please rename the setting from "Change languages" to "Change language".
Thanks

**Comment by procobain** [comment]
+1

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.twitch/issues/499 This was removed by Twitch last year sadly.
