### ISSUE TITLE
404 error when openning clips.

### ISSUE THREAD

**Issue by DimmKG** [anxdpanic/plugin.video.twitch#568]
### Context
Can't watch any clips from Twitch.

* Add-on Version: 2.5.7
* Kodi Version: 18 (Leia)
* Kodi GUI Language: en_GB
* Operating System: Windows 10
* Operating System Language: en_US

------

### Expected Behavior

Clips can be opened and played.

------

### Current Behavior

After selecting a clip, nothing happens.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open addon and select "Browse"
2. Open the "Clips" section
3. Open any clip.

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.twitch/files/6679113/kodi.log)

------

### Additional Information
Addon generates a video link (e. g https://production.assets.clips.twitchcdn.net/AT-cm%7C1221888955-720.mp4) that throws a 404 error.

Video
https://user-images.githubusercontent.com/8424428/122611279-3dd0a100-d0ab-11eb-86be-b38f56da2cde.mp4

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/script.module.python.twitch/releases/tag/2.0.17
