### ISSUE TITLE
Getting ads as a sub

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.twitch#581]
I’m seeing preroll and midroll ads on channels I sub to. I currently have the default kimne... private client id inserted. Do I need to change anything to stop seeing ads on my subed channels? And by ads I mean the commercial break placeholder it shows instead. I love this add-on and would donate to it If I knew how

**Comment by anxdpanic** [comment]
Follow the wiki here: https://github.com/anxdpanic/plugin.video.twitch/wiki/Subscription-and-Turbo-benefits
