### ISSUE TITLE
The link for the oath token is dead. 

### ISSUE THREAD

**Issue by mklcf** [anxdpanic/plugin.video.twitch#582]
I randomly got an api error, so I decided to reinstall, but I can't get a token because the link (https://twitchaddon.page.link/yqBK) doesn't work.

**Comment by Mister-Denis** [comment]
Same problem when twitch authorization for TTV exist.

If i clear twitch authorization for TTV, the link is working, but the process does not finish
Response for the request
either 404 or
`{"status":401,"message":"invalid csrf token"}`
The auth is created in the twitch website though but i dont have the popup which give me the token to use

I can repeat the 2 case above multiple times with same consequence.

Note :  i edtited the message after having repeated the above steps.

**Comment by Mister-Denis** [comment]
As a temporary workaround.
1 - remove the authorization for TTV within twitch
In the web site, it is under parameters -> connections "tab" -> scroll down to "other connections".
2 - do the regular creation of the token by clicking the usual link (see mkclf post).
3 - when you get a 404 screen copy the corresponding URL to a text editor just for esay reading.
It will be like: 
`https://anxdpanic.github.io/Twitch-on-Kodi/token/#access_token=XXX&scope=user_read+user_follows_edit+user_subscriptions&token_type=bearer`
of course "XXX" will be replace by the generated token.
4 now use the string where the "XXX" is as your oauth_token.

**Comment by anxdpanic** [comment]
https://twitchaddon.page.link/Vvxc should work, the repository was renamed so some things had to be updated.

**Comment by Mister-Denis** [comment]
> 
> 
> https://twitchaddon.page.link/Vvxc should work, the repository was renamed so some things had to be updated.

just testing the new link, it's working fine for me.
Thanks a lot.

**Comment by mklcf** [comment]
Thanks a lot for the new link!

I forget what to do exactly to get twitch turbo working. I know it was on here somewhere, but I can't seem to find it...

**Comment by beigexperience** [comment]
Link works fine but the token is not accepted in the addon. On libreelec on raspi 3b+.   Says failed to connect to twitch api
