### ISSUE TITLE
Subscription locked streams don't downscale

### ISSUE THREAD

**Issue by bbck** [anxdpanic/plugin.video.twitch#59]
If a stream only allows subscribers to view higher quality bitrates, the addon will refuse to play if best possible is selected for the quality setting. 

Tried with http://twitch.tv/gsl this morning. Having 720p or best possible cause an error when trying to play. The stream works when changing the video quality setting to 480p. On twitch only medium and below are offered for free.

Expected behaviour would be playing the highest quality allowed without a subscription if the addon is configured to pick one that is sub only.

**Comment by Sup3rlativ3** [comment]
The reason is that the plugin does not log you in. You provide the username because your follows are public. It would be awesome if you could login via the plugin (dota2 allows drops in game if you are logged in and have your steam account connected)

**Comment by MrSprigster** [comment]
As far as I can see, the Twitch API does not provide us with the ability to check if the higher encode options are locked to subscribers only so manually switching to a lower quality is the only option for now. 

@Sup3rLativ3 is correct and the authentication feature is on the to do list so watch out for that.

**Comment by derrod** [comment]
If you request the playlist all available qualities are in there. If higher qualities (source, high) are not available you might want to have the add on falling back to the next highest quality available.

Btw the restricted qualities are in the token.

**Comment by MrSprigster** [comment]
@derrod, thanks for that (I didn't think of checking for restrictions in the token!) :+1:. I'll implement a check for restricted qualities in the token and fall back on the best available quality as you suggested.

Sprig

**Comment by MrSprigster** [comment]
Fixed in https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/pull/61

**Comment by MrSprigster** [comment]
This is solved and can be closed (@bbck feel free to do the honours)
