### ISSUE TITLE
Toggle follow now 404s

### ISSUE THREAD

**Issue by cmsimike** [anxdpanic/plugin.video.twitch#591]
### Context

Please provide any relevant information about your setup

* Add-on Version: Latest - not exactly sure where to find it in the ui but can update if needed
* Kodi Version: 19.1
* Kodi GUI Language: english
* Operating System: Android TV 
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Can't follow anymore. API endpoint returns a 404 when trying to follow a user from the categories/game menu

------

### Current Behavior

What is the current behavior?
The API end point 404s with a message that the end point was sunset at the end of June

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Go to games
2. Select user that you are not following
3. Toggle follow

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

I'm happy to grab this but will need to jump on another computer to do it. Not sure it's too easy to grab a log from the Android file system. Again happy to do it if you think it will help.

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
This should be resolved with https://github.com/anxdpanic/plugin.video.twitch/releases/tag/v2.5.11 and https://github.com/anxdpanic/script.module.python.twitch/releases/tag/v2.0.19 thanks to @apo86 
submitted to the official repository as well.
