### ISSUE TITLE
Only first 20 followed channels analyzed for being online

### ISSUE THREAD

**Issue by grocal** [anxdpanic/plugin.video.twitch#6]
In function _createFollowingList()_ you compare two data sets: list of channels followed by user _jsonData_ and list of actual live channels _xmlDataOnlineStreams_. According to JustinTV API this

```
jsonData = getJsonFromTwitchApi('http://api.justin.tv/api/user/favorites/' + username + '.json')
```

will **only return first 20 entries from favorites**. Therefore if there are some channels that user follows and those channels are beyond those 20 returned by API they won't be listed.

Fix:

```
jsonData = getJsonFromTwitchApi('http://api.justin.tv/api/user/favorites/' + username + '.json?limit=100')
```

100 is, accordint to JustinTV API, maximum number of followed channels we can retrieve from API _user/favorites_

**Comment by StateOfTheArt89** [comment]
Fix is online: 1c0127f6e136026701410b517ac656a51a74ee92

Thanks for the remark. As soon as the twitch api is ready, i'm going to switch this part to the twitch api-version.

https://groups.google.com/forum/?hl=de&fromgroups=#!topic/twitch-api/MuQnWlE2vHc
