### ISSUE TITLE
"Laggy" image

### ISSUE THREAD

**Issue by Ulrar** [anxdpanic/plugin.video.twitch#60]
Hi,

Recently I started to have a problem with the plugin.
Almost all the time I have sort of a laggy blinking image, everything kind of blink backward all the time. Like if a unit is moving, it is always blinking back as it moves forward, which is really really annoying to watch.

Don't know if that's very clear, I would have liked to take a video but I have nothing capable of taking a fluid enough video to show the problem.
It does that with every stream, and no problem on the PC so it is a problem with the plugin.

I am using OpenElec for rpi

EDIT : Seems to work fine in 720p though, so I guess the problem is only in 1080p

**Comment by KoehlerClem** [comment]
Hey i have the same problems. Laggy video while sound has no problems. I uploaded a video on vimeo here: http://vimeo.com/84489709

I am runnning Raspbmc on the pi. I installed it new and tried oc but nothing helped. I have a 100Mbit up/down connection from my university so that should not be a problem. 1080p youtubevideos and movies are no problem.

**Comment by Ulrar** [comment]
That's exactly the same problem indeed.
I have a 100 Mbit connection too.

**Comment by Sup3rlativ3** [comment]
I can also confirm this. I am also having streams buffer constantly to the point where it is unwatchable whereas before the HLS update or whatever it was fine. I'm thinking that this may be because it's trying to stream in 1080 rather than the 720 I want to stream. I can stream "high" on twitch website no problems.

**Comment by MrSprigster** [comment]
Hi Guys,

When you play a stream, this Addon requests a playlist file from Twitch which contains a playlist item for each quality that is available for the stream that you selected. 

It then looks at your settings to ascertain your preferred quality and passes the relevant playlist item to the XBMC video player which handles all of the playback functionality.

Unfortunately this means that this issue does not fall within the scope of this Addon and we will not be able to provide you with a solution. 

Unless the XBMC team release an update to their video player that addresses the HLS stream skipping at 1080p resolution that you guys are encountering, it may be a case of sticking to the 720p option in the settings.

It is worth noting that this is likely a hardware limitation of the Raspberry Pi not being able to deal with the decoding of the new HLS streams at high resolution and not a software related issue (in my opinion / best educated guess).

@Sup3rLativ3: You can select 720p from the TwitchTv Addon settings which is the same as selecting 'high' on the twitch website (the default option 'Best possible' is equivalent to 'Source' on the twitch website).

Sprig

**Comment by Sup3rlativ3** [comment]
@MrSprigster I have 720p selected but the playback is equivalent to the source from the twitch site. I do notice that some streams are worse than other. Perhaps this is all some other issue and just coincided with the update but nothing on my end has change other than the experience. I can see I'm getting about 4Mbps from twitch on my computer and it seems to be running fine (that's on best).

Thanks for looking into anyway, I'm going to change my ADSL profile with my ISP and see if perhaps they can get me some more speed or check the routing for issues.

**Comment by Ulrar** [comment]
That's strange, the rpi is usually perfectly capable of decoding 1080p
streams, I do it all the time though ftp, sftp or webdav.
Does twitch use some esoteric encoding that the hardware wouldn't support ?
That would be also strange, not sure the cpu could even decode 720p if it
was asked to.

2014/1/19 Dave - Mr Sprigster notifications@github.com

> Hi Guys,
> 
> When you play a stream, this Addon requests a playlist file from Twitch
> which contains a playlist item for each quality that is available for the
> stream that you selected.
> 
> It then looks at your settings to ascertain your preferred quality and
> passes the relevant playlist item to the XBMC video player which handles
> all of the playback functionality.
> 
> Unfortunately this means that this issue does not fall within the scope of
> this Addon and we will not be able to provide you with a solution.
> 
> Unless the XBMC team release an update to their video player that
> addresses the HLS stream skipping at 1080p resolution that you guys are
> encountering, it may be a case of sticking to the 720p option in the
> settings.
> 
> It is worth noting that this is likely a hardware limitation of the
> Raspberry Pi not being able to deal with the decoding of the new HLS
> streams at high resolution and not a software related issue.
> 
> @Sup3rLativ3 https://github.com/Sup3rLativ3: You can select 720p from
> the TwitchTv Addon settings which is the same as selecting 'high' on the
> twitch website (the default option 'Best possible' is equivalent to
> 'Source' on the twitch website).
> 
> Sprig
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/60#issuecomment-32711192
> .

## 

Kévin Lemonnier

**Comment by MrSprigster** [comment]
@Ulrar: You do have a point there, unfortunately I could only attempt an educated guess as to why this behavior is only occurring on the Raspberry Pi at 1080p. It may be a bug with the video player in XBMC that only presents itself on the Raspberry Pi platform but as I said previously this issue is definitely outside of the scope of this Addon.

@Sup3rLativ3: No worries :+1: , I hope you manage to find a solution.

Sprig

**Comment by Ulrar** [comment]
Well, no big deal, 720p is enough for me.
Thanks anyway !

**Comment by Smultie** [comment]
Finally some others with the same issue. IMHO I don't think it's a hardware constraint issue. Will link this topic to some other forms with RPi/XBMC geniuses. Maybe they can figure out what goes wrong here.

In the meantime, thanks for the 720p suggestion. It's a good workaround for the time being!

**Comment by MrSprigster** [comment]
http://forum.xbmc.org/showthread.php?tid=152339 is worth a read.

**Comment by Smultie** [comment]
Thanks for the link. However, I'm running XBMC on an overclocked RPi (1GHz, from USB) and the system rarely gets above 50% CPU, so there is some room for some extra calculations for sure.

**Comment by henrikbjorn** [comment]
Have the same problem with AppleTV also have 720p as my setting.

**Comment by MrSprigster** [comment]
Closing due to issue being outside of our control.
