### ISSUE TITLE
move twitch.py to seperate git repository

### ISSUE THREAD

**Issue by ingwinlu** [anxdpanic/plugin.video.twitch#66]
Hi,

I am currently working on my own media center application and I am using a modified (python3 compatible and stripped of xbmc references) version of twitch.py.

Have you thought of moving twitch.py to a seperate repository so it can be used by other applications besides xbmc as well?

**Comment by MrSprigster** [comment]
Hi,

This isn't something that I would personally be interested in doing, however this project is covered by a GNU License which means you are free to fork and maintain your own version of the twitch.py that's specific to your media center, but please do give credit where credit is due.

Cheers,

Sprig

**Comment by ingwinlu** [comment]
Hi MrSpringster,

thank you for your input.

I did not do serious testing yet but it seems to work well with python2 and python3:
https://github.com/ingwinlu/python-twitch

**Comment by MrSprigster** [comment]
No problem, it is worth noting that there's a lot of dead code in twitch.py which used to handle the previous twitch encoding method (RTMP) and we just haven't had the time to go through and clean it all up yet.

On a separate note, I also had a quick browse through your media center code last night and I'll most likely give it a try when you have a fully functional version :). Nice work so far.

Sprig
