### ISSUE TITLE
The api ignores the limited bandwidth setting for vods

### ISSUE THREAD

**Issue by pitsi** [anxdpanic/plugin.video.twitch#691]
### Context

* Add-on Version: 3.0.2
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: Debian testing/unstable x64
* Operating System Language: English (en_us, according to locale's output)

------

### Expected Behavior
When setting a limit to the bandwidth the addon can use, it practically limits the resolution vods and live streams are played. For that reason, with 1.5Mbps (1500000 in the setting), the addon should play them at 480p...

------

### Current Behavior
...but, since yesterday, it does not. Although the setting is respected for live streams and they do play at 480p, vods play at whatever the highest quality is, i.e. the "source quality", which sometimes is even 1080p60 and demands a lot more bandwidth than the set one.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set settings > general > video quality to "bandwidth" and bandwith below it to a number in bps, e.g. 1500000 for 1.5Mbps. 
2. Go to a channel of your choice and select a vod from it. 
3. When it starts playing, press o to check the resolution it plays at.

------

### Log

Messy log output, not full log. At the end it says that the video starts playing properly.
```
2023-12-15 08:29:08.575 T:11866    info <general>: Twitch: Calling |_search| for mode |search| with pos args |[]| and kwargs |{}|
2023-12-15 08:29:08.664 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:10.842 T:11866    info <general>: Skipped 3 duplicate messages..
2023-12-15 08:29:10.842 T:11866    info <general>: Twitch: Calling |_search_history| for mode |list_search| with pos args |['channels']| and kwargs |{}|
2023-12-15 08:29:10.933 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:12.576 T:11866    info <general>: Twitch: Calling |_new_search| for mode |new_search| with pos args |['channels']| and kwargs |{}|
2023-12-15 08:29:12.665 T:11792    info <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2023-12-15 08:29:15.740 T:11866    info <general>: Twitch: Calling |_search_results| for mode |search_results| with pos args |['channels', 'iipk']| and kwargs |{'after': 'MA=='}|
2023-12-15 08:29:16.296 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:18.973 T:11866    info <general>: Skipped 25 duplicate messages..
2023-12-15 08:29:18.973 T:11866    info <general>: Twitch: Calling |_list_channel_video_categories| for mode |channel_videos| with pos args |[]| and kwargs |{'channel_id': '49425476', 'channel_name': 'iipk', 'display_name': 'iiPK'}|
2023-12-15 08:29:19.066 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:20.271 T:11866    info <general>: Skipped 3 duplicate messages..
2023-12-15 08:29:20.271 T:11866    info <general>: Twitch: Calling |_list_channel_videos| for mode |channel_video_list| with pos args |['archive']| and kwargs |{'channel_id': '49425476'}|
2023-12-15 08:29:21.544 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:23.966 T:11866    info <general>: Skipped 25 duplicate messages..
2023-12-15 08:29:23.966 T:11866    info <general>: Twitch: Calling |_play| for mode |play| with pos args |[]| and kwargs |{'video_id': '2001587240'}|
2023-12-15 08:29:26.708 T:11842    info <general>: PVR Manager: Starting cleanup of cached images.
2023-12-15 08:29:26.727 T:11842    info <general>: PVR Manager: Cleaned up 0 cached images.
2023-12-15 08:29:27.275 T:11866 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-12-15 08:29:27.275 T:11866 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-12-15 08:29:27.306 T:11792    info <general>: Skipped 1 duplicate messages..
2023-12-15 08:29:27.306 T:11792    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.twitch/?mode=play&video_id=2001587240
```

------

### Additional Information
There are 2 things I want to point out. The first one is that I noticed the issue on my old laptop which still runs le 9.2.6 and kodi 18.9. I have not upgraded to kodi 19 or newer there because of reasons that are specific to le 10+ and the playback on that system. The log above is from my pc, which runs whatever I mentioned, but I rarely use kodi on my pc.

The second one is how I got to know the bandwith needed for each quality and the answer is simple: with yt-dlp. Here is an output from a live stream
```
$ yt-dlp -F https://www.twitch.tv/eslcs
[twitch:stream] Extracting URL: https://www.twitch.tv/eslcs
[twitch:stream] eslcs: Downloading stream GraphQL
[twitch:stream] eslcs: Downloading stream access token GraphQL
[twitch:stream] 40270210709: Downloading m3u8 information
[info] Available formats for 40270210709:
ID               EXT RESOLUTION FPS │   TBR PROTO │ VCODEC      ACODEC     ABR
──────────────────────────────────────────────────────────────────────────────
audio_only       mp4 audio only     │  160k m3u8  │ audio only  mp4a.40.2 160k
1080p60__source_ mp4 1920x1080   60 │ 6884k m3u8  │ avc1.4D402A mp4a.40.2
160p             mp4 284x160     30 │  230k m3u8  │ avc1.4D401F mp4a.40.2
360p             mp4 640x360     30 │  630k m3u8  │ avc1.4D401F mp4a.40.2
480p             mp4 852x480     30 │ 1428k m3u8  │ avc1.4D401F mp4a.40.2
720p             mp4 1280x720    30 │ 2373k m3u8  │ avc1.4D401F mp4a.40.2
720p60           mp4 1280x720    60 │ 3423k m3u8  │ avc1.4D401F mp4a.40.2
```
And here is one from the vod I tried playing above 
```
$ yt-dlp -F https://www.twitch.tv/videos/2001587240
[twitch:vod] Extracting URL: https://www.twitch.tv/videos/2001587240
[twitch:vod] 2001587240: Downloading stream metadata GraphQL
[twitch:vod] 2001587240: Downloading video access token GraphQL
[twitch:vod] 2001587240: Downloading m3u8 information
[twitch:vod] 2001587240: Downloading storyboard metadata JSON
[info] Available formats for v2001587240:
ID         EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC     ABR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────
sb1        mhtml 110x62       0 │                  mhtml │ images                     storyboard
sb0        mhtml 220x124      0 │                  mhtml │ images                     storyboard
Audio_Only mp4   audio only     │ ~  1.13GiB  353k m3u8  │ audio only  mp4a.40.2 353k
1080p60    mp4   1920x1080   60 │ ~ 20.93GiB 6541k m3u8  │ avc1.64002A mp4a.40.2      Source
160p       mp4   284x160     30 │ ~947.36MiB  289k m3u8  │ avc1.4D000C mp4a.40.2
360p       mp4   640x360     30 │ ~  2.26GiB  706k m3u8  │ avc1.4D001E mp4a.40.2
480p       mp4   852x480     30 │ ~  5.09GiB 1591k m3u8  │ avc1.4D001F mp4a.40.2
720p60     mp4   1280x720    60 │ ~ 11.44GiB 3575k m3u8  │ avc1.4D0020 mp4a.40.2
```
The bandwidth needed for that specific vod at 480p is a bit over 1.5Mbps, which is something that happens from time to time and it then plays at 360p. Any time this happens, I set the limit a bit higher, at like 1.6 or 1.7Mbps, no big deal.

As for the why I am using such a low limit on bandwidth, I have 2 reasons: my internet connection is a mere 12Mbps and I hate it when the vod takes more than a few seconds to load or seek forward/backward. Yes, I rarely watch live streams :/

**Comment by apo86** [comment]
I have no clue how this works on the addon level and what might be wrong.
But have you tried configuring your limits in inputstream.adaptive instead?
So set video quality to "adaptive" and then configure inputstream.adaptive with either bandwidth limits or resultion limits or even a fixed resolution.

I've never used any of this before, but in my testing just now, results were mixed. Some VODs even the addon bandwidth limit seemed to somewhat work, where I could drop it down even to audio only. Other VODs seemed to ignore the setting. With inputstream.adaptive I definitely got lower resolutions accross the board, but also not quite exactly how I expected. For example setting the maximum to 480p, I got a 640p video. On a VOD where the twich web UI itself only had options for 720p and 480p... So I don't know, but maybe you can find a setting that works for you.

If this doesn't help, you'll have to wait for someone smarter than me.

**Comment by pitsi** [comment]
Good Idea, I will try it when I get back home... on Sunday afternoon. I am afk right now, sorry for not mentioning it.

As for the rest, it would be really helpful if someone can reproduce the behavior using only the bandwidth variable, as I describe above. This way I will know it is not an issue on my end only. 
For the 640p video, was it something recorded in vertical mode? If so, it would be 360*640 in order to respect the aspect ratio.

**Comment by apo86** [comment]
I did try the bandwidth setting as well, yesterday with mixed results. For some it was working, for others not at all.
Today it seems better. With 1500000 I almost always get 480p.

**Comment by pitsi** [comment]
Thank you for testing it :)

I tried a vod earlier and it started playing at 480p, without manually selecting the resolution. When I got bored of it, I stopped it and switched to youtube (the kodi addon), without closing or leaving kodi, 
Let's say that the vod was stopped at the 1hr mark. When I got bored of youtube, I went back to that vod, selected it like before and it started from the 1hr mark but at 180p60! Manually selecting the resolution for 480p makes the vod start from the beginning, and that is very annoying.

Maybe the api malfunction has to do with this change :D
https://www.theverge.com/2023/12/13/24000534/twitch-loosens-sexual-content-policy

**Comment by pitsi** [comment]
Yt-dlp is also affected by this mess the api has made
```
$ yt-dlp --get-url -f 480p https://www.twitch.tv/videos/2024029034
ERROR: [twitch:vod] v2024029034: Requested format is not available. Use --list-formats for a list of available formats

$ yt-dlp -F https://www.twitch.tv/videos/2024029034
[twitch:vod] Extracting URL: https://www.twitch.tv/videos/2024029034
[twitch:vod] 2024029034: Downloading stream metadata GraphQL
[twitch:vod] 2024029034: Downloading video access token GraphQL
[twitch:vod] 2024029034: Downloading m3u8 information
[twitch:vod] 2024029034: Downloading storyboard metadata JSON
[info] Available formats for v2024029034:
ID         EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC     ABR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────
sb1        mhtml 110x62       0 │                  mhtml │ images                     storyboard
sb0        mhtml 220x124      0 │                  mhtml │ images                     storyboard
Audio_Only mp4   audio only     │ ~243.42MiB  354k m3u8  │ audio only  mp4a.40.2 354k
1080p60    mp4   1920x1080   60 │ ~  4.39GiB 6547k m3u8  │ avc1.64002A mp4a.40.2      Source
160p       mp4   284x160     30 │ ~198.74MiB  289k m3u8  │ avc1.4D000C mp4a.40.2
360p       mp4   640x360     30 │ ~484.88MiB  706k m3u8  │ avc1.4D001E mp4a.40.2
480p       mp4   852x480     30 │ ~  1.07GiB 1590k m3u8  │ avc1.4D001F mp4a.40.2
720p60     mp4   1280x720    60 │ ~  2.40GiB 3575k m3u8  │ avc1.4D0020 mp4a.40.2

$ yt-dlp --get-url -f 480p https://www.twitch.tv/videos/2024029034
https://d2nvs31859zcd8.cloudfront.net/74f53ac0c4302bc3634f_iipk_43347342475_1704505581/480p30/index-dvr.m3u8
```

**Comment by pitsi** [comment]
And today I got a couple of "No stream found" messages on the vods I tried. They did play with no issues a few minutes later though, so let's hope that the issue is on the api's side and it is (or will be) addressed.

Other than that, my key, which was due to expire on Wednesday (Jan 10th), expired yesterday and I had to make a new one earlier than I expected.

**Comment by pitsi** [comment]
A small discovery which I made earlier. It may not explain the addon's issue completely, but I think it explains the weird output of yt-dlp. The following screenshots are from right clicking on a vof > choose quality. 

This vod here played at 480p, respecting the limited bandwidth setting
![screenshot058](https://github.com/anxdpanic/plugin.video.twitch/assets/5880037/3f596b49-1754-445e-90fb-41c57451991a)

This one though played at its source quality (720p60 to be precise)
![screenshot060](https://github.com/anxdpanic/plugin.video.twitch/assets/5880037/9706f824-1bcb-41c5-b7ec-bd054fe2a167)

Notice the framerate next to the lower resolutions?
For that same reason, on my pc I have these 2 profiles for playing twitch on mpv, since the days mpv was using youtube-dl to resolve the vods' urls.
```
[tw480]
ytdl-format=480p
[tw720]
ytdl-format=720p,720p60
```
Can we have the same on the addon as well? Can you make the addon pick the resolution by number and not by bandwidth?

Both screenshots are from le 9.2.x, which runs kodi 18.9 and twitch 2.6.2, but I assume the api's fault is the same on all systems.

**Comment by pitsi** [comment]
It has been more than a month now and the bs api still has that inconsistency with the bandwidth limit. As a workaround, the user can set the addon to ask for resolution before playback. It is not ideal, but at least it remembers where the vod has stopped and continues from there, regardless if it has played on 480p or 480p30 (or any other quality) before.

**Comment by pitsi** [comment]
The wierd formats with the framerate next to them, e.g. 480p30, are gone since last week and the api seems to have switched to its old ones, and it now respects the limited bandwidth setting. Even yt-dlp works like it should.

Can someone confirm it so as to close the issue?

**Comment by pitsi** [comment]
Closing...
