### ISSUE TITLE
Rework saveHLSToPlaylist

### ISSUE THREAD

**Issue by ingwinlu** [anxdpanic/plugin.video.twitch#73]
i started cleanup of saveHLSTToPlaylist in my python-twitch fork

main things so far: 
-   quit earlier if no data is received, so the whole data does not have to be searched
-   remove some unecessary join/splits

i do this on my fork for now because I have test cases set up which can also be extended to measure time used. Help/Feedback is welcome

https://github.com/ingwinlu/python-twitch/pull/1

**Comment by MrSprigster** [comment]
Nice, I look forward to seeing the end result, faster code is always a good thing! and thanks for input :+1:

**Comment by ingwinlu** [comment]
@MrSprigster can you do me a favor and review it? 

I am down to 33-50% of the execution time of the original now (though I run a rpi :P), my tests all pass but I am not sure if this suitable to pull it upstream yet. 

I also added support for the 'mobile' quality setting which would probably needed to be added somewhere on the xbmc side as well.

**Comment by MrSprigster** [comment]
Will do matey, I'm not near a computer at the moment so I'll take a look
later

**Comment by MrSprigster** [comment]
I like the way this is looking, as well as the code speed increase (especially for devices such as the RPi). When you feel it's optimal, create a pull request (without the testing stuff in ofc) and I'll make the necessary changes to the XBMC side to handle the extra quality option.

**Comment by MrSprigster** [comment]
Merged and I have added the mobile quality to the XBMC settings
