### ISSUE TITLE
HLS Streaming

### ISSUE THREAD

**Issue by mc02** [anxdpanic/plugin.video.twitch#77]
Would it be possible to use the HLS Streams? The streaming in the evening hours is really unstable / connection losts on TwitchXBMC while the Twitch App and Desktop Streaming working fine.
The App and the Desktop is already migrated to HLS afaik.

**Comment by MrSprigster** [comment]
We've been using the HLS streams since version 1.0.3. I recommend lowering your quality settings if you are experiencing buffering.

Sprig

**Comment by mc02** [comment]
Hello Sprig

thanks for the Quick response, oh ok i didnt know that.
Unfortunately the Quality Settings dont affect the Connection dropouts, i get the same disconnecting/unstable streams on Low Setting. 
Here is my xbmc log, can you tell me if you see something obvious? 
http://pastebin.com/Bda1yGvb

**Comment by MrSprigster** [comment]
"Get - asked for new data packet, with nothing available" definitely a network issue somewhere along the line. Possibly bad routing from your ISP to Twitch servers. 

It's worth noting that this add-on doesn't handle any of the playback of the streams, it just passes the stream info to XBMC's built in player and the rest is handled by that.

Sprig

**Comment by mc02** [comment]
Ok but the browser streaming works fine. Does the addon getting the same stream info than the browser?
Feel free to close this any time

**Comment by MrSprigster** [comment]
There's a chance that the API returns different servers than the twitch website uses but it's unlikely. Try opening the playlist that is generated in VLC to eliminate any issues with your XBMC setup. The location of the playlist can be found in the log you posted.

Closing as requested.

Sprig

**Comment by dPing** [comment]
This also might be due to XBMC using google's DNS's as its own instead of a local cache on an ISP/homerouter level DNS.  the defaults being primary: 8.8.8.8 and secondary 8.8.4.4 even with dhcp.  Check to ensure this is set to your local dns (should be same as router)

**Comment by ingwinlu** [comment]
why whould dns have something to do with connection drops?

I am genuinely interested in an answer.
Am 23.06.2014 17:19 schrieb "dPing" notifications@github.com:

**Comment by dPing** [comment]
is coding done by IP address?  if not then it will rely on DNS requests,  If your DNS isn't local to your LAN then every request has to go through all the way to google's dns servers, which is just an extra step IMO. 

EDIT: to answer your question, onyl if 8.8.8.8 doesn't resolve the request in a timely manner would you see a "connection drop" (or as stated above the resolve request changes to a different twitch server).  

from what I understand linux's tool to cache dns requests are broken but browsers usually find their own way to cache DNS so this might be the difference.  

All this is theory and is from a networking standpoint, not a software dev one.

In testing, when I hard set my DNS to my router, this issue goes away.

**Comment by MrSprigster** [comment]
This issue is not caused by DNS. There is only one DNS lookup once the stream has been passed to the player and no matter how long that lookup takes, once the server IP is resolved and the stream begins playing DNS is no longer relevant and it is at this point when mc02 experiences connection issues.

It's most likely either an internal network issue or an issue with the ISP's routing to the servers that the Twitch API is providing.
