### ISSUE TITLE
Unable to view archives of streams, that require subscription

### ISSUE THREAD

**Issue by michaelelleby** [anxdpanic/plugin.video.twitch#78]
For example this video http://www.twitch.tv/sc2proleague/b/543464374 requires you to have a subscription to the channel. Now I have a subscription, however the addon does not start the stream, whenever I try to open it, it just tries for a few seconds and then nothing happens, it returns to the list.

**Comment by ingwinlu** [comment]
plugin does not support logins yet

**Comment by MrSprigster** [comment]
This feature is on the to do list, however it seems most contributing Devs are fairly busy at the moment (myself included). Feel free to develop it if you're capable and submit a pull request.
