### ISSUE TITLE
Channel 'status' can be null in json data - can't do len() on not a string

### ISSUE THREAD

**Issue by grocal** [anxdpanic/plugin.video.twitch#8]
In _createFollowingList()_ function/method we set _name = x['status']_ (line: 154)  and then we check this variable if it's empty _if len(name) <= 0:_ (line: 157). However, and this happened to me, sometimes json data with favorite channels returns status as a null for some channels. Python treats it as a NoneType thing. Therefore we can't do len(name) while name is NoneType. This raises python exception:

```
14:09:57 T:4176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                        Error Type: <type 'exceptions.TypeError'>
                                        Error Contents: object of type 'NoneType' has no len()
```

Easy to fix with type checking of _x['status'] before setting *name_ variable.

And one more thing. It would be much optimized, if getting/setting name variable would be done **after** checking for channel online status. For checking online status we just need only _loginname_.  So only after we know the channel is really online - we do check for name, which we put on streams list on XBMC listing.

And I also do .strip() on _name_ to get rid of white-spaces from start and end of string. It looks better in listing ;)

```
jsonData = getJsonFromTwitchApi('http://api.justin.tv/api/user/favorites/' + username + '.json?limit=100')
if jsonData is None:
    return
for x in jsonData:
    loginname = x['login']
    if xmlDataOnlineStreams.count('<login>'+loginname+'</login>') > 0:
        name = loginname
        if type(x['status']) is unicode and len(x['status']) > 0:
            name = x['status']
        image = x['image_url_huge']
        items.append({'label': name.strip(), 'path': plugin.url_for(endpoint='playLive', name=loginname), 'icon' : image, 'is_playable' : True})
return items
```

**Comment by StateOfTheArt89** [comment]
Hey,
I'm sorry for the delay - i was very busy in the last few days. I see you already fixed it by yourself and did a polish translation :+1: 
Do you close this issue and do a pull request, when you are ready?

**Comment by grocal** [comment]
I can pull it whenever you want. Although you have to review changes by yourself because I've changed couple of things that might not suit you (channel names in entries titles in format "[channel_name] channel_status_text" ;)

**Comment by kokarn** [comment]
I've written a patch that let's the user set what way the channel is displayed, maybe i should add that as well?

**Comment by StateOfTheArt89** [comment]
You mean the count of channels, which should be displayed? That would be great. Can you merge that fix into grocals changes?

**Comment by kokarn** [comment]
It has changes both for how many channels should be displayed and how they should be displayed, eg a setting to choose in what way the names are displayed.

[channel name] - [channel status] 
[viewers] - [channel name] - [channel status] 
[channel name] 
[channel status] 

and so on.

**Comment by StateOfTheArt89** [comment]
Even better :) - i pulled grocals changes into my repository. Could you integrate that feature into the current version?

**Comment by kokarn** [comment]
I'll have a look at it when i get home, so hopefully done later today.

**Comment by kokarn** [comment]
Noticed now that you've changed to xbmcswift2 and i really don't feel like getting into that stuff and getting it set up right now, sorry.

The changes i had implemented uses the official "follows" part of the API, https://github.com/justintv/Twitch-API/blob/master/resources/follows.md and uses a wrapper function for the title display so that you can edit it in settings.

**Comment by StateOfTheArt89** [comment]
No, problem - i will integrate that asap

**Comment by kokarn** [comment]
You might want to know that there is a Team API now as well, at least for listing teams.

https://api.twitch.tv/kraken/teams

**Comment by StateOfTheArt89** [comment]
Yeah, I saw the message. I going to implement that too.
