### ISSUE TITLE
Can't play highlights or past streams

### ISSUE THREAD

**Issue by spiffomatic64** [anxdpanic/plugin.video.twitch#80]
Getting this error consistently on all past/highlight videos

20:11:19 T:2364535872  NOTICE: Previous line repeats 1 times.
20:11:19 T:2364535872 WARNING: CreateLoader - Unsupported protocol(plugin) in plugin://plugin.video.twitch/playVideo/c4671857/
20:11:19 T:2515530816  NOTICE: Thread LanguageInvoker start, auto delete: false
20:11:19 T:2515530816  NOTICE: -->Python Interpreter Initialized<--
20:11:20 T:2515530816  NOTICE: [xbmcswift2] Request for "/playVideo/c4671857/" matches rule for function "playVideo"

It looks like its going to start playing, then just stops (no errors visibly) 

Can play live streams without issue though. 

I was able to play past videos/highlights a few weeks ago, possible twitch changed something on their side?

**Comment by ingwinlu** [comment]
hey @spiffomatic64 is this still an issue, when I looked at video playback because of the quality related stuff everything worked fine

**Comment by spiffomatic64** [comment]
The last I tried, it was working fine, so I'll close this. (I've run into a few problems with twitch and this plugin that have automagically righted themselves, and im assuming its twitch changing things on their side (would line up with their recent drm, etc changes))
