### ISSUE TITLE
Past Broadcasts in lower quality

### ISSUE THREAD

**Issue by defoeyido** [anxdpanic/plugin.video.twitch#81]
Hey having an issue getting past broadcasts to play in the lower quality. I can view the 480p on the site but they're all 720p+ on xbmc if I try and view any past broadcast. Any chance you could take a look at bringing in the lower quality?

Thanks

**Comment by MrSprigster** [comment]
Hi @defoeyido, 

I'll take a look at this when I get a little more time on my hands and see if there's an option in the API to request a  lower quality stream for the past broadcasts (I assume there will be) and if there is I'll link it directly to the quality options in settings.

Sprig

**Comment by ingwinlu** [comment]
is this even possible right now?

in a browser I can't select quality for past broadcasts. also can not find anything in the v2 api.

**Comment by MrSprigster** [comment]
I haven't had a chance to look so not sure. But it sounds like it isn't
possible based on your findings. Sorry OP.

Sprig

**Comment by dPing** [comment]
It is possible.  If it is streamed with transcode, it is recorded with transcode.

i.e. http://www.twitch.tv/esltv_sc2/c/5039141

**Comment by ingwinlu** [comment]
hu good to know,  on it

**Comment by ingwinlu** [comment]
@defoeyido this should be resolved now, can you confirm so this can be closed?

**Comment by defoeyido** [comment]
Hey yeah its working great now thanks!
