### ISSUE TITLE
delete unnecessary parts in twitch.py

### ISSUE THREAD

**Issue by ingwinlu** [anxdpanic/plugin.video.twitch#85]
Hi,

since I am currently running through everything in twitch.py to clean up, I would like to propose deletation of stuff that is not needed anymore. this mainly concerns `getRTMPUrl` and functions it calls, see here: http://www.heroicdebugging.biz/static/htmlcov/_home_winlu_gitrepos_python-twitch_twitch___init__.html

while the report was generated for my fork, I think it still applies to this repo as well

**Comment by MrSprigster** [comment]
Deletion of unused code is welcomed (I currently don't have time to do this myself).
