### ISSUE TITLE
Fast forward in past broadcasts is very, very slow

### ISSUE THREAD

**Issue by michaelelleby** [anxdpanic/plugin.video.twitch#86]
Every time I try to change to a specific time in a past broadcast stream, it takes between 1:30 and 3 minutes before it resumes playback. I've tried with both hardware and software decoders and hard/software renderers, same result.

This is what the log says when skipping in the video:
14:17:46 T:6888   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playVideo/a564796428/]
14:17:46 T:6888  NOTICE: DVDPlayer: Opening: http://media-cdn.twitch.tv/store155.media102/archives/2014-9-3/live_user_wcs_europe_1409759544.flv
14:17:46 T:6888 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:17:46 T:5720  NOTICE: Thread DVDPlayer start, auto delete: false
14:17:46 T:5720  NOTICE: Creating InputStream
14:17:46 T:5720  NOTICE: Creating Demuxer
14:17:46 T:1568  NOTICE: Thread FileCache start, auto delete: false
14:17:47 T:5720  NOTICE: Opening video stream: 0 source: 256
14:17:47 T:5720  NOTICE: Creating video codec with codec id: 28
14:17:47 T:5720  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
14:17:47 T:5720  NOTICE: Creating video thread
14:17:47 T:5720  NOTICE: Opening audio stream: 1 source: 256
14:17:47 T:5720  NOTICE: Finding audio codec for: 86018
14:17:47 T:5624  NOTICE: Thread DVDPlayerVideo start, auto delete: false
14:17:47 T:5624  NOTICE: running thread: video_thread
14:17:47 T:5720  NOTICE: Creating audio thread
14:17:47 T:4640  NOTICE: Thread DVDPlayerAudio start, auto delete: false
14:17:47 T:4640  NOTICE: running thread: CDVDPlayerAudio::Process()
14:17:47 T:4640  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
14:17:47 T:5624  NOTICE:  fps: 25.000000, pwidth: 1920, pheight: 1080, dwidth: 1920, dheight: 1080
14:17:47 T:5624  NOTICE: Display resolution DESKTOP : 1920x1080@ 60.00 - Full Screen (16)
14:20:48 T:6896  NOTICE: Found 2 Lists of Devices
14:20:48 T:6896  NOTICE: Enumerated DIRECTSOUND devices:
14:20:48 T:6896  NOTICE:     Device 1
14:20:48 T:6896  NOTICE:         m_deviceName      : {E0A1BA6F-1682-4914-A457-27248481F836}
14:20:48 T:6896  NOTICE:         m_displayName     : SPDIF - Realtek Digital Output (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_displayNameExtra: DIRECTSOUND: Realtek Digital Output (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 48000
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_AC3,AE_FMT_DTS
14:20:48 T:6896  NOTICE:     Device 2
14:20:48 T:6896  NOTICE:         m_deviceName      : {F8C0C205-4E11-4FCD-B3F5-D716FD39875E}
14:20:48 T:6896  NOTICE:         m_displayName     : Speakers - Speakers (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_displayNameExtra: DIRECTSOUND: Speakers (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 48000
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
14:20:48 T:6896  NOTICE:     Device 3
14:20:48 T:6896  NOTICE:         m_deviceName      : default
14:20:48 T:6896  NOTICE:         m_displayName     : default
14:20:48 T:6896  NOTICE:         m_displayNameExtra:
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 48000
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
14:20:48 T:6896  NOTICE: Enumerated WASAPI devices:
14:20:48 T:6896  NOTICE:     Device 1
14:20:48 T:6896  NOTICE:         m_deviceName      : {E0A1BA6F-1682-4914-A457-27248481F836}
14:20:48 T:6896  NOTICE:         m_displayName     : SPDIF - Realtek Digital Output (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_displayNameExtra: WASAPI: Realtek Digital Output (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_DTS,AE_FMT_AC3,AE_FMT_AAC,AE_FMT_S24NE4,AE_FMT_S24LE4,AE_FMT_S24BE4,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
14:20:48 T:6896  NOTICE:     Device 2
14:20:48 T:6896  NOTICE:         m_deviceName      : {F8C0C205-4E11-4FCD-B3F5-D716FD39875E}
14:20:48 T:6896  NOTICE:         m_displayName     : Speakers - Speakers (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_displayNameExtra: WASAPI: Speakers (Realtek High Definition Audio)
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR,FC,LFE,SL,SR,BL,BR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_S24NE4,AE_FMT_S24LE4,AE_FMT_S24BE4,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_LPCM
14:20:48 T:6896  NOTICE:     Device 3
14:20:48 T:6896  NOTICE:         m_deviceName      : default
14:20:48 T:6896  NOTICE:         m_displayName     : default
14:20:48 T:6896  NOTICE:         m_displayNameExtra:
14:20:48 T:6896  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:20:48 T:6896  NOTICE:         m_channels        : FL,FR,FC,LFE,SL,SR,BL,BR
14:20:48 T:6896  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
14:20:48 T:6896  NOTICE:         m_dataFormats     : AE_FMT_S24NE4,AE_FMT_S24LE4,AE_FMT_S24BE4,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_LPCM

**Comment by ingwinlu** [comment]
Hey,

sadly there is nothing we can do for you on our end, the plugin just passes the urls(split up in blocks) of the past broadcast to the xbmc player

**Comment by michaelelleby** [comment]
I was thinking since I can pass ?t=300s to livestreamer, start the stream at 5 minutes, that it might be possible to do the same here.
But that is something the XBMC player must handle ?

**Comment by ingwinlu** [comment]
well we could parse the duration that is given with the chunks to the listitems we add to the playlist (which is then passed to xbmc player) but I doubt that the player itself actually checks that info (since it would be stupid)

so no I don't think it is possible to improve that behaviour

**Comment by MrSprigster** [comment]
Fixed in #110
