### ISSUE TITLE
'Source' quality stream?

### ISSUE THREAD

**Issue by cr08** [anxdpanic/plugin.video.twitch#87]
Stupid question as I haven't looked at the source in a while but on live streams on the 'Highest quality' setting is the plugin pulling the Source stream or just the transcoded High stream? Long time follower of Wyld who streams at 960x540 and it always seems like the High transcode is noticeably worse quality than Source compared to other streamers who do 720p+ where the quality difference is much more subtle. And watching via XBMC it tends to show that reduced quality.

**Comment by ingwinlu** [comment]
plugin plays source quality on highest setting, you might have your xbmc settings set to a lower resolution or misconfigured the plugin
