### ISSUE TITLE
Follow Games feature

### ISSUE THREAD

**Issue by georgetogo** [anxdpanic/plugin.video.twitch#92]
Twitch just recently implemented the ability to follow games. They essentially act as bookmarks to specific games. 

I was wondering if we can get that feature in the xmbc addon?

Thanks and great work!

**Comment by ingwinlu** [comment]
you know you can favorite a game in xbmc already? just go games -> select the game you want to 'follow', activate the context menu and add to favorites, same functionality

**Comment by georgetogo** [comment]
Oh good to know!
