### ISSUE TITLE
Past broadcasts does not appear to be working 

### ISSUE THREAD

**Issue by spiffomatic64** [anxdpanic/plugin.video.twitch#94]
getting this in xbmc.log

17:29:15 T:2896262208 WARNING: CreateLoader - Unsupported protocol(plugin) in plugin://plugin.video.twitch/playVideo/a574780260/
17:29:15 T:2769237056  NOTICE: Thread LanguageInvoker start, auto delete: false
17:29:16 T:2769237056  NOTICE: -->Python Interpreter Initialized<--
17:29:16 T:2769237056  NOTICE: [xbmcswift2] Request for "/playVideo/a574780260/" matches rule for function "playVideo"

Using version: 1.1.7

**Comment by MrSprigster** [comment]
Hi @spiffomatic64, 

Are you still experiencing this issue? I'm not able to reproduce your problem at my end.

Sprig

**Comment by MrSprigster** [comment]
I'll assume your silence indicates the issue is no longer presenting.

**Comment by spiffomatic64** [comment]
Yep, confirmed working, didnt get a chance to verify it until now

**Comment by MrSprigster** [comment]
Thanks! :-)
