### ISSUE TITLE
Distorted Video but audio is fine

### ISSUE THREAD

**Issue by Dendore** [anxdpanic/plugin.video.twitch#96]
Run into an issue where all streams load as fuzzy green distorted video but the audio is fine. It's like watching a scrambled cable channel from back in the day. This is only with twitch. I have tried reinstalling but that didn't do anything.

Can anyone help me figure this out.

**Comment by ingwinlu** [comment]
I only know this if the streamer you choose does stream in a strange resolution, i.e. widescreen or something. nothing the plugin can do to solve this

**Comment by Dendore** [comment]
Interesting. It seems to happen with every stream I try to watch though. I will test some more to verify. I can also test with my own account. Do you know what settings I would have to use for it to play nice?

**Comment by MrSprigster** [comment]
Your issue falls outside of the scope of this addon I'm afraid. I hope you manage to find a solution.

FAQ:
I'm having issues with the playback of streams (buffering, dropping, stuttering).

This Addon does not handle any aspect of the playback of Twitch streams (that would be the XBMC Video Player), it simply tells XBMC what to play. The Addon does however provide Quality Options which may help if your internet connection / computer specs are below requirements for HD streams.
