### ISSUE TITLE
RPi OpenELEC 4.2.1 No audio and screen just goes black, no streams play anymore

### ISSUE THREAD

**Issue by Slarky** [anxdpanic/plugin.video.twitch#97]
Hi, I noticed that the twitch.tv AddOn stopped working a week ago. It started with a massive audio delay on certain streams und then a day later all the streams just stay black with no audio (i.e. I click on a stream I want to watch and then the screen goes black and the playback stops at 00:00:07 or 00:00:03; though I see smth from the stream when I stop it).

Is it just me?

Specs: RPi/OpenELEC 4.2.1, latest Twitch.tv AddOn

**Comment by MrSprigster** [comment]
No issues at my end so most likely just you. Feel free to post a log and I'll see if I can identify the cause.

**Comment by Slarky** [comment]
There's a full debug log:

http://privatepaste.com/download/c4ef68ed63

**Comment by ingwinlu** [comment]
plugin does work correctly according to your log, might be an issue with your version of ffmpeg or omxplayer.

**Comment by Slarky** [comment]
Thanks for your help guys. I have no idea what was wrong, but completely reinstalling OpenELEC worked. The Twitch.tv AddOn is fine now.

Thanks again and keep it up! :)
