### ISSUE TITLE
XBMC Twitch.tv plugin, every stream "unplayable" 

### ISSUE THREAD

**Issue by nrk666** [anxdpanic/plugin.video.twitch#99]
So, I was running Twitch.TV plugin 1.1.1 from XBMC repo an hour ago, works fine. The plugin correctly reads my "followed" list, but every stream I try to connect to yields these errors, including streams not on my followed list: 

19:52:26 T:139979527272192  NOTICE: Thread LanguageInvoker start, auto delete: false
19:52:26 T:139979527272192  NOTICE: -->Python Interpreter Initialized<--
19:52:26 T:139979527272192  NOTICE: [xbmcswift2] Request for "/playLive/ANYSTREAMER/" matches rule for function "playLive"
19:52:26 T:139980386551616   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/ANYSTREAMER/]

I manually updated to 1.1.7 through git and no change. Every stream produces this error now. 

I tried lowering the Playback Quality, no effect. 

I've also gone back and tried it on several other of my XBMC installs and they all have the same issue. 

Twitch may have changed something that broke the plugin. 

I can use the mobile twitch.tv app for iPad and it works fine, so I know it isn't a connectivity issue, this seems localized only to the XBMC plugin.

**Comment by JohnMcLear** [comment]
Duplicate of https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/98

**Comment by JohnMcLear** [comment]
I'm going to bump twitch support to see if they have deprecated an API or so.

**Comment by nrk666** [comment]
Tested on XBMC 13.2 Gotham on Windows, Kodi 14RC3 on Windows, Gotham 13.2 on FireTV and Gotham 13.2 on OpenElec, all have the same issue.

**Comment by nrk666** [comment]
Reports of tardsplaya also broken, so probably a twitch backend change. I hope this isn't the end of this addon.

**Comment by nrk666** [comment]
I can confirm this fix is working. Tested on same versions/platforms listed above. 

Thanks ntfwc!

**Comment by ntfwc** [comment]
No problem. I'm glad I was able to help keep things working.

**Comment by ingwinlu** [comment]
this also changes how offline streams should be handled, ill prepare a complete pr based on @ntfwc changes

**Comment by MrSprigster** [comment]
Fixed in #101

**Comment by JohnMcLear** [comment]
Thanks @ntfwc and @MrSprigster 

Great job :)
